### ISSUE TITLE
Jasmine/Karma unit test example

### ISSUE THREAD

**Issue by paulsheldrake** [firebase/angularfire#161]
Hello

Would it be possible to get a reference example on how to unit test a controller with an AngularFire/Firebase dependency?

**Comment by ThibaultJanBeyer** [comment]
404 page not found…

**Comment by jwngr** [comment]
That's because those links are nearly three years old. The repo is https://github.com/firebase/angularfire-seed and the end-to-end tests are now at https://github.com/firebase/angularfire-seed/tree/master/e2e-tests.
