### ISSUE TITLE
Support request/response interceptors like $http

### ISSUE THREAD

**Issue by kennethlynne** [firebase/angularfire#184]
It would be nice to be able to intercept requests and responses like one is able to using $http. For example to be able to integrate smoothly with services like Andy Joslins [promise tracker](https://github.com/ajoslin/angular-promise-tracker)

**Comment by maqboolkhan** [comment]
hallo @anantn i have one use to show spinner until all firebase request are not complete (with Angular 6)! I wrote Angular interceptor but as you mentioned above it did not work so i am wondering now how to achieve it ? can you please help
Thanks in advance
