### ISSUE TITLE
Handle priority changes

### ISSUE THREAD

**Issue by anantn** [firebase/angularfire#19]
From: http://stackoverflow.com/questions/16159576/im-convinced-that-ref-auth-is-bugged

"If you want to see the bugs in AngularFire, change priority of items. Then you'll see AngularFire unable to correctly move the items in the collection"

**Comment by sivaramsi** [comment]
http://plnkr.co/edit/Lp9IVCXhhCfUbbemoqcL?p=preview update the demo link
