### ISSUE TITLE
Using $firebase().$on('value', ...) does NOT work

### ISSUE THREAD

**Issue by skingsland** [firebase/angularfire#272]
I have 2 types of entities stored in Firebase, Cars and Users. Each car has a userID, which is the identity of the user who owns the car. I have a web page where I display data about the car, and I want to display the name of the car's owner. This means that I need to sync _both_ the car and the user name to the `$scope`, so I can display both sets of data on the same web page.

I was previously getting the car and user data using Firebase refs and `once('value', ...)` calls, which works just fine:

```
// get a Firebase reference to the car
var carRef = ref.child('cars').child($scope.carID);
// ...and bind the car to the $scope, so I can display it's data (not shown)

// now use the car's userID to look up the user's name, and bind it to the $scope
carRef.child('userID').once('value', function(userID) {
    // use the userID to look up the user, and bind her data to the $scope
    // (again not shown, but works just fine)
});
```

Now I'm trying to do the same thing using the new $firebase() API, which I've read about in the new [API docs](https://www.firebase.com/docs/angular/reference.html#on-eventname-handler), [angularFire-seed](https://github.com/firebase/angularFire-seed) project, StackOverflow [questions](http://stackoverflow.com/questions/20597581/a-little-clarity-on-getting-key-values-using-angularfire-v2) and even online [tutorials](http://www.thinkster.io/angularjs/dVRdu6dXNT/8-adding-comments-and-voting-to-our-application). But it's not working for me like it should:

```
var carRef = ref.child('cars').child($scope.carID);

// get a $firebase reference to the car
var $car = $firebase(carRef);

// now get the $car's userID, so we can look up the user
$car.$child('userID').$on('value', function(userID) {
    // this is never called!
});
```

Based on the firebase API [documentation](https://www.firebase.com/docs/angular/reference.html#on-eventname-handler), calling `$on('value', ...)` should work just as well as calling `on('value', ...)` or `once('value', ...)` (as I did above). But the `'value'` event's callback is never called! If I change `'value'` to `'loaded'` then it does in fact work, but only the first time. If I view another car's page (a different angular route) and then come back, it doesn't work. Only if I do a full page refresh does the `'loaded'` event's callback get called again. Which actually makes complete sense, given the docs for `loaded`.

Anyway, why isn't this working as expected?

Here are the versions I'm using:
- firebase.js 1.0.5
- firebase-simple-login.js 1.2.5
- angular.js 1.2.14
- angular-route.js 1.2.14
- angularfire.js 0.7.0

**Comment by romelgomez** [comment]
Hi @katowulf,  

This comment is current valid: 

https://github.com/firebase/angularfire/issues/272#issuecomment-37212003

I trying this: 

    userPublicationsRef.orderByChild('releaseDate').on('value', function(snapshot) {
      $scope.account.publications = snapshot.val();
    });

i have to use: 

      $scope.$apply();  

or

       $timeout(function() {
         $scope.account.publications = snapshot.val();
       });

To make this work.

**Comment by romelgomez** [comment]
@katowulf  

when i put that code into a promise, it work with not use $apply(); or $timeout

    var publications = function(){
      var deferred = $q.defer();

      var userPublicationsRef = FireRef.child('publications').child($scope.account.user.uid);
      userPublicationsRef.orderByChild('releaseDate').on('value', function(snapshot) {
        deferred.resolve(snapshot.val());
      },function(error){
        deferred.reject(error);
      });

      return deferred.promise;
    };

    $scope.httpRequestPromise = publications()
      .then(function(publications){
        $scope.account.publications = publications;
      });

**Comment by katowulf** [comment]
@romelgomez your comments have been deleted. This thread is over a year old, your comments were unrelated to the original question, and your comments were unrelated to AngularFire. If you want to discuss, reach out on [firebase-talk](https://groups.google.com/forum/#!pendingmsg/firebase-talk) or submit a new issue.
