### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by staunsholm** [firebase/angularfire#31]
I see that offline support was 'not yet' in February: http://stackoverflow.com/questions/14670394/does-firebase-allow-an-app-to-start-in-offline-mode

I created some simple offline support for now, but I'd really like firebase to handle this. Is this still on it's way?

Mkkl.

PS! Doing a Spotify app btw, seems to work as expected so far.

**Comment by sebastianovide** [comment]
any updates ? thanks

**Comment by katowulf** [comment]
This isn't the forum for questions about the SDK or Firebase's release schedule. Also, Firebase does not offer release dates to the public. Offline persistence is a top priority for us and under active development as we speak.

**Comment by jeremiahgibson91** [comment]
any updates ? thanks

**Comment by jwngr** [comment]
No updates to share. As Kato clearly mentioned above, this is not the correct venue for these kinds of discussions. Once the web SDK has full offline support, there will be plenty of announcements and discussion.
