### ISSUE TITLE
'Firebase' is not defined error

### ISSUE THREAD

**Issue by stcho** [firebase/angularfire#362]
I am trying to utilize angularFire in my app, I followed this guide (https://www.firebase.com/tutorial/#tutorial/angular/0), and I even tried generator-angularfire, however both times, initially I get

```
  Uncaught Error: [$injector:modulerr] Failed to instantiate module pepsiAppApp due to:
  Error: [$injector:modulerr] Failed to instantiate module firebase due to:
  Error: [$injector:nomod] Module 'firebase' is not available! You either misspelled the m...<omitted>...1) 
```

To fix this issue above I added these two lines right by my bower_components in index.js

```
   <script src='https://cdn.firebase.com/js/client/1.0.15/firebase.js'></script>
   <script src='https://cdn.firebase.com/libs/angularfire/0.7.0/angularfire.min.js'></script>
```

and changed the version of angularfire from 0.8.0 to 0.7.0 following this thread (http://stackoverflow.com/questions/25021003/firebase-angularfire-error-module-firebase-is-not-available?lq=1) 

However, I get another error

```
app/scripts/controllers/main.js
   line 32   col 23  'Firebase' is not defined.
```

more detail on this thread (http://stackoverflow.com/questions/25021640/angularfire-firebase-is-not-defined?lq=1)

How do I resolve this issue?

**Comment by thedig** [comment]
This is not the same as the "duplicated" referenced answer.  I'm having this same issue and there's no syntax issues in my bower.json.

**Comment by jamestalmage** [comment]
@thedig This is a 6 month old issue. There have been drastic changes to all of angularfire in that amount of time.

That said, I did take a look at the current tutorial and there is a problem. 

Those docs are jumping the gun on the upcoming angular release. Angular 1.4.0 is currently in beta and not available at the url in that tutorial. If you really want to use **bleeding** edge angular, you could change the angular script tag to point at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-beta.5/angular.min.js.

However, I would recommend you avoid any beta release unless you are desperate for some functionality in it. Here is a template to get you going.
```html
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.4/angular.min.js"></script>
	 <script src="https://cdn.firebase.com/js/client/2.2.1/firebase.js"></script>
	 <script src="https://cdn.firebase.com/libs/angularfire/1.0.0/angularfire.min.js"></script>
	 <script>
	   angular.module('myModule',['firebase'])
	 		//.controller()
	 		//.directive()
	 		//...
	 </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by JimTheMan** [comment]
I'm getting this error as well:

![ngnjorg](https://cloud.githubusercontent.com/assets/5354163/19175761/9d4fcbb2-8c07-11e6-8d95-81897049dc41.png)

**Comment by jwngr** [comment]
Locking conversation on this thread. @JimTheMan - please stop spamming other issues and properly open one of your own which follows the issue template.
