### ISSUE TITLE
Calling $save does not trigger a $watch event

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#368]
When we call `$save` on a local object, we push the current value to the server. If a change occurs, then a child_changed event will be triggered. However, because the data will already be set locally, no change will occur, and therefore neither `$FirebaseArray` nor `$FirebaseObject` will trigger a $watch event after. Consider sending notifications for these?

**Comment by jaymanned** [comment]
So now, how can I tell from $watch() if the change was remote or local? In my case I only need to process the remote ones...

**Comment by katowulf** [comment]
@jaymanned please post your own issue, rather than replying to one closed 2 years ago.
