### ISSUE TITLE
0.8.0 doesn't save date objects

### ISSUE THREAD

**Issue by joshbowdoin** [firebase/angularfire#381]
Previously AngularFire (0.7.1) called `angular.fromJson(angular.toJson(record))` before a save, which converted date objects to JSON dates.  Could this be added back as the last line of `firebaseUtils.toJSON()?`

As it stands now, I have to handle each date before the save, otherwise they are simply omitted (no errors or anything).  Or am I missing something?

**Comment by rcuddy** [comment]
Just a note for anyone who finds this while trying to sort out dates not saving to firebase, katowulf's snippet no longer works in 1.0.0, trying to decorate the firebaseUtils results in a circular reference error.

The theory is still sound with firebaseObject and overriding the $save and $$updated methods. Your answer will be found over here:
https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-services-decorating-the-services

**Comment by minervadreaming** [comment]
@rcuddy : thanks for that update, it's exactly what I'm looking for.  However, being new to Firebase, I don't know where to apply this code.  Do you know of a good resource with a better explanation?

**Comment by katowulf** [comment]
There is an example of using the extend methods and working with dates [in the API](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-services-firebasearrayextend).

**Comment by minervadreaming** [comment]
Hi @katowulf.  Thanks, I did find the example in the APIs in the "Decorating the Services" section.  However, being quite new and after having tried to insert said code into the places that I thought were logical (and failing), I was hoping for something a little more illustrative.

**Comment by katowulf** [comment]
Yeah, I'm really not sure what I can add to this example. I just don't understand what's left to illustrate. I'm happy to help, but you're going to have to a) start a new issue as this is a closed thread from over a year ago and b) illustrate the problem and where you're having trouble with the example.

```
// an object to return in our WidgetFactory
app.factory("Widget", function($firebaseUtils) {
  function Widget(snapshot) {
    // store the record id so AngularFire can identify it
    this.$id = snapshot.key();

    // apply the data
    this.update(snapshot);
  }

  Widget.prototype = {
    update: function(snapshot) {
      var oldData = angular.extend({}, this.data);

      // apply changes to this.data instead of directly on `this`
      this.data = snapshot.val();

      // add a parsed date to our widget
      this._date = new Date(this.data.date);

      // determine if anything changed, note that angular.equals will not check
      // $value or $priority (since it excludes anything that starts with $)
      // so be careful when using angular.equals()
      return !angular.equals(this.data, oldData);
    },

    getDate: function() {
      return this._date;
    },

    toJSON: function() {
      // since we changed where our data is stored, we need to tell AngularFire how
      // to get the JSON version of it. We can use $firebaseUtils.toJSON() to remove
      // private variables, copy the data into a shippable format, and do validation
      return $firebaseUtils.toJSON(this.data);
    }
  };

  return Widget;
});

// now let's create a synchronized array factory that uses our Widget
app.factory("WidgetFactory", function($firebaseArray, Widget) {
  return $firebaseArray.$extend({
    // change the added behavior to return Widget objects
    $$added: function(snap) {
      // instead of creating the default POJO (plain old JavaScript object)
      // we will return an instance of the Widget class each time a child_added
      // event is received from the server
      return new Widget(snap);
    },

    // override the update behavior to call Widget.update()
    $$updated: function(snap) {
      // we need to return true/false here or $watch listeners will not get triggered
      // luckily, our Widget.prototype.update() method already returns a boolean if
      // anything has changed
      return this.$getRecord(snap.key()).update(snap);
    }
  });
});
```

**Comment by katowulf** [comment]
Also found this old fiddle I wrote that demonstrates date manipulations using $extend. Updated it to 1.0.0. code base. Should be helpful as a simplified example.

http://jsfiddle.net/katowulf/syuzw9k1/

**Comment by minervadreaming** [comment]
@katowulf : Very helpful indeed.  Thank you for taking the time!
