### ISSUE TITLE
$push({new:'record'}) to child of $firebase reference?

### ISSUE THREAD

**Issue by irfaan** [firebase/angularfire#402]
I have a `$firebase` ref to 'a/b' and wish to push a new record to 'a/b/c' (i.e. have firebase create new key with value {new:'record'}), such that it will result in: `a/b/c/-Joi2392d09` with {new:'record'} as its value.

How do I go about doing this?

```
// Setup
var db = new Firebase('https://example.firebaseio.com/');
$scope.remote = $firebase(db.child('a/b')).$asObject();

// How do we push to a/b/c?
$scope.remote.c.$push({new:'record'}); // error - $push is not a function.
```

I can try using `$inst()`, but i can only push to 'a/b'; I do not know how to $push a record to a child of the reference. Any ideas?

Thank you! Love the changes to the API in the latest release.

**Comment by Snehitha09** [comment]
[data (1).zip](https://github.com/firebase/angularfire/files/1263195/data.1.zip)
@katowulf @irfaan hey thanks for your suggestions, had a clarification, if you could please guide me, 
i have a table with 2 root nodes 
1)Parent 
2)Child 
So when i do a post information to parent a key is added along with the values i pass, 
Now in the child root i would want to reference the corresponding parent and then generate a specific key to the child and then the values that i have passed, so this is how i would want, will attach an example
