### ISSUE TITLE
Support controllerAs in $bindTo

### ISSUE THREAD

**Issue by unclejustin** [firebase/angularfire#441]
I can't see a way to use controllerAs syntax with bindTo without first dumping the $scope to a property on this. Is there some way to bind directly to this?

Example:

```
syncObject.$bindTo($scope, 'data'); // Works
syncObject.$bindTo(this, 'data'); // Fails

this.scope = $scope;
syncObject.$bindTo(this.scope, 'data'); // Works but is ugly
```

**Comment by ratbeard** [comment]
I tried the above but it did not work as $scope.data is undefined.  I believe because the data has not synced yet.

I was able to do it by binding to the controllerAs name I'm using in the view.  A little hacky, but works:

```
company.$bindTo($scope, 'controllerName.company')
```

**Comment by katowulf** [comment]
Note that `$bindTo()` is really just a convenience and any complicated hacks to try and make it work with things other than `$scope` are probably more work than they are worth. It's generally straightforward to just call `$save()` after making changes to the data.
