### ISSUE TITLE
Remove `$firebase` object

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#501]
This is causing a lot of confusion and doesn't provide any capabilities that don't already exist in the SDK. Firing the $digest scope is now superfluous.

Provide examples in the guide or readme for working direcly with the SDK.

Pass a ref directly to $FirebaseObject and $FirebaseArray. Add a $getRef() method to replace $inst().

**Comment by puf** [comment]
Ooh... can I vote for this one? Or is it already done?
