### ISSUE TITLE
Unit test for a service

### ISSUE THREAD

**Issue by annabellor** [firebase/angularfire#520]
How can I make a unit test for a service (factory) in combination with angularfire?

I also see you use an own mock file and not the [mockfirebase](https://github.com/katowulf/mockfirebase), why is that?

Thanks for this btw! I'm new with firebase in combination with angularjs :).

**Comment by katowulf** [comment]
We use mockfirebase. This looks like the same question you asked at mockfirebase repo. Cheers.

**Comment by annabellor** [comment]
Yes it was, totally forgot about this one xD
