### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by geekinventures** [firebase/angularfire#522]
Hello,

Unless I am misunderstand the language here....

Under the $asObject() document for the $bindTo() function you have $set as the method to "write the changes to the database" however you are reference a Firebase reference not a $firebase reference.  Unless these two are the same then I think there is an error in your documentation.  Your documentation states they are not are not the same and have different "set" functions, one being $set and the other .set.  A "Firebase" reference would only have the method .set and NOT $set.  

Here is the line of code from the documentation that I believe is incorrect. 
var ref = new Firebase(URL); //YOU CREATE A REGULAR Firebase reference which does not have $set method only .set method. 

var obj = $firebase(ref).$asObject();

obj.$bindTo($scope, "data").then(function() {
   console.log($scope.data); // { foo: "bar" }
   $scope.data.foo = "baz";  // will be saved to Firebase
   ref.$set({foo: "baz"});   // THIS IS INCORRECT as you are not referencing the $firebase object. 

//SHOULD THIS BE
//this to me makes more sense due to the fact that $set IS a function of $firebase object. 
obj.$set({foo: "baz"}); 
});

As you can see, the ref is a Firebase object and not the $firebase object.  According to your documentation $firebase DOES have a $set method but it does not have a .set method.  When you try to run this code it says this is undefined.  The regular "Firebase" object does have a .set method but not a $set method.  

So I am confused as to what exactly is needed to be done here.  Do I use .set on my Firebase reference?  If this is the case I believe the documentation should be changed to reflect this.  If this is not the case feel free to laugh at my stupidity :)

**Comment by jwngr** [comment]
@geekinventures - You are correct that our documentation is wrong. I think your solution is still a bit off though. We just want `ref.set()` instead of `ref.$set()`. The point with that line is that if you change the underlying Firebase ref that you have an object bound to, it will update Firebase and you locally bound variable.

Thanks for pointing it out! I'll get it fixed right now and the change will go out with our next website deploy early this week. I'm going to close this issue since we are now tracking it internally.

**Comment by geekinventures** [comment]
Yes, I modified the ref.$set to ref.set and it stopped throwing the error.  What I meant by "it makes sense" is that if your original documentation was supposed to be obj.$set then it makes sense the code would work.  But as you stated, the documentation needed some tweaking :) 

Now that I have changed it, it works beautifully!

**Comment by jwngr** [comment]
Great, thanks again for the tip!
