### ISSUE TITLE
Invalid documentation for createUser method

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [firebase/angularfire#525]
In [documentation example](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-users-and-authentication-createusercredentials) looks like this
``` javascript
$scope.authObj.$createUser({
  email: "my@email.com",
  password: "mypassword"
})
```

This code gives an error: Firebase.createUser failed: First argument must contain the key "email" with type "string"

The reason is that in angularfire.js line 634 $createUser is mapped to createUser internal method which looks like this
``` javascript
   createUser: function(email, password) {
      var deferred = this._q.defer();

      this._ref.createUser({
        email: email,
        password: password
      }, function(error) {
        if (error !== null) {
          deferred.reject(error);
        } else {
          deferred.resolve();
        }
      });

      return deferred.promise;
    }
```

**Comment by jwngr** [comment]
Hey @ivanvoznyakovsky - I'm sorry to hear you are running into issues. The documentation is actually correct as this format changed with the AngularFire 0.9.1 release yesterday. [Here](https://github.com/firebase/angularfire/blob/b7e76c2a1ccbc088a429fc64f09e3e89737e4f8c/src/FirebaseAuth.js#L311-L320) is what the code looks like in current `master`. We allow both formats, but the single credentials argument is the recommended version. Passing in individual arguments is deprecated, as noted in the [AngularFire changelog](https://www.firebase.com/docs/web/libraries/angular/changelog.html).

So how do you fix this? Simply upgrade to the latest version of AngularFire (which is currently 0.9.1).

**Comment by ivanvoznyakovsky** [comment]
thnx. update to latest version. all is ok now )))
