### ISSUE TITLE
removeUser requiring user's password

### ISSUE THREAD

**Issue by tobysteward** [firebase/angularfire#530]
Hey guys,

What would you recommend to do when an admin wishes to remove a user from Firebase Auth via an Angular application? 

The method removeUser requires the user's password (which the administrator will not have) and resetting the password to get a token to use in place of a password (automatically triggering a reset password email).

Thanks!

**Comment by jwngr** [comment]
Hey @tobysteward, even our core Firebase client unfortunately does not provide a programmatic admin API to remove a user without their password. Although this is definitely something we have discussed and plan on providing in the future.

As a short term workaround, you can go to the **Login & Auth** tab of your Firebase's dashboard, you can manually remove users via the "Delete" buttons next to each user.

**Comment by rdesimone** [comment]
Yes, IMO this is needed. Any news about it? Could you reopen? Thanks!

**Comment by jwngr** [comment]
Promise me that it is on our todo list. No news on when it will land though.

Regarding reopening the issue: This is not an AngularFire issue per se. AngularFire just provides what our core Firebase SDK provides. So this is not the right place to track this feature request. We have it in our internal feature list and it's going to happen.

**Comment by rdesimone** [comment]
@jwngr Thanks

**Comment by douwevdijk** [comment]
+1

**Comment by jbouhier** [comment]
+1

**Comment by brunomptorres** [comment]
@jwngr Any predictions for when this will be working?

**Comment by jwngr** [comment]
We don't provide estimations on when features like this will land. It is on our backlog and we appreciate the feedback. +1's / me too's are not necessary as we get enough of them on a daily basis in our other support channels and we already know that we want to provide this type of feature.

**Comment by katowulf** [comment]
Also, as mentioned before, this is a limitation of the core API and not something that could be addressed in AngularFire until the feature appeared in the core SDK (nor would it need to be address here if it was added to the SDK).

**Comment by d-david-k** [comment]
+1 / me too, or we're gonna have to save passwords too. :D
