### ISSUE TITLE
API Example $FirebaseArray.$extendFactory: this._list returns "undefined"

### ISSUE THREAD

**Issue by benjaminsuch** [firebase/angularfire#533]
Hello,

am I wrong or is there a mistake in the Example code at: https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-factories-firebasearrayextendfactory

I used the example code and its working fine, except, that `console.log(this._list)` returns `undefined` (I put `console.log(this._list)` right after `var total = 0`). When I use `this` instead of `this._list` I'm not able to find `_list`

**Comment by jwngr** [comment]
Thanks for reporting. We will get this fixed shortly.
