### ISSUE TITLE
Throw an error if using array-like data

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#534]
We do not support array-like data (numeric, sequential ids can't be used for concurrent edits) so throw an error if someone tries to load them into a synchronized array in AngularFire.

**Comment by jwngr** [comment]
Is this any different from #509 which you also opened? If so, let's just close this guy. I think we can do something better than just throwing an error here. Or at least we should try to.

**Comment by katowulf** [comment]
I think this is the correct answer. Let's close the other.

**Comment by jwngr** [comment]
Right before firing the initial `$loaded()` event, we will check if `angular.isArray(snapshot.val())`, and if so, throw a synchronous error explaining that AngularFire does not support arrays in this way.
