### ISSUE TITLE
Does the $remove evaluate async?

### ISSUE THREAD

**Issue by gigablox** [firebase/angularfire#536]
I have a promise chain:

    e.validate(v).then(function(){
      
      //validate Sucess!
      return !e.get()?refManager.addPvt($firebase(ref.child('users').child(currentUser.$id)).$asObject()).$remove():false;
    },function(error){
      
      //validate Failure!
      e.add(error);
    }).then(function(){
      
      //$remove Success!
      return !e.get()?refManager.addPvt($firebase(ref.child('usersMap').child('password').child(currentAuth.uid)).$asObject()).$remove():false;
    }, function(error){
      
      //$remove Failure!
      e.add(error);
    }).then(function(){

      //$remove Success!
      refManager.destroyPvt();
      return !e.get()?auth.$removeUser({
        email: email.email,
        password: password.password
      }):false;
    }, function(error){
      ...

This method removes a user from the users collection entirely.

`refManager.addPvt()` service method collects refs dependent on an authentication state and returns the ref passed to it for method chaining.

`refManager.destroyPvt()` service method invokes `$destroy` on the collected methods.

You're probably wondering why I'm using this `refManager` service at all as the docs state:
*"Removes the entire object locally and from Firebase."* 

Consider these two reproducible scenarios when the next link in the chain is to delete the user through `auth.$removeUser()` which according to your docs invokes `$unauth()` silently:

1. **Without** synchronously removing the local references first through this helper service before `auth.$removeUser` I'm getting `permission_denied`.

2. **With** synchronously removing the local references first through this helper service before `auth.$removeUser` I'm getting `obj is null`.

This leads me to believe this invocation of `$remove()` is running async.

Using `$save` on the parent after setting the `<$userid>` to `null` isn't an option for obvious security reasons.

What am I doing wrong here?

**Comment by gigablox** [comment]
After playing around with this a bit more I've realized `ref.$asObject().$remove()` does not work at all.

I can use `ref.$remove()` where my only real consequence is seeing the `permission_denied` error in the console... but as you can see I really do not like errors in my log haha.

Since the `$save()` method is not a viable option - I have no other means of using `$destroy` against the local object to avoid these error messages.

**Comment by jwngr** [comment]
I just released [AngularFire 0.9.2](https://github.com/firebase/angularfire/releases/tag/v0.9.2) with a fix for the `$FirebaseObject.$remove()` bug. That should fix your issue. If not, feel free to reopen this issue and provide a minimum repro (JSFiddle, CodePen, etc.) so that we can debug it. Ideally, you'd leave out unnecessary pieces like your `refManager` if you can. Thanks!
