### ISSUE TITLE
0.9.2 `auth.$waitForAuth()` throws `permission_denied` for OAuth2 providers

### ISSUE THREAD

**Issue by gigablox** [firebase/angularfire#538]
If I am a user with an existing authenticated session returning to a website we can use `auth.$waitForAuth()` to `resolve` the authentication.

However resolving authentication with an OAuth2 provider - *tested Facebook, Google+ and Github*...

I'm getting `permission_denied` errors.

Password grant type works as intended with no `permission_denied` errors.

**Comment by jwngr** [comment]
Can you please explain why you closed this? I assume it is because you realized the `PERMISSION_DENIED` error came from a different part of your code. But just in case someone ends up here in the future, please explain what you discovered. Thanks!

**Comment by gigablox** [comment]
Yes - this functionality is working properly and `permission_denied` was coming from an unrelated issue.
