### ISSUE TITLE
0.9.2 `auth.$requireAuth()` doesn't `$emit` a `$stateChangeError` on page load.

### ISSUE THREAD

**Issue by gigablox** [firebase/angularfire#539]
**On initial page load** - using `auth.$requireAuth()` as part of a `$state` resolve object - `auth.$requireAuth()` does not `$emit` a `$stateChangeError`.

This causes the application to die - aka "white screen".

I can use a work around like:

    resolve:{
      currentAuth:function(auth, $state){
        return auth.$requireAuth().then(function(user){
          return user;
        }, function(error){
          $state.go('app.home');
        });
      }
    }

But then lose the ability to act on modules paired with the parent controller like an "error" toast.

**After page load** - accessing a *protected state* from an *unprotected state* correctly fires the `$stateChangeError` in the parent controller.

**Comment by jwngr** [comment]
Do you have a repro for this? AngularFire itself doesn't worry about calling `$emit()` itself so I don't think it is the problem here. The `$requireAuth()` method is simply a promise which is fulfilled with the user if a user exists or is rejected otherwise. The way I understand things, rejecting the promise *should* `$emit()` a `$stateChangeError` without us having to do anything else. If it's not, it's possible something else is going on in your code.

**Comment by gigablox** [comment]
Sure, here's Plunker. Uncomment line 6: http://plnkr.co/edit/W22sFEm7Eco51OhHTkrp to simulate a page load. In your console you will see a bunch of Angular errors.

The parent controller is holding the `$on` event. 

There is also a link in the parent template to simulate an after page load scenario. In the child feel free to play around with the resolve logic intercepting the `$requireAuth()` failure as shown above.

**Comment by jwngr** [comment]
After debugging this for way too long, I have uncovered your problem. You are using Angular 1.2.x, however the `$stateChangeError` event apparently does not work in that version (?). In `index.html`, if you simple replace this line:

`<script src="angular.js"></script>`

with this:

`<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.11/angular.min.js"></script>`

everything magically works! I would suggest upgrading to Angular 1.3.x.

**Comment by gigablox** [comment]
Oh hey sorry about that. I was actually using `1.3.0` in my local source - must have copied the wrong CDN source to that plunkr. Must have been a bug in the 1.3.x series as well... anyways will bump version to latest 1.3.11. Thank you.
