### ISSUE TITLE
Empty arrays are not stored to the backend

### ISSUE THREAD

**Issue by ProLoser** [firebase/angularfire#54]
After the AngularJS meetup I talked to the core team about how my empty arrays were not being saved to the server.

The issue with this is that, lets say we have a shopping cart app.
1. I create a new list, which contains a 'name' property and an 'items' array property
2. Someone closes the window without creating any items
3. Someone reopens the page, the list is restored, but now I have to check if the 'items' property exists before I start pushing to it.

It's fairly negligible check theoretically, but it would be nice if this would be handled a bit better.

**Comment by llllllllllllIIIIlll** [comment]
This is like saying we don't need the number 0 which represents nothing

Silly mistake from Googles side

**Comment by wh1t3h47** [comment]
Please note that you can always store falsy values for that purpose, as Firebase doesn't care about types: Instead of `[]`, `{}` or `NULL`, store either `false` or `0`.
