### ISSUE TITLE
0.9.2 `$remove()` on orderBy* operations throws error.

### ISSUE THREAD

**Issue by gigablox** [firebase/angularfire#543]
I'm trying to query a range of data and remove it.

```js
var q = ref.child('users').child(targetUserId).child('pub').child('chat');
/**
  * For debugging I just set $priority via $add with simple integer values...
  * In this example (I think) I'm saying delete all of the records <= 2.
  */
$firebase(q.orderByPriority().endAt(2)).$asObject().$remove();
```

Getting:
`Firebase.DataSnapshot.forEach failed: Was called with 2 arguments. Expects no more than 1.`

I've played around with the various combinations... `orderByChild()` using a key value, `orderByPriority()`, using different queries with `startAt()` and `endAt()`... And have tried building the query different ways. 

Am I doing something wrong?

**Comment by gigablox** [comment]
Any updates on this?

**Comment by jwngr** [comment]
Sorry for not responding earlier. Kato and I have been fighting fires elsewhere.

If you consider what you are doing, you are attempting to turn a Firebase query (which can contain multiple Firebase nodes) into a single JavaScript object by using `$asObject()` on that query. This doesn't really make logical sense and we honestly should throw an error when users try to do this. What you really want probably this:

```
q.orderByPriority().endAt(2).on('child_added', function(snapshot) {
  snapshot.ref().remove();
});
```

If these changes are being reflected in your view, you could thrown in a `$timeout()`:

```
q.orderByPriority().endAt(2).on('child_added', function(snapshot) {
  $timeout(function() {
    snapshot.ref().remove();
  });
});
```

**Comment by gigablox** [comment]
Ahhh... I think I see now. So `child_added` gives you a `ref` handle for every node in the callback - where `$asObject.$loaded` is the aggregation of all those objects. 

I could still perform a `$remove` on each child in the `$asObject.$loaded` callback using a loop right? Is that essentially achieving the same thing as the `child_added` callback?

**Comment by jwngr** [comment]
Your could use `$asObject().$remove()`, but then you are wasting time creating a synchronized object for no real value. You are just doing a delete and don't need to actually sync the object. This is a case where you don't want to create a synchronized array or object, so you should instead just use the regular Firebase SDK.

**Comment by gigablox** [comment]
Got ya.
