### ISSUE TITLE
Callbacks not being removed?

### ISSUE THREAD

**Issue by henry74** [firebase/angularfire#548]
I'm using $firebaseAuth and $onAuth to setup a callback when a user successfully logs in.  My issue is I cannot seemed to successfully remove the callbacks as every logoff/login results increasing # of the same callback being called.

```
var ref = new Firebase("https://****.firebaseio.com/");
var auth = $firebaseAuth(ref);

this.onAuth = function(loginCallback) {
    auth.$onAuth(function(authData) {
      if (authData) {
        event.debug("User has been logged in with User ID: " + authData.uid + ", Provider: " + authData.provider);
        loginCallback(authData);
      }
    });
  }
this.logoff = function(callBack) {
    auth.$unauth();
    ref.offAuth(callBack);
  }
```

I'm passing in the same callback used for onAuth but the callback does not seem to be removed.  Is there an AngularFire specific command I need to use to remove onAuth callbacks?

**Comment by jwngr** [comment]
Hey there, I've got good news for you: AngularFire provides a much simpler way to solve your problem! The only problem is that it is currently undocumented. `$firebaseAuth.$onAuth()` actually returns a callback function which can be used to remove the callback you attach to `$onAuth()`. So your code would look like this:

```
var ref = new Firebase("https://****.firebaseio.com/");
var auth = $firebaseAuth(ref);
var offAuth;

this.onAuth = function(loginCallback) {
  offAuth = auth.$onAuth(function() {
    // ...
  });
}

this.logoff = function() {
  auth.$unauth();
  offAuth();
}
```

I'll make sure to update our documentation to include this information. Thanks for bringing this to our attention!
