### ISSUE TITLE
Using angular validation with a three-way binding

### ISSUE THREAD

**Issue by datasage** [firebase/angularfire#551]
I've been struggling with an issue and haven't found documentation on the best way to handle it.

Lets say I have an object bound to the scope using $bindTo. Properties within this object are bound to form fields with ng-model.

Angular validators will return undefined if a field is invalid (just use ng-required for a simple example). Trying to update a field with an undefined value causes firebase to throw an error.

My workaround at the moment is to override $parsers with custom directivies to return a value other than undefined (null or empty string). But this more or less precludes using any of the predefined validators. 

Is there a better way to handle this issue?

**Comment by katowulf** [comment]
It would be much simpler to just call $save() after successful validation. $bindTo is a nice convenience, but hardly a necessity and more burden than it's worth here.
