### ISSUE TITLE
Create migration plan from AngularFire 0.8.x to 1.0.0

### ISSUE THREAD

**Issue by jwngr** [firebase/angularfire#555]
Still undecided as to where to put it, but we should provide the following:
  * full list of changes
  * code samples for each breaking change
  * FAQ / solutions to common problems users may run into

**Comment by katowulf** [comment]
Still think [releases](https://github.com/firebase/angularfire/releases) is the right place for this. It would allow migration from older versions to newer ones by simply reading up the release list for "MIGRATION NOTES" or something similar.

**Comment by jamestalmage** [comment]
Wow,
First time I've seen that. I agree that it's the right place for migration notes, especially if changes are easily summed up in a few bullet points. The readme should link to that page.

**Comment by jwngr** [comment]
The fact that you've never seen it is the reason why I think we need to put it in a more prominent place... I think we at the very least need to link to it from our website.

**Comment by jamestalmage** [comment]
On a related note - it would be nice to have access to versioned documentation, both for `AngularFire` and `Firebase` as a whole. Angular does a really nice job of this.

**Comment by katowulf** [comment]
That is a completely unrelated note. Never bring it up again. I mean, it's already in our website/docs tracker. Good idea.

**Comment by jwngr** [comment]
This is done and will be live when AngularFire 1.0.0 is released. We ended up placing this here: https://firebase.com/docs/web/libraries/angular/guide/migration-guides.html (note that this will 404 until the docs go live).
