### ISSUE TITLE
Documentation style makes "newEmail" look like "new Email"

### ISSUE THREAD

**Issue by eeue56** [firebase/angularfire#565]
See any example here - https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-users-and-authentication-changepasswordcredentials

Any time the word new is included, it is shown as a separate word. newEmail becomes new Email

**Comment by jwngr** [comment]
As of yesterday, this is fixed in `master` of our website. It will get deployed early next week. Thanks for reporting!
