### ISSUE TITLE
API Reference can't be found on Google

### ISSUE THREAD

**Issue by ExplodingCabbage** [firebase/angularfire#568]
It took me a really long time (I'd been fiddling with the library for hours) before I found the annotated source at https://www.firebase.com/docs/web/libraries/angular/api.html.

It doesn't seem to be indexed on Google. Searching for method names or snippets from the docs yields no results. See, for instance:

* https://www.google.co.uk/webhp?q=$authWithCustomToken#q=$authWithCustomToken&nfpr=1
* https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22this%20method%20returns%20a%20promise%20that%20will%20be%20fulfilled%20when%20the%20data%20has%20been%20removed%20from%20the%20server.%22
* https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22authenticates%20a%20firebase%20client%20using%20an%20authentication%20token%20or%20firebase%20secret%22
* https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%24getAuth+angularfire

The API reference should come up for all these searches, but does not. It is currently only discoverable via the GitHub repo's README or the link on https://www.firebase.com/docs/web/libraries/angular/index.html (which is itself confusing insofar as it's not obvious that the API reference on the page is different from the one in the sidebar).

Not sure what's causing Googling not to index the docs, but it would be useful to fix.

**Comment by katowulf** [comment]
Thanks for this. Great feedback. I'll move this into the internal tracker for our web site.

Cheers,
Kato
