### ISSUE TITLE
Update end-to-end tests to use a random push ID

### ISSUE THREAD

**Issue by jwngr** [firebase/angularfire#571]
If anyone, anywhere is running the test suite at the same point in time, the end-to-end tests will almost certainly fail because they are modifying the same Firebase nodes. This causes huge headaches in Travis. We should update the end-to-end tests to use a random push ID in order to have more resilient tests.

**Comment by jamestalmage** [comment]
Random? or just `gameBaseRef = baseRef.push()`.

and then maybe in the travis build script
```javascript
if(process.env.TRAVIS_BUILD_NUMBER % 100 === 0){
 baseRef.set(null); //erase all stored games
}
```

**Comment by jwngr** [comment]
Push IDs should work. I don't think we want this to live in Travis though. Each individual e2e test should use a different node to store data every time so we never have conflicts. I am about halfway through putting this together and I'll cc you on the PR so you can see what I'm thinking!

**Comment by jamestalmage** [comment]
no - I wasn't suggesting it live in travis
just that travis wipe out old data every 100 builds.

**Comment by jamestalmage** [comment]
actually - those tests create so little data, you probably could leave them around forever

**Comment by jwngr** [comment]
Oh oh oh. I see. That makes sense. I think keeping them around forever won't be an issue. That Firebase will naturally get deleted every so often anyway due to a broken test :smirk:
