### ISSUE TITLE
Bad script tag in AngularFire tutorial

### ISSUE THREAD

**Issue by jamestalmage** [firebase/angularfire#576]
See my reply on #362 

The script tag in the docs points to angular version `1.4.0`, but should point to either `1.4.0-beta.5`, or better yet `1.3.4`.

**Comment by jamestalmage** [comment]
[link](https://www.firebase.com/tutorial/#tutorial/angular/0) to tutorial

**Comment by jwngr** [comment]
The link now points to 1.3.14. Thanks for triaging that issue!

**Comment by jwngr** [comment]
Oh shoot, you were linking to a different place. I'll fix that as well and it'll get deployed tomorrow.
