### ISSUE TITLE
Link to migration guide in v1.0.0 release is broken

### ISSUE THREAD

**Issue by ExplodingCabbage** [firebase/angularfire#578]
<strike>This is another site bug; let me know if there's a more appropriate place to report issues like this one.</strike> *Edit: Actually, this is just an issue with your release description on GitHub.*

At https://github.com/firebase/angularfire/releases/tag/v1.0.0 you've written:

> * **We have a migration guide [here](https://firebase.com/docs/web/libraries/angular/guide/migration-guides.html).**

However, the linked page is a 404:

![screen shot 2015-03-06 at 11 11 08](https://cloud.githubusercontent.com/assets/2358339/6524456/98161456-c3f1-11e4-92de-85ea0719fcf9.png)

**Comment by ExplodingCabbage** [comment]
Aha, https://www.firebase.com/docs/web/libraries/angular/guide/migration-plans.html#section-0-9-x-to-1-0-0 seems to be the correct link target.

**Comment by katowulf** [comment]
Thanks for pointing this out. I've fixed the releases section and submitted a PR for the website link as well. We appreciate the feedback!
