### ISSUE TITLE
Bower still installing 0.9.1

### ISSUE THREAD

**Issue by OliverRC** [firebase/angularfire#580]
I am using the Yeoman generator for Angular-Firebase
Even when I for a bower update on angularfire it is still fetching 0.9.1

**Comment by jwngr** [comment]
This is the wrong repo to open this issue in. Doing `bower install angularfire` will download version 1.0.0, but our [`generator-angularfire` repo](https://github.com/firebase/generator-angularfire) has not yet been updated to AngularFire 1.0.0. I created [an issue](https://github.com/firebase/generator-angularfire/issues/47) to track this. Kato should be getting to this soon.
