### ISSUE TITLE
$unauth causing binding issues

### ISSUE THREAD

**Issue by douwevdijk** [firebase/angularfire#581]
Hi All,

Not sure if I am looking in the right direction, but I am experiencing a strange issue. It looks like calling $unauth() in a single page app and then logging in again with a different user is causing issues on my references and thus bindings. In other words, it looks the reference ( or binding ) remains even though the path has changed and updates are done on the new and previous index.

FYI, I am using Angularfire 0.9.1 and Firebase 2.0.5 

Many thanks.

**Comment by jwngr** [comment]
I'm not quite sure I understand what issue you are running into. Can you please be more specific? It would be best if you could put together a Plunker or CodePen with a repro of the issue. That way we can debug it ourselves. Thanks.

**Comment by douwevdijk** [comment]
Let me try to explain what is going on here:

First I create a Firebase reference like so:

var ref = new Firebase("https://xxx.com/accounts").child('user1234');
var account = $firebase(ref).$asObject();
account.$bindTo($scope, "account");

Then, when I change the reference:

var ref = new Firebase("https://xxx.com/accounts").child('user5678');
var account = $firebase(ref).$asObject();
account.$bindTo($scope, "account");

It will remain the previous assigned binding instead of overwriting it.

Probably I am doing something wrong. but I do not know how to detach or overwrite an existing binding. ( tried everything (destroy, off(), offline(), etc).

**Comment by katowulf** [comment]
Hello! From [the docs](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebaseobject-bindtoscope-varname):

    If $destroy() is emitted by scope (this happens when a controller is destroyed), 
    then this object is automatically unbound from scope. It can also be manually 
    unbound using the unbind() method, which is passed into the promise callback.

And the example from the same doc:

```
var obj = $firebaseObject(ref);
obj.$bindTo($scope, "data").then(function(unbind) {
  // unbind this later
  //unbind();
});
```

It is also unbound if you call $destroy on the synchronized object.
