### ISSUE TITLE
Some $firebaseArray properties don't exist when requiring firebase & angularfire

### ISSUE THREAD

**Issue by chinedufn** [firebase/angularfire#584]
I'm trying to use the $keyAt and $indexFor functions of a $firebaseArray, but it looks like the properties don't exist. Firebase and angularfire are being required using browserify.

```
var firebase = require('firebase');
require('angularfire');

// later inside of a controller ...
var list = $firebaseArray( new firebase(FIREBASE_URL) );

// undefined undefined
console.log( list.$keyAt, list.$indexFor );

// is defined
console.log( list.$ref )
```

**Comment by katowulf** [comment]
[It exists in the code](https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L188) and [has tests](https://github.com/firebase/angularfire/blob/master/tests/unit/FirebaseArray.spec.js#L336). It doesn't look like the unit tests or e2e utilize browserify. [We'll add that](https://github.com/firebase/angularfire/issues/585). But for now, we'll need some help understanding the specific conditions you've encountered here; it seems unlikely that browserify is somehow breaking the prototype methods.

Version info? Stack? Are we working in node.js by any chance? ES6? Any other notable details we can use to repro?

**Comment by chinedufn** [comment]
##### Versions

angularfire 1.0.0
firebase 2.2.2
angular 1.3.14

##### Javascript

Not using ES6

Fairly basic browserify config :

```
gulp.task('browserify', function() {

  gulp.src(['app/app.js'])
  .pipe(browserify({
    insertGlobals: true,
    debug: true
  }))

  .pipe(concat('bundle.js'))

  .pipe(gulp.dest('dist/js/'))
  .pipe(livereload());
});
```

I see that index.js uses require('./dist/angularfire');

Are $keyAt and $indexFor new as of 1.0.0? If so, when we npm install angularfire are we getting an up to date /dist/angularfire?

**Comment by katowulf** [comment]
Thanks for the details. Re: dist/ folder -- Would be best to check the versions numbers in the files to be sure.

**Comment by chinedufn** [comment]
Thanks for the help!

Made a quick new test project and got it working fine.. 

Turns out there is absolutely no issue here.

The problem was that my controller looked like this ->

```
controller('CTRL', ['$scope', '$firebaseObject', '$firebaseArray', 'FBURL', function($scope, $firebaseArray, $firebaseObject, FBURL) {
 // code
}])
```

Notice the ordering of $firebaseObject and $firebaseArray :(

**Comment by katowulf** [comment]
Cheers, glad you resolved it. That was mysterious.

**Comment by jamestalmage** [comment]
@chinedufn, you should consider using [ng-annotate](https://github.com/olov/ng-annotate) in your build process and **not** using the array syntax (`ng-annotate` will handle that for you). This allows you to add/delete/reorder your function parameters without worrying about keeping the array in sync.

Just make sure to enable [ng-strict-di](https://github.com/olov/ng-annotate#highly-recommended-enable-ng-strict-di-in-your-minified-builds) as recommended. That will save you lots of debugging if `ng-annotate` misses something.

**Comment by jamestalmage** [comment]
here is the [browserify transform](https://www.npmjs.com/package/browserify-ngannotate) for `ng-annotate`.

**Comment by chinedufn** [comment]
@jamestalmage will consider it, many thanks
