### ISSUE TITLE
use angular.merge instead of utils.deepCopy

### ISSUE THREAD

**Issue by jamestalmage** [firebase/angularfire#586]
current: [utils.deepCopy](https://github.com/firebase/angularfire/blob/master/src/utils.js#L283)

recommended replacement: [angular.merge](https://docs.angularjs.org/api/ng/function/angular.merge) ([src](https://github.com/angular/angular.js/blob/master/src/Angular.js#L373)) ([meat of the implementation](https://github.com/angular/angular.js/blob/master/src/Angular.js#L326)).

**Comment by katowulf** [comment]
That function appears to be new in 1.4--I don't see an equivalent in 1.3?

**Comment by jamestalmage** [comment]
ahh, That explains it.
perhaps do feature detection with a polyfill then? Or at least compare deepCopy to merge (they differ in some significant ways) and see if they are catching some corner cases we are not?

**Comment by katowulf** [comment]
Gave this [30 mins today](https://github.com/firebase/angularfire/tree/kato-merge) and couldn't get in running--test units fail with awkward errors and the data in $bindTo objects is not as expected. Perhaps will try again when 1.4 leaves beta. Closing for now as won't fix. Feel free to send a PR if you feel this is important.

**Comment by luckylooke** [comment]
polyfill for angular<1.4.0
```javascript
    if (!angular.merge) {
      angular.merge = (function mergePollyfill() {
        function setHashKey(obj, h) {
          if (h) {
            obj.$$hashKey = h;
          } else {
            delete obj.$$hashKey;
          }
        }

        function baseExtend(dst, objs, deep) {
          var h = dst.$$hashKey;

          for (var i = 0, ii = objs.length; i < ii; ++i) {
            var obj = objs[i];
            if (!angular.isObject(obj) && !angular.isFunction(obj)) continue;
            var keys = Object.keys(obj);
            for (var j = 0, jj = keys.length; j < jj; j++) {
              var key = keys[j];
              var src = obj[key];

              if (deep && angular.isObject(src)) {
                if (isDate(src)) {
                  dst[key] = new Date(src.valueOf());
                } else {
                  if (!angular.isObject(dst[key])) dst[key] = angular.isArray(src) ? [] : {};
                  baseExtend(dst[key], [src], true);
                }
              } else {
                dst[key] = src;
              }
            }
          }

          setHashKey(dst, h);
          return dst;
        }

        return function merge(dst) {
          return baseExtend(dst, [].slice.call(arguments, 1), true);
        }
      })();
    }
```
