### ISSUE TITLE
$loaded promise for a $firebaseObject of a newly created child

### ISSUE THREAD

**Issue by birdcw** [firebase/angularfire#587]
I have a service giving me:
```javascript
return $firebaseObject(ref).$loaded();
```
And then in my controller: 
```javascript
service().then(function(data){
$scope.data = data;
});
```

Seems to work in all cases except for when ref is a child endpoint that doesn't exist yet i.e.:
```javascript
ref = refThatExists.child('thatDoesNot');
```

In that situation $scope.data.$save doesn't work for me after I've assigned new data to $scope.data.

Am I just using ref.child() incorrectly to set a new endpoint or is something not right with $loaded and new endpoints?

**Comment by katowulf** [comment]
We'll need a minimal repro to be any help here.

**Comment by jwngr** [comment]
Closing this issue due to no response and the fact that this seems to be working for me. I built a small example from the provided data [here](http://plnkr.co/edit/wQGYtY) but was not able to get it to repro. @birdcw - if you think you have a repro, please fork my Plunk and make one yourself.
