### ISSUE TITLE
$requireAuth doesn't immediately detect expired token

### ISSUE THREAD

**Issue by ereyes01** [firebase/angularfire#590]
Hi folks,

I'm running into a problem whose underlying root cause might be related to issue #514. I have several routes whose resolve methods use the $firebaseAuth object's $requireAuth promise to ensure you are logged in before giving you access to the page. On failure, the user is redirected to the login page. I am using email login (I believe it was formerly simplelogin) to authenticate users.

The problem happens when the browser remains open for a long time and $firebaseAuth's underlying JWT expires. When I navigate back to an authenticated route, $requireAuth's promise at first succeeds, allowing me access to the authenticated route. After a few moments, if I try another authenticated route, it successfully detects the expired token and redirects me to the login screen.

On the surface and without diving into your code, this sounds like a race condition in $firebaseAuth's underlying global state and expiring tokens. Will this problem go away when this issue is fixed? Also, what is a reasonable work-around for route authentication in the meantime? I would prefer some way to hasten de-authentication over $extending the $$error of each of my Firebase objects/arrays.

Thanks, Eddy

**Comment by katowulf** [comment]
Root cause here is that once a promise is resolved, it can't be unresolved. We could change the internals of these methods to check if auth has been resolved previously, and if so, use getAuth() to resolve/reject, creating a new promise on each request, rather than having one global promise used for all future calls.

**Comment by ereyes01** [comment]
That's a useful explanation! Based on what you said, I've coded up a workaround that fixes the problem for me. I've replaced the call to $requireAuth in my resolve with the following code:

```javascript
    resolve: {
        "currentAuth": ["Auth", "$q", function(Auth, $q) {
            var deferred = $q.defer();
            var auth = Auth.$getAuth();
            var now = new Date();

            if (auth && auth.expires > now.valueOf() / 1000) {
                deferred.resolve(auth);
            } else {
                deferred.reject("AUTH_REQUIRED");
            }

            return deferred.promise;
        }]
    }
```

Note how I still needed to compare the current time to the token's expiration. The $getAuth() method apparently doesn't immediately detect expiration, either, and returns an auth object.

Implementation detail: "Auth" is my own service that returns `$firebaseAuth(baseRef)`, where `baseRef` is a reference to my firebase.
