### ISSUE TITLE
Page freezes and cannot load

### ISSUE THREAD

**Issue by kornicameister** [firebase/angularfire#591]
Hi,

I am experiencing a very strange bug with AngularFire and/or Firebase itself. Since this repository is located under firebase I believe this might be a good place to start with.

Ok, let's get going. 
I've created a very simple factory which would allow me to create several instances of **angularFire** components without a need to constantly refer to the firebase url. Therefore I present my code snippets 

```javascript
angular
    .module('sg.data', ['firebase'])
    .constant('DATA_URL', 'my_cool_firebase_url');

angular
    .module('sg.data')
    .factory('sgDataFactory', [
        'DATA_URL',
        '$firebaseAuth',
        function (DATA_URL, $firebaseAuth) {
            var service = {};

            service.firebaseAuth = _.wrap(getFirebaseAuth.bind(service), refWrapper);

            return service;

            function getFirebaseAuth(ref) {
                debugger;
                return $firebaseAuth(ref)
            }

            function refWrapper(func) {
                return func(getFirebaseRef())
            }

            function getFirebaseRef() {
                return new Firebase(DATA_URL)
            }
        }]
);
```

Problem is that as long as I provide a valid URL and try to open my page locally either using [browserSync](http://www.browsersync.io/) or WebStorm builtin server my application fails to load completely. By failure I mean that it freezes on loading it. I am able to see my files loaded from under serve directory but I cannot see the content, and the tab itself starts to consume CPU like crazy causing entire tab inaccessible and forcing me to shut it down by force. There are no Angular specific issues in the console (I am able to see them as long as firebase url is set to empty string/undefined value) so I assume entire build process is valid and produces deployable code.

As for the environment and the background of the problem. While I was building an app on top of the RequireJS, everything was ok, where for the application built with a little **Gulp** help, well...I cannot verify if app is actually working.

If You'd like to take a look on my gulp tasks or any other stuff required to reproduce it, let me know.

**Comment by katowulf** [comment]
Hey Tomasz,

Since most of the code likely to be responsible isn't in your sample, it's hard to guess at the cause. The best way to help here would be to see a repro in jsfiddle, plunkr, etc. If you can't reproduce the problem there, then you've isolated the error to the build environment. If you do, then we should be able to spot the error pretty quickly.

Cheers,
Kato

**Comment by kornicameister** [comment]
Hey Kato,

It seems that the root cause wasn't in the AngularFire or even in the code related to the snippet above. I made a typo somewhere else inside while loop. By typo I mean extra exclamation mark (!). 
After I figure that out and changed the problematic line everything started to working. 

So I guess that's a lesson to be remembered for future. Always look starting from yourself. 

Sorry for causing troubles. 

Best regards,
Tomasz

**Comment by katowulf** [comment]
Cheers, Tomasz. One of the great parts about creating a minimal repro is they often uncover those sorts of errors. Thanks for reaching out and for using AngularFire!
