### ISSUE TITLE
Bug in API docs - decorating services

### ISSUE THREAD

**Issue by rcuddy** [firebase/angularfire#592]
https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-services-decorating-the-services
Changes suggested:
  * Should be `$$updated`, not `$$update`
  * for consistency with other examples it should be `app.config`, not `angular.config`, to reflect the need to apply config to the module, not the angular global name space

Also the $delegate is never returned so the snippet will result in undefined error when trying to use firebaseObject later

```javascript
app.config(function($provide) {
  $provide.decorator("$firebaseObject", function($delegate, $firebaseUtils) {
    var _super = $delegate.prototype.$$updated;

    // override any instance of $firebaseObject to look for a date field
    // and transforms it to a Date object.
    $delegate.prototype.$$updated = function(snap) {
      var changed = _super.call(this, snap);
      if( this.hasOwnProperty("date") ) {
        this._dateObj = new Date(this.date);
      }
      return changed;
    };

    // add a method that fetches the date object we just created
    $delegate.prototype.getDate = function() {
      return this._dateObj;
    };

    // variables starting with _ are ignored by AngularFire so we don't need
    // to worry about the toJSON method here

    return $delegate;
  });
});
```

**Comment by jwngr** [comment]
Awesome work, @rcuddy. We will get the docs updated with your suggestions. Thanks for helping us improve this stuff!

**Comment by jwngr** [comment]
Wow, just realized this never got fixed... I just sent Kato a PR to update our docs. This change should go out next time we deploy our website (which happens every day or two). Thanks again!
