### ISSUE TITLE
$keyAt behavior 

### ISSUE THREAD

**Issue by krokhale** [firebase/angularfire#594]
I noticed this weird behavior while building a simple chatroom. While listing out the room on the page using ng-repeat with:

    ng-click="enterRoom(roomsList.$keyAt($index))"

 I noticed that keys were mismatched, as in it was returning back keys of random records to the enterRoom function. Also note that in this case i was using one room "Lobby" that was already bootstrapped. So firebase looked something like this:

    rooms: {'Lobby': {}, 'fireBaseGeneratedId': {}, 'fireBaseGeneratedId': {} ....}

Lobby was the only one that was not a firebase generated id using push.

After i changed lobby to be a firebase generated id, it was all fine though and returned proper keys to the enterRoom function:

   rooms: {'fireBaseGeneratedId': {name: 'Lobby'}, 'fireBaseGeneratedId': {}, 'fireBaseGeneratedId': {} ....}

Not sure if it's a bug or am i missing something? Thanks.

**Comment by krokhale** [comment]
Some more info, this continued to happen with Fb generated keys as well. I am now down to pinpointing it to:

    ng-repeat="room in roomsList | orderBy: ['persistent', '-createdAt']"

If i remove the multiple orderBy clause:

    ng-repeat="room in roomsList | orderBy: 'persistent'"

It's all good. At least for now. Let me know if you can replicate the issue.

**Comment by katowulf** [comment]
When you use `orderBy`, you effectively create a new array and reorder the contents. You won't be able to use `$index` in this case. Presumably, however, you have the key already, as it's stored in `$id`. Yet another reason array indices are pretty useless with realtime data.

```
<div ng-repeat="room in rooms">
     <button ng-click="enterRoom(room.$id)" />
     <!--- OR, just pass in the room -->
     <button ng-click="enterRoom(room)" />
</div>
```

**Comment by krokhale** [comment]
Thanks, that din't occur to me that we have $priority and $id in the array. I agree arrays are a pain to deal with, the only reason i am using angular fire is to have to deal with arrays so that it's easier for orderBy and filters. I prefer the regular javascript API otherwise.

**Comment by krokhale** [comment]
Ah, this is awesome, works great. Thanks.
