### ISSUE TITLE
angular new router + three way data binding

### ISSUE THREAD

**Issue by rolandjitsu** [firebase/angularfire#597]
It seems like in the [new angular router](https://angular.github.io/router/) we cannot access the `$scope` object, thus we cannot use the  `$bindTo` method because it throws an error while trying to hook on the `$destroy` phase of the controller using `scope.$on`.

Any suggestions on how to achieve three way bindings now? Maybe hook to the controller's `activate` [method](https://angular.github.io/router/lifecycle#activate)?

**Comment by katowulf** [comment]
We don't support the new router yet. We'll investigate soon. Until then, please use supported versions.

Most likely, $bindTo will not be compatible if there is no $scope available, although I'm not really sure what role the router has in determining this or why it would be modifying dependency injection to prevent it.

**Comment by rolandjitsu** [comment]
@katowulf probably is because in 2.x they eliminated the concept of `$scope` in favour of zones. But I am unsure why they did it this way.

**Comment by jamestalmage** [comment]
@rolandjitsu are you trying to use the new router in in `angular 1.4` or `angular 2.0`. I haven't tried it yet, but I'm sure `angularFire` is completely broken in `angular 2.0`. Assuming you are using the new router in `angular 1.4`, then you absolutely have access to `$scope` in the new router (but you did NOT in the old router).

Take a look at the (wizard example)[https://github.com/angular/router/blob/master/examples/angular-1/wizard/app.js] and add an `injection` for $scope:
```
    controller('AppController', ['$router', '$scope', AppController]).
    factory('answers', answersFactory);

function AppController($router, $scope) {
  console.log($scope);
```

With the old router you needed to specify your routes in the `config` stage where you would not have access to `$scope` at all.

**Comment by rolandjitsu** [comment]
@jamestalmage I am using the new router with 1.4 of angular. The issue is when the component controller asks for the `$scope`. In that case, the controller cannot ask for `$scope`, at least this is what I experience.

**Comment by jamestalmage** [comment]
Ahh, I see. You are correct `$scope` is not available in the component constructor. You can get around it by specifying an `activate` method on your component:

```javascript
angular.module("myModule").
    controller('AppController', ['$router', AppController]).
    controller('EditMessageController', ['$routeParams', EditMessageController]);

function AppController($router, $scope) {
  console.log($scope);
  $router.config([
    { path: '/message/:messageId',  component: 'editMessage', as:'editor' }
  ]);
};

function EditMessageController($routeParams){
  this.messageId = $routeParams.messageId;
};

EditMessageController.prototype.activate = function($scope, $firebaseObject) {
  var ref = new Firebase("https://myApp.firebaseio.com/messages/" + this.messageId);
  this.sync = $firebaseObject(ref);  
  this.sync.$bindTo($scope, 'editor.message');
  // firebase object will now be bound to this.message
};

EditMessageController.prototype.deactivate = function() {
  this.sync.$destroy();
};
```

**Comment by rolandjitsu** [comment]
@jamestalmage that is exactly what I have suggested :) I think I have tried to use it that way, but for some reason I could not get `$scope` to work. I cannot remember for sure, I've tried it two weeks ago. If you try it and it works, please let me know :)

**Comment by jamestalmage** [comment]
No - your original post suggested `deactivate` which will not work. You just edited your original post to say `activate`.

You don't just need `$scope.$on('$destroy', ...)`, you also need `$scope.$watch()`. Basically, you still need `$scope`, and you can't wait until the deactivate phase to get it.

The above code works just fine.

**Comment by rolandjitsu** [comment]
@jamestalmage I know, that was a mistake I only saw after you suggested it again :) It would make no sense to have it in the `deactivate`.

**Comment by katowulf** [comment]
I don't plan to support changes for the new router at this time. It seems the only benefit is being able to use $bindTo() and avoid calling $save(), and at the cost of complexity and bandwidth.
