### ISSUE TITLE
$waitForAuth does not seem to actually wait

### ISSUE THREAD

**Issue by adamstortz** [firebase/angularfire#598]
When executing the following code, the promise is resolved before authentication is complete and the $bindTo method fails with an permission denied message.  Is this expected behavior? 
```
Auth.$waitForAuth().then(function() {
   console.log('logged in');
   that.syncObject = $firebaseObject(firebaseUtil.ref('config/harvest'))
   that.syncObject.$bindTo($scope, 'data');
});
```

I am using 1.0.0: https://cdn.firebase.com/libs/angularfire/1.0.0/angularfire.min.js

**Comment by jwngr** [comment]
`$waitForAuth()` waits until the current authentication state is retrieved for the first time. It does not guarantee that the user will be logged in. The first authentication state may be the logged out state. So your `console.log('logged in')` message is not correct. Instead, your code should look something like this:

```
Auth.$waitForAuth().then(function(authData) {
  if (authData) {
    console.log('logged in');
     that.syncObject = $firebaseObject(firebaseUtil.ref('config/harvest'))
     that.syncObject.$bindTo($scope, 'data');
  } else {
    console.log('logged out');
    // do something else...
  }
});
```

Note that `$waitForAuth()` is designed for use in routers and not for non-router code. Are you using it in a router? If not, what is your use case? We can probably find an easier way for you to handle things.

**Comment by adamstortz** [comment]
Thank you for the clarification.  I am using it in the new router.  My app will not support unauthenticated guests, so I need the user to be logged in before they see anything.  I am struggling to see how I would accomplish this elegantly.  I am using AngularFire with Google Apps auth integration to manage my authentication with $authWithOAuthPopup.  I need to find a way to defer all routining until the promise from $authWithOAuthPopup has resolved.

**Comment by katowulf** [comment]
We haven't looked into the new router yet, but we do have a section in the docs on [working with routers](https://www.firebase.com/docs/web/libraries/angular/guide.html#section-routes). It's fairly straightforward and implemented in both [angularFire-seed](https://github.com/firebase/angularFire-seed) and [our yeoman generator](https://github.com/firebase/generator-angularfire/)

Essentially, in the old routers, you use the `resolve` method and return `$requireAuth()`. Monitor the equivalent to `$routeChangeError` and redirect to a login page if `"AUTH_REQUIRED"`.

That's about all the support we can offer for the new router for now.

**Comment by adamstortz** [comment]
Ok, I have read that and understood it.  Thanks for taking the time to respond.  I will keep an eye on the new router and angular fire I am sure this is something that will get resolved (sorry for the pun ;))

**Comment by jamestalmage** [comment]
@adamstortz 
Check out the documentation on [component lifecycles](https://angular.github.io/router/lifecycle) in the new router, specifically [`canActivate`](https://angular.github.io/router/lifecycle#can-activate). Also see the [`requireAuth`](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-users-and-authentication-requireauth) method in the AngularFire API docs. 

I believe something like this should work:

```
angular.module('app', ['ngNewRouter']) 
  .controller('MyController', ['$firebaseAuth', MyController]);

function MyController($firebaseAuth) {
  this.$firebaseAuth = $firebaseAuth;
}

MyController.prototype.canActivate = function() {
  return this.$firebaseAuth.requireAuth();
};
```

Note, the name `ngNewRouter` will soon be changed to [`ComponentRouter`](/soon to be called ComponentRouter https://github.com/angular/router/issues/159)
