### ISSUE TITLE
Incorrect event names in API doc for $firebaseArray.$watch

### ISSUE THREAD

**Issue by gjungb** [firebase/angularfire#599]
The API doc for ```$firebaseArray.$watch``` (https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L245) is incorrect.

Wrong: ```<code>{ type: 'added|updated|moved|removed', key: 'key_of_item_affected'}</code>```
Right: ```<code>{ event: 'child_added|child_updated|child_moved|child_removed', key: 'key_of_item_affected'}</code>```

**Comment by katowulf** [comment]
If you find yourself depending on those event names (i.e. listening to server events), it's likely that you've misunderstood the purpose of the AngularFire classes and there's probably a better way to accomplish your goals. I'm surprised to see, in fact, that we pass anything into the $watch callback. That should have been removed before the 1.0 release.

In general, using `$extend` to modify the `$$added`, `$$updated`, and `$$removed` would be more appropriate for manipulating data and intercepting server events.  Anything that can't be done with these should probably use a custom service and tap directly into the Firebase SDK.

**Comment by gjungb** [comment]
BTW: the ```$watch``` method is also documented here: https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-watchcb-context
