### ISSUE TITLE
3-way binding for $firebaseArray?

### ISSUE THREAD

**Issue by jyasskin** [firebase/angularfire#600]
If I have a Firebase object containing an array, I can either 3-way bind it with a `$firebaseObject` and use the array's key to remove elements, or I can 2-way bind it with a `$firebaseArray`, requiring an explicit `.$save()` call in each `<input>`'s `ng-change` event, but getting the ability to remove with just the item. Would it be possible to either add a `$firebaseArray.bindTo` method or make array elements of a `$firebaseObject` just work like `$firebaseArray`s?

**Comment by katowulf** [comment]
Not possible. Three-way binding is simply a convenience and not really suitable for anything other than simple key/value pairs. Calling $save is the correct approach here.
