### ISSUE TITLE
Is there a way to load filtered array and load new items based on same filter?

### ISSUE THREAD

**Issue by gayanpathirage** [firebase/angularfire#605]
Currently it loads everything from a firebase location.

**Comment by katowulf** [comment]
Not really sure what this means. A simple repro and details about the behavior you're seeing and what you'd like to see instead would be helpful. Cheers.

**Comment by gayanpathirage** [comment]
Default firebase supports basic querying facilities ( Ref https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries )

Can we get the same facility with AngularFire?

e.g. say a given URL has 100 entries and we want only to load 10 of them based on some criteria. 

NOTE: Currently we do this after additional filtering at client level, but that is a waist of data transmission.

**Comment by jwngr** [comment]
Yup, you can pass a query to `$firebaseArray()` or `$firebaseObject()`, like so:

```
var ref = new Firebase("https://<your-firebase>.firebaseio.com/items");
var query = ref.orderByChild("foo").limitToLast(100);
var items = $firebaseArray(query);
```
