### ISSUE TITLE
$loaded() does not resolve into $firebaseArray

### ISSUE THREAD

**Issue by BetterTrader** [firebase/angularfire#608]
Hello,
The documentation says that calling $loaded() on $firebaseArray returns a promise that resolves into the $firebaseArray itself:
https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-loaded
However, that is not the case. 
The promise never resolves into the $firebaseArray and always stays a promise.

**Comment by katowulf** [comment]
Try using the catch() block and checking the JavaScript console for errors. If the problem persists, provide an [mcve](http://stackoverflow.com/help/mcve) demonstrating the issue. Cheers.

**Comment by jwngr** [comment]
Yup, try something like this and see what gets printed to the console:

```
var list = $firebaseArray(ref);
list.$loaded().then(function(x) {
  console.log("Success");
}).catch(function(error) {
  console.error("Error:", error);
});
```

**Comment by BetterTrader** [comment]
Here's a codepen:
http://codepen.io/anon/pen/oXgpyg
According to the docs, $scope.list (which is a promise returned from $loaded()) should be resolved to be the list itself, and you can see it doesn't happen here.

**Comment by katowulf** [comment]
You have set $scope.list to the promise reference, not the results of the promise. Also, there is no need to use $loaded or a promise here. AngularFire will work out the details and notify Angular when the data is available. You want this:

```
$scope.list = $firebaseArray(ref);
```

Also, you need to read the guide in detail and save yourself some pain and thrashing with these basic fundamentals:  https://www.firebase.com/docs/web/libraries/angular/guide.html

Cheers,
Kato

**Comment by BetterTrader** [comment]
I did read it.
I know that I don't need to use $loaded() in this case, it was just a demonstration.
Let me quote from the API:
"The promise resolves to the $firebaseArray itself"
Doesn't it mean that the object returned from $loaded() will become the $firebaseArray itself, which means the code above should've worked?

**Comment by katowulf** [comment]
No. $loaded() returns a promise. The value passed into the then() or done() method will be the synced array.
