### ISSUE TITLE
bindTo causes typing problems

### ISSUE THREAD

**Issue by ggowan** [firebase/angularfire#612]
When editing a text input field that is being synced via $bindTo(), I find that characters are ocassionally dropped. If I try to insert text into the middle of the field, the cursor sometimes skips to the end of the text. This is easiest to reproduce by jamming all fingers on multiple keys simultaneously over and over again, but it can happen while simply typing quickly.

I was using AngularFire 1.0.0, AngularJS 1.3.14, and Firebase 2.2.2 in Chrome on a linux laptop connected via WiFi to a cable modem. I had multiple windows open showing the same data form and I think that is probably required to reproduce the problem, but I'm not 100% certain of that.

**Comment by ggowan** [comment]
I forgot to mention the workaround which is to not use bindTo and call $save() from an ng-change attribute on the input control. See also this stackoverflow question:
http://stackoverflow.com/questions/25331760/when-using-angularfire-the-cursor-jumps-to-end-of-field-while-typing

**Comment by jamestalmage** [comment]
@katowulf @jwngr 
Confirmed in 1.0.0, but already fixed in @b7be0b8

confirming [plunk](http://plnkr.co/edit/wK7TpDktHSDaOEtrkOoM)

**Comment by jamestalmage** [comment]
The fix should be published in a release ASAP, IMO.

**Comment by jwngr** [comment]
We plan on doing a release next Monday. Was going to do one today, but we didn't get around to it. Although @katowulf was able to clear out almost all of the issues today.

@ggowan - Thanks for reporting! Can you try out the `master` branch locally and see if it resolves your problem?

**Comment by katowulf** [comment]
I've confirmed that @jamestalmage is right and the reported issue has been fixed. I can still create a related issue by typing in characters super fast for some length longer than 20 and then stopping (some of the text I've typed in is deleted as the server and client are not agreeing on the value).

**Comment by ggowan** [comment]
I'm a bit late to the party, but wanted to confirm that this issue is indeed fixed.
