### ISSUE TITLE
$firebaseArray and v1.1.0

### ISSUE THREAD

**Issue by albertosantini** [firebase/angularfire#617]
I have the following data structure:
```
subscribers: { 
    0: {
        id: 18, 
        name: "foo"
    }, 
   1: {
        id: 19, 
        name: "bar"
    } 
}
``` 

I have been using the following code:
```
subscribersSync = $firebaseArray(ref); 
subscribersSync.$loaded().then(function (subscribers) {
    // subscribers has zero length
    ...
```

With 1.0.0 it is ok, `subscribers` has length equals to two.
With 1.1.0 `subscribers` has zero length.

Any hint?

**Comment by jwngr** [comment]
Thanks for reporting this bug! @katowulf just made a fix with PR #618. We will get a `1.1.1` release with this fix out shortly.

**Comment by tobysteward** [comment]
@jwngr Any idea how long we're looking at for release?

**Comment by jwngr** [comment]
@tobysteward - I just released 1.1.1 ([see tweet](https://twitter.com/FirebaseRelease/status/595610210443526145)). Just needed to wake up first! Let us know if you still run into any issues!

**Comment by tobysteward** [comment]
@jwngr excellent, everything seems fine now! Thanks for getting the update out so quickly :)

**Comment by albertosantini** [comment]
Here it works nice. :)
Thanks for the super fast fix.
