### ISSUE TITLE
Path value getting cleared during protractor test

### ISSUE THREAD

**Issue by mperrenoud** [firebase/angularfire#620]
Let me preface this by saying I believe this is happening while running as well but it's not visible because of the Mock controller that's running. I believe it's rehydrating the path before it matters.

During a test we execute a set like this:

    ref.set(data, function (err) {
          if (err) {
            def.reject(err)
          }
          else def.fulfill();
        });
    return def.promise;

And that adds the path to Firebase as expected. However, before we can even get to returning the promise, the value for that path has been wiped clean. We found that when commenting out the default binding it persists:

    $ref.$bindTo($rootScope, '$state.' + name).then(function () {
      // merge in the default values so that any updates are propagated to all connected user
      $rootScope.$state[name] = angular.extend({},
        defaultStateValues[name],
        $rootScope.$state[name]);
    });

Has anybody experienced this before? What might be the best way to track down the setter that is wiping the value at that path?

**Comment by kclay** [comment]
One more note about this when we don't comment out `$ref.bindTo` and then call `ref.set` in our protractor test the callback isn't invoked. At first we thought for some reason the promise for `$bindTo` was being called multiple times but this doesn't seem to be the case.

**Comment by katowulf** [comment]
Please provide a minimal repro demonstrating the issue. Cheers.
