### ISSUE TITLE
Repeated input fields inside lists lose focus

### ISSUE THREAD

**Issue by ggowan** [firebase/angularfire#623]
This is similar to issue #127 filed by sniras.

I modified the plunker from that issue slightly to demonstrate the issue. 
http://plnkr.co/edit/GZL0SDELZO6yokIYYNA8?p=preview
Try editing grandchild 1 in the top section. It loses focus after you type one character.
Note that the inputs have ng-changed="model.$save()" on them. If you remove that attribute, the problem goes away, probably because the changes are no longer being saved.

Is there some other way this is supposed to be handled?

This occurs with Angular fire 1.1.1, 1.1.0 and 1.0.0. I'm not sure about older versions.

**Comment by ggowan** [comment]
Actually this occurs even with the child, you don't need nesting to repro it.

**Comment by ggowan** [comment]
Here's a different plunker demonstrating that this problem only occurs for repeated input fields on lists. It does not occur if the repeated input field is on object properties.

http://plnkr.co/edit/hNE3JIkMcidtHdgbAgPt?p=preview

**Comment by katowulf** [comment]
I believe the answer here is to use identified by in the ng-repeats. I'll have a look later. The core problem is that the lists are being re-rendered each time a value changes. Nested lists in lists in lists are always complex and troublesome, even without Firebase in the picture.

**Comment by jamestalmage** [comment]
@ggowan I can not reproduce using your plunker (OSX Chrome). Can you specify your environment (browser & OS)? If chrome, try incognito mode so we know some plugin is not the problem.

**Comment by ggowan** [comment]
I am using Chrome on Linux, Version 43.0.2357.65 beta (64-bit). I haven't tried OSX.

Make sure you used the first plunker in the opening comment, not the one in my third comment. In other words, this one: http://plnkr.co/edit/GZL0SDELZO6yokIYYNA8?p=preview

Confirmed it occurs in incognito mode as well. It happens all the time, not on and off.

**Comment by ggowan** [comment]
Kato is correct, this is fixed by adding " track by $index" at the end of each ng-repeat expression.
http://plnkr.co/edit/X2HBheoTkENcpGT4eRzD?p=preview

Shall we close this issue then?

**Comment by jamestalmage** [comment]
I confirmed it in chrome for Android. That said, `tracky by` is the correct way to do this (same thing can happen without angularfire).

I say close.
