### ISSUE TITLE
$getRecord() not working in angularfire 1.1.1

### ISSUE THREAD

**Issue by Zjaaspoer** [firebase/angularfire#627]
$getRecord() returns null even when passing a valid id.

I'm using:
angularfire 1.1.1
firebase 2.2.7
angular 1.4.0

When I downgrade angularfire to 1.0.0 the function works again, when downgrading to 1.1.0 the problem persisted.

I'm aware of ticket https://github.com/firebase/angularfire/issues/622, which also mentions $getRecord not working in 1.1.1, but when downgrading my angular version to 1.3.15 the problem persists.

**Comment by katowulf** [comment]
Thanks for sending this in! Could you create a repro we could run locally to see the issue?

**Comment by Zjaaspoer** [comment]
No problem, is a JSBin / Codepen? also ok?

**Comment by jamestalmage** [comment]
Yes, anything that makes it easy for us to reproduce.

**Comment by katowulf** [comment]
Closing this for now. Please reopen if you can provide a repro.
