### ISSUE TITLE
using extend on $firebaseArray issue

### ISSUE THREAD

**Issue by andersrehn** [firebase/angularfire#638]
I've been looking at the documentation for Synchronized Arrays https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-services and https://www.firebase.com/docs/web/libraries/angular/guide/extending-services.html#section-firebasearray

I'm using Firebase version 2.2.7 and AngularFire version 1.1.2

Using the code below, I'm having trouble recognizing $$removed events.

    .factory("ExtendedCourseList", ["$firebaseArray",  function($firebaseArray) {
     // create a new service based on $firebaseArray
      var ExtendedCourseList= $firebaseArray.$extend({
      $$added: function(dataSnapshot, prevChild){
           var course = dataSnapshot.val();
           var course_key = dataSnapshot.key();
           console.log("new course");
           return course;
       },
       $$removed: function(snap){
           console.log("removed");
           return true;
       }
     });
     return function(listRef) {      
         return new ExtendedCourseList(listRef);
     } 
    }]) 
    
    .factory("CompanyRefObj", function(CompanyRef) {
      //CompanyRef is a constant containing the url string  
      var ref = new Firebase(CompanyRef);
     return ref;
    })
    
    .factory('CourseList', function (localstorage,$rootScope,ExtendedCourseList,CompanyRefObj) {
         var companyID = localstorage.get("company");   
        $rootScope.courseList = ExtendedCourseList(CompanyRefObj.child(companyID).child("courses")); 
    )

If I run this code, only the $$added events will be triggered. To simulate the remove events I use the web-interface at Firebase to display data, where I press the remove button and accept the data being deleted permanently.

Additionally, if I delete the $$removed function, the extended service still won't synchronize when a record is deleted.

If I modify my code to use the $firebaseArray instead of extending the service (as seen above) both add and remove events will be recognized.

    .factory('CourseList', function (localstorage,$rootScope,$firebaseArray,CompanyRefObj) {
        var companyID = localstorage.get("company");   
        $rootScope.courseList = $firebaseArray(CompanyRefObj.child(companyID).child("courses")); 
    )

Finally, are there any bad practices I've missed that can cause some of the extended functions to not work?

**Comment by katowulf** [comment]
You've overridden the $$added method, but have [not stored $id](https://github.com/firebase/angularfire/blob/master/src/FirebaseArray.js#L315) on the record. So when AngularFire attempts to remove the record, it can't find one with that key, so there is nothing to remove.

**Comment by andersrehn** [comment]
Appreciate your answer, it works flawless. I should investigate what other methods, such as $id that is lost when I override the $$ methods.

**Comment by puf** [comment]
Cross-post: http://stackoverflow.com/questions/31443066/angularfire-extending-the-service-issue
