### ISSUE TITLE
firebase auth is not working

### ISSUE THREAD

**Issue by omkar0001** [firebase/angularfire#640]
$scope.authObj.$authWithCustomToken("<CUSTOM_AUTH_TOKEN>").then(function(authData) {
  console.log("Logged in as:", authData.uid);
}).catch(function(error) {
  console.error("Authentication failed:", error);
});

Its not going into any of the callback functions.

**Comment by katowulf** [comment]
Can you provide version info?

**Comment by jwngr** [comment]
I just tested this [in a Plunker](http://plnkr.co/edit/gf1Pw1?p=preview) and it works as expected. Namely, the `catch()` is called with the `INVALID_TOKEN` error.

I used the following versions:

```
<!-- Angular -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js"></script>
    
<!-- Firebase -->
<script src="https://cdn.firebase.com/js/client/2.2.8/firebase.js"></script>
    
<!-- AngularFire -->
<script src="https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.js"></script>
```

Closing as "no repro." If you want to re-open, please provide a Plunker which reproduces the issue and let us know what versions of all libraries you are using.

**Comment by jwngr** [comment]
Note that it's possible that `console.error()` is not defined in whatever environment you are using. Maybe try replacing it with `alert()` or just `console.log()` and see if your issue persists.

**Comment by omkar0001** [comment]
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>

    <script src="https://cdn.firebase.com/js/client/2.2.4/firebase.js"></script>
    
    <script src="https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.min.js"></script>

**Comment by katowulf** [comment]
Just updated Jacob's plunk to match your version info and it's working as expected. Still can't repro this.
http://plnkr.co/edit/qRNXfo?p=preview

**Comment by omkar0001** [comment]
Hi, thanks a lot its working. But no of connections is going high when ever i m logging in, how can i reduce it. Does unauth reduces it.

**Comment by omkar0001** [comment]
Even though i closed my client window. Its sill showing 20 concurrent users. Can you please look into this. I made round 20 authentication requests which have failed.

**Comment by katowulf** [comment]
That's a totally different issue, unlikely to have anything to do with AngularFire, and a repro is *still necessary* to be any help.
