### ISSUE TITLE
Parent is not synced after last child is removed

### ISSUE THREAD

**Issue by ivarprudnikov** [firebase/angularfire#641]
jsfiddle - http://jsfiddle.net/ivarprudnikov/bL0qn6yu/

In jsfiddle, first add child and then try removing it.

## Description

If removing children by using `$scope.fireObjRef.$ref().child('_parent/children').child(childId).remove()` then after doing it to the last child, result (reference in scope `$scope.fireObjRef`) will not be synced and will still have the last child.

Could not reproduce in the case when parent object key **does not** start with underscore.

### Example data structure 

    // fireObjRef is not gonna be synced
    {
      fireObjRef: {
        _parent: {
          children: {
            -askdjhakjhdgajkhwdg: "abc01",
            -askdjhakjhdgajkhwdg: "abc01",
            -askdjhakjhdgajkhwdg: "abc01"
          }
        }
      }
    }

### JS fiddle source (in case its lost)

Libraries used:

- https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.1/angular.min.js
- https://cdn.firebase.com/libs/angularfire/1.1.2/angularfire.min.js
- https://cdn.firebase.com/js/client/2.2.7/firebase.js

#### HTML part

    <h3>Test sync removal of last child</h3>
    <div ng-controller="TestController">
        <p ng-show="!testObject._parent.children">No children</p>
        <ul ng-show="testObject._parent.children">
            <li ng-repeat="(id,val) in testObject._parent.children track by id">
                <span>{{ val }}</span>
                <button type="button" ng-click="remove(id)">&times;</button>
            </li>
        </ul>
        <form ng-submit="add()">
            <label for="testVal">Test value to append</label>
            <input name="testVal" id="testVal" ng-model="testVal">
            <button type="submit">Add</button>
        </form>
            <h4>JSON</h4>
            <pre>{{ testObject | json }}</pre>
    </div>

#### JS part

    angular.module('app', [])
        .controller('TestController', function ($scope, $firebaseObject){
            var ref = new Firebase("https://bugsfire.firebaseio.com/");
            $scope.testObject = $firebaseObject(ref);
            $scope.testVal = '';
            $scope.add = function(){
                if(angular.isString($scope.testVal)){
                    $scope.testObject.$ref().child('_parent/children').push($scope.testVal);
                    $scope.testVal = '';
                }
            };
            $scope.remove = function(valId){
                $scope.testObject.$ref().child('_parent/children').child(valId).remove();
            };
        });
    angular.bootstrap(document, ['app', 'firebase']);

**Comment by jwngr** [comment]
Hey there. I just tried your Fiddle and it acted as I would expect. When I removed the last item, it was removed from the JSON output. Am I missing something?

**Comment by ivarprudnikov** [comment]
I can confirm that I still experience an issue. If you open the above given fiddle, and add at least one item , and then try to remove all of what is in queue (all bullet points with "x"), then the last one will not be synced and stays in the view.

**Comment by maxrevilo** [comment]
Yes, I tested your fiddle and it happened to me too.

I saw the code and found that the function used to iterate through objects in Angularfire filters all the properties that start with either the dolar sign, **underscore** or dot.

https://github.com/firebase/angularfire/blob/master/src/utils.js#L300

So I think it is on purpose, you can't name parents with names that start with those characters.

**Comment by katowulf** [comment]
As mentioned in the docs, _, $, and . are considered private constructs and ignored by design, allowing you to add methods or properties with these prefixes which will not be synced to Firebase.

Why this strange construct? If you want to bind on the collection `children`, then bind on that instead of the root path. In general, binding on root is bad. Bind on exactly what you want synced, and use `$firebaseArray` for collections.

**Comment by ivarprudnikov** [comment]
@katowulf as far as I see, the behaviour is unexpected, because I work with endpoint where leaf does not have **underscore** (`url/_parent/children`). 
The obvious here is that when last child object is removed then `children` key has to be removed from tree as well (and it is removed) but update is not caught as Angularfire ignores it (because in this case it is sent for `url/_parent`). But as far as I(developer) was concerned I was working with the endpoint without **underscore**, unless it would be clear that none of the keys in all of my data structure can have underscores.

I suggest that documentation should be much clearer, stating something like `keys that start with _ $ . should not be stored/used in Firebase as Angularfire ignores those by design`.

In my case I use `_` quite heavily in Firebase when I store something like `_meta` information about the object(s)

**Comment by katowulf** [comment]
You are synchronizing on `url/` not, `children`. Thus, the keys in your object consist of `_parent`, which is ignored. Sync on `children` using `$firebaseArray` and your woes will disappear.
