### ISSUE TITLE
Disable console messages

### ISSUE THREAD

**Issue by sergiy-talashko** [firebase/angularfire#642]
Maybe someone already asked, but I cannot find solution.

So - how to disable all messages in console log in browser? Or leave error, but disable warning messages.
Maybe set some attribute for production version of site.

**Comment by jamestalmage** [comment]
Angularfire produces a very minimal console output (almost none). What are you seeing?

**Comment by sergiy-talashko** [comment]
I think this relates more to Firebase.js
But I hope your library has some solution.

Example output: 
```
FIREBASE: Attempt to read /rooms/536e60f5d39f9b0200bd3eb1 with auth=Success({"uid":"custom:55c1cdaa52a74b03001bee00","givenName":"pro-user-20@t.f.tv","admin":false})
FIREBASE: 	/: "false"
FIREBASE: 		=> false
FIREBASE: 	/rooms
FIREBASE: 	/rooms/536e60f5d39f9b0200bd3eb1: "true"
FIREBASE: 		=> true
FIREBASE: 
FIREBASE: Read was allowed.
FIREBASE: Attempt to write Success({"admin":true,"created":1438877183800,"id":"custom:559ed3152b5a0a03001c22ca","message":"tr","name":"Сергій"}) to /rooms/536e60f5d39f9b0200bd3eb1/-Jw2kqvPgNKezhHrF5ny as namespace admin
FIREBASE: 
FIREBASE: Admin has unlimited access.  Write allowed.
```

**Comment by katowulf** [comment]
You're probably authenticating with a custom token that has `debug: true`. And this has nothing to do with AngularFire.

**Comment by sergiy-talashko** [comment]
@katowulf Yes, we are using authenticating with a custom token. 
Thanks.

**Comment by garthtee** [comment]
Can you explain where you set debug to false? @katowulf @sergiy-talashko

**Comment by sergiy-talashko** [comment]
Nowhere. If you are using authenticating with a custom token (as in my case) - there are no good way to do this.
