### ISSUE TITLE
authWithPassword shows the password on request

### ISSUE THREAD

**Issue by raphaelpor** [firebase/angularfire#643]
Why the authWithPassword method is sending my passwords by URL? is it correct?
https://auth.firebase.com/v2/myapp/auth/password?&email=[myemail]&password=[mypassword]&[...]

**Comment by jwngr** [comment]
This is not an AngularFire issue. This is how the Firebase SDK itself sends the request. And no, there is no security issue here since the message is sent via HTTPS and we scrub our server logs.

**Comment by raphaelpor** [comment]
But trust only in a HTTPS request, isn't a good practice, right?

**Comment by jwngr** [comment]
Sorry, I'm not sure what your question is. Would you mind rephrasing it?

HTTPS is the industry standard for encrypting data across the web and prevents it from being sniffed unencrypted by malicious parties.

**Comment by raphaelpor** [comment]
I'm sorry. My fault. :wink:
