### ISSUE TITLE
unable to load user info

### ISSUE THREAD

**Issue by steady-daddy** [firebase/angularfire#645]
Hi,

For some reason I'm not able to fetch user info from the database in AngularFire version 1.1.2. Here's my code:

    var ref = new Firebase(FIREBASE_URL),
    auth = $firebaseAuth(ref);
  
    auth.$onAuth(function (authUser) {
        if(authUser){
            var ref = new Firebase(FIREBASE_URL+'users/'+authUser.uid);

            var user = $firebaseObject(ref);
            user.$loaded().then(function () {
                $rootScope.currentUser = user;
            });
        }else{
            $rootScope.currentUser = null;
        }
    });

The user object has `firstname`, `lastname` etc as fields but none of them are available. Not sure what's wrong here. Kindly help.

**Comment by katowulf** [comment]
There is no code here to authenticate the user. We can't help troubleshoot an authentication issue without a [complete, minimal repro](http://stackoverflow.com/help/mcve).

**Comment by steady-daddy** [comment]
Authentication is done using an authentication factory. Here's the code form the factory:

    myApp.factory('Authentication', function($firebaseArray, $rootScope, $firebaseAuth, $location, FIREBASE_URL){
    "use strict";

    var ref = new Firebase(FIREBASE_URL),
        simpleLogin = $firebaseAuth(ref),
        obj;

    obj =  {
        login: function (user) {
            return simpleLogin.$authWithPassword({
                email: user.email,
                password: user.password
            });
        }, //login

        logout: function(){
            return simpleLogin.$unauth();
        }//logout
    }; //obj

    return obj;
    });

Login is initiated by ng-submit="login()" which is handled in the `registration` controller here:

        $scope.login = function(){
        Authentication.login($scope.user)
            .then(function (user) {
                $location.path('/meetings');
            }, function(error){
                $scope.message = error.toString()
            });
    }; //login

The `statusController` checks for the login state and initializes view variables. The code is:

    var ref = new Firebase(FIREBASE_URL),
    auth = $firebaseAuth(ref);

    auth.$onAuth(function (authUser) {
    if(authUser){
        var ref = new Firebase(FIREBASE_URL+'users/'+authUser.uid);

        var user = $firebaseObject(ref);
        user.$loaded().then(function () {
            $rootScope.currentUser = user;
        });
    }else{
        $rootScope.currentUser = null;
    }
    });

Let me know if I missed anything else. Thank you.

**Comment by jwngr** [comment]
A error is clearly being eaten here at some point. Try adding a catch to your `$loaded()` promise:

```
user.$loaded().then(function () {
  $rootScope.currentUser = user;
}).catch(function(error) {
  console.log(error);
});
```

I bet you will see a `PERMISSION_DENIED` error, meaning your security rules failed. This could be a result of many things (as Kato alluded to): (1) you may not actually be authenticated yet (please very that `authUser.uid` is defined) or (2) your rules may be rejecting the request for some other reason. If it's (2), then you should provide us with the relevant rules you have. Also, try using the simulator in the Firebase Dashboard to test your rules. 

FWIW, you can simplify:

```
var user = $firebaseObject(ref);
user.$loaded().then(function () {
  $rootScope.currentUser = user;
});
```

to:

```
$rootScope.currentUser = $firebaseObject(ref);
```

`currentUser` will "just work" in your HTML template since AngularFire handles all the compile / digest loop for you.

**Comment by steady-daddy** [comment]
@jwngr no error is caught with the $loaded method.

**Comment by jwngr** [comment]
We will need a live repro to help you further. Looking at a block of code only gets us so far. Please provide a Plunker (you can fork [my AngularFire seed Plunker](http://plnkr.co/edit/u9I0Wu) to avoid any boilerplate) with a reproduction of the issue. Once you have that, re-open this issue. Thanks.

**Comment by steady-daddy** [comment]
I was adding some extra info for the user after the registration. Here's the code:

    register: function (user) {
            return simpleLogin.$createUser({
                email: user.email,
                password: user.password
            }).then(function(regUser){
                var ref = new Firebase(FIREBASE_URL+'users');
                var firebaseUsers = $firebaseArray(ref);

                var userInfo = {
                    date: Firebase.ServerValue.TIMESTAMP,
                    regUser: regUser.uid,
                    firstname: user.firstname,
                    lastname: user.lastname,
                    email: user.email
                };

                firebaseUsers.$add(userInfo);

            });//promise

So the problem was, a new id was automatically created for every new user. I had to make two changes to make it work. First, to provide the user id:

    var ref = new Firebase(FIREBASE_URL+'users/'+regUser.uid);

and second to add the userinfo with the `set` method.

    ref.set(userInfo);

Once I did that, the users in the users table were identified by ids like simplelogin:1 etc

Now, I'm able to fetch user by the same id. Thanks for your help folks!

**Comment by katowulf** [comment]
There's no reason to be using $firebaseArray in this context. You aren't modifying a collection. You're modifying single records in a singular context, and they have predefined keys. Since there are no bindings to the UI here, AngularFire isn't really necessary.

This would be simpler, more performant, and less buggy:

```
register: function (user) {
        return simpleLogin.$createUser({
            email: user.email,
            password: user.password
        }).then(function(regUser){
            var ref = new Firebase(FIREBASE_URL+'users');
            var userInfo = {
                date: Firebase.ServerValue.TIMESTAMP,
                regUser: regUser.uid,
                firstname: user.firstname,
                lastname: user.lastname,
                email: user.email
            };

            ref.child(regUser.uid).set(userInfo, function(err) {
                 // handle errors
            });
        });
```

**Comment by steady-daddy** [comment]
Just starting out with angularjs and firebase @katowulf, some experiment should be forgiven.  Appreciate you taking out time to explain. I'll keep that in mind. Thanks a lot.

**Comment by katowulf** [comment]
@steady-daddy please experiment and have fun. Also thanks for reaching out with your questions; we love helping people build amazing apps and everyone is new to the community at some point. Everything above is intended to be a learning tool and not a correction. Have a great day!
