### ISSUE TITLE
Calling `$extend` with a Class function is awkward and incorrectly documented

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#646]
The docs indicate that $extend() can be called with a class function. In practice, this works, but not as documented. The API documents indicate this will work:

```
    function Widget(ref) {
      $firebaseArray.call(this, ref);
      // do widgety things
    }

   var WidgetArray = $firebaseArray.$extend(Widget);
   new WidgetArray( ...ref... );
```

However, in practice, this does not return an array, but the instance that wraps the array (internally, AngularFire's constructor creates an array and returns that, so Array.isArray() will work as expected, and array functions can be used on it directly).

To make this actually work, one must do the following:

```
    function Widget(ref) {
      var res = $firebaseArray.call(this, ref);
      // do widgety things
      return res;
      // or this works, too:  return this.$list;
    }

   var WidgetArray = $firebaseArray.$extend(Widget);
   new WidgetArray( ...ref... );
```

We should ponder this to see if it can be simplified and also update docs to match.

**Comment by eXaminator** [comment]
Any chance of also supporting ES6 classes with babel somehow? It would be great if we could do something like this:

```javascript
import {FirebaseArray} from 'angularfire';

class WidgetArray extends FirebaseArray {
    constructor(ref) {
        super(ref);
    }
}

new WidgetArray( ...ref... );
```

**Comment by katowulf** [comment]
No plans to support ES6 for 1.0.

**Comment by katowulf** [comment]
There's no easy fix for this issue. I've changed it to a documentation fix. the solution is to `return this.$list` from the function, which is not immediately intuitive, but necessary to make `Array` functions (e.g. `Array.isArray()` and `Array.prototype.forEach()`) function correctly on `$firebaseArray` instances.
