### ISSUE TITLE
$getRecord(key) from $firebaseArray always return `null`

### ISSUE THREAD

**Issue by hugw** [firebase/angularfire#648]
Hey there,

I'm using `$firebaseArray` to manage some data but every time I try to get a single record using `$getRecord(key)` I always get a `null` response.

I don't know If I am doing something wrong, but please, take a look at this sample code: https://jsbin.com/qopiqifixu/edit?html,js,console

**Comment by puf** [comment]
The array hasn't yet loaded by the time you're trying to retrieve the keys. One way of fixing that is by waiting for the `$loaded()` promise to be fulfilled:
```
  tasks.$loaded().then(function(tasks) {
  
    var key1 = '-JyPlZ3tGOxcy0PVKewu';
    var key2 = '-JyPlaj72Hyo6T3aJchM';
    var key3 = '-JyPlbmtt86NVwFTkTY6';
  
    console.log(tasks.$getRecord(key1));
    console.log(tasks.$getRecord(key2));
    console.log(tasks.$getRecord(key3));
  });
```

**Comment by hugw** [comment]
Thanks @puf
