### ISSUE TITLE
Correct way to reverse $firebaseArray?

### ISSUE THREAD

**Issue by uofmmike** [firebase/angularfire#651]
[enhancement/question]

For the life of me i can't figure out how to reverse a $firebaseArray. 
I've tried 
-extending
-reverse order with ng-repeat
-tried a filter
-tried firebase orderByPriority()

And i can't seem to get it to stick. Any help/documentation would be much appreciated! 

I'm happy to do this anywhere, be it a factory, filter, controller. I just can't get it to stick! 

Most recent attempt: 
```
app.filter('reverseArray', function() {
	return function(input, scope) {
		if (input != null) {
			returnItem = [];			
			angular.forEach(input, function(item) {
				returnItem.push(item);			
		});		
		return returnItem;			
		} else		
		return input
	}
});
```

I'm sure this would be a common thing many would be looking for, so i would also like to propose adding this to the firebaseArray service.

Thanks to the community and folks behind this!

**Comment by katowulf** [comment]
AngularFire-seed has [a reverse filter](https://github.com/firebase/angularfire-seed/blob/master/app/components/reverse/reverse-filter.js)

Additionally, you can utilize a [query with orderByChild](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries) to reverse ordering at the server [1](https://groups.google.com/forum/#!searchin/firebase-talk/reverse/firebase-talk/5XSirxJnOMY/pzSm1ed-YXsJ) [2](http://stackoverflow.com/questions/17769607/firebase-reading-ordered-data-reversed-order) [3](http://stackoverflow.com/questions/15126360/possible-to-traverse-the-children-of-a-firebase-node-in-reverse-order), before passing your ref into $firebaseArray.

**Comment by uofmmike** [comment]
Thank you so much for the insanely fast reply!

Your solutions is fantastic! 
```
angular.module('myApp')
  .filter('reverse', function() {
    return function(items) {
      return items.slice().reverse();
    };
  });
```

Such a dumb move on my part...

I had  (wrongly)
 ` <div ng-repeat="post in posts |  limitTo: feedLimit | reverseArray " class='animate-repeat'>`

And I should have had: 
`<div ng-repeat="post in posts | reverseArray | limitTo: feedLimit" class='animate-repeat'>`

Turns out fundamental things like order matters are important to pay attention to!

Thank you again @katowulf for the quick reply!
