### ISSUE TITLE
Destroying all firebaseArrays and firebaseObjects when unauth

### ISSUE THREAD

**Issue by JerryBels** [firebase/angularfire#660]
Hello guys,

I have an issue in my app, when a user disconnects and I use $unauth(), I have a lot of "Error: permission_denied: Client doesn't have permission to access the desired data". I completed the security rules for my app, and since I have this issue (which is completely to be expected).

The number of errors is related to the number of firebaseArrays and firebaseObjects (often extended) that are currently watching data changes. My instinct tells me it's related.

So, is there a way to stop listening to everything at once, that I could use just before $unauth() ? Or maybe have I completely missed the point ?

Thanks !

**Comment by katowulf** [comment]
Hello! Have you tried the $destroy method?

**Comment by JerryBels** [comment]
Hey Kato ! Thanks for your fast answer. 

The $destroy method is applied on a specific firebaseArray or firebaseObject, if I'm not wrong. I don't want to have to get back to every active firebaseArray or firebaseObject to destroy it on logout ! That's why I asked for a command that would "cut" every active watcher.

**Comment by katowulf** [comment]
You would use a decorator and wrap those services, then tie that to your authentication process.

**Comment by JerryBels** [comment]
Okay, that's a little off my knowledge for now, I will work on it to understand how it works and then post back here with code if I reach a viable solution... Thanks for your help.

**Comment by katowulf** [comment]
Decorators are very simple. There's an example here: https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-extending-the-services-decorating-the-services

It might look something [like this](https://gist.github.com/katowulf/f264e7e0c7b8cefd1bcf).

Additionally, you may want to consider the approach here and whether this is worth this work. If you're not going to re-route users to a new controller on logout, things are going to be pretty broken. And the best time for destroying listeners is when the controller is unloaded, not later when you get the warning.

```
   $scope.$on('$destroy', function() {
       // call destroy on any existing synchronized arrays/objects
       // that way when we re-route to the logout screen, there are no warnings
   });
```

**Comment by JerryBels** [comment]
I could potentially do that and destroy every watcher when the user leaves the relevant page, but it's not really great for me - I'm using a caching system, keeping the page in the memory, so if I destroy the watcher at that moment, I'm losing the ability to show the page again immediately when asked for it. I need to get the data again...

I'm rerouting user on logout so no problem with that.

About decorators, I think I understand how it works now - but if I'm not wrong it gives the ability to add functions to each service separately. I can't call a function for every watchers alive. So, to destroy my watchers, it won't be better than $destroy I guess.

What about storing every synchronized service reference to a global array on a parent scope, and on logout looping through it to call $destroy for each ?

**Comment by katowulf** [comment]
That's what the linked gist does. Check it out.

**Comment by JerryBels** [comment]
Oh I only saw the doc link, not the gist ! That's awesome, I think it will completely do it. I will try it tomorrow and report here. Thank you so much !

**Comment by JerryBels** [comment]
Hey @katowulf ,

I just tried the gist you provided me, there is an issue though : 

    $firebaseArray.$extend is not a function

appears immediately in the console when I add the decorator (and indeed the data from any function using extend capabilities will not return).

**Comment by katowulf** [comment]
Great point. Updated the gist. That's about all the bandwidth I can provide for this. You'll have to check into how some of those tools work to adapt this further.

☼, Kato

**Comment by JerryBels** [comment]
Hey,

it won't work either : 

    Uncaught TypeError: Cannot read property '$loaded' of undefined

Thank you very much for your help anyway, I will try to continue from here.

**Comment by touletan** [comment]
I created a service to create all $firebaseArray and $firebaseObject and then calling the clean function just before unauth. 
.factory("AF", function ($firebaseObject, $firebaseArray) {
    var AFArray = [];
    var angularFire = {
        object: function (path) {
            ref = firebase.database().ref(path);
            o = $firebaseObject(ref);
            AFArray.push(o);
            return o;
        },
        array: function (path) {
            var ref = firebase.database().ref(path);
            a = $firebaseArray(ref);
            AFArray.push(a);
            return a;
        },
        clean: function () {
            for (i in AFArray) {
                if (angular.isDefined(AFArray[i]) && angular.isDefined(AFArray[i].$destroy)) {
                    AFArray[i].$destroy();
                }
            }
            AFArray = [];
        }
    };
    return angularFire;
})

**Comment by katowulf** [comment]
[This is](https://gist.github.com/katowulf/f264e7e0c7b8cefd1bcf) much simpler.

**Comment by meetbryce** [comment]
I still don't understand why this isn't just offered by the angularfire library. 

It seems to me that every possible use case would require it...

I'm assuming most people just ignore the console error, but it really bothers me that this isn't handled by the library.

**Comment by mpeguero** [comment]
Hi meetbryce this is really simple: 
```
//Your service
getdata(): Observable<any>{
   return this.af.database.list('datanode');
}
//In your component
this.sub = yourservice.getData().subscribe((data) =>{
     console.log(data);
}

ngOnDestroy(){
  this.sub.unsubscribe();
}
```
