### ISSUE TITLE
Suggestions on using multi path update with $$updated firebasearray?

### ISSUE THREAD

**Issue by dreadjr** [firebase/angularfire#664]
I am interested if anyone has already attempted to use `firebasearray` and multi path updates during the array lifecycle, it would be great for denormalized data.

**Comment by katowulf** [comment]
Since $$updated is called when there is a server update (not when you do a save from the client), it wouldn't really apply here. It wouldn't be difficult to add a saveAll() method, although the benefit of this, over just saving records individually, is not immediately clear. Do you have a use case in mind?

**Comment by dreadjr** [comment]
I wanted the update to be more transactional, so all locations are updated at once. Yeah thinking about it more it might work better on the `firebaseobject` but i guess i would just be writing another `$save` method in that case.

**Comment by jamestalmage** [comment]
It seems like there is a decent question/feature request in here somewhere.

It would be cool to offer a binding for denormalized where updates would be pushed across multiple nodes. I am not sure what an angularfire API would look like for that, and it may turn out to be prohibitively difficult to generalize.

Specifically, we should explore how [client-side-fanout](https://www.firebase.com/blog/2015-10-07-how-to-keep-your-data-consistent.html) should look in angularfire.

**Comment by dreadjr** [comment]
Yeah sorry for the ambiguity of the question, just started thinking about this.
I am playing around with overriding the  `firebaseobject.$save`, on the constructor having multiple firebase references and a function (to select which fields to update), then just doing the client-side-fanout in the $save. But i love the idea of generalizing it if possible. I know a lot of work has been done in the `firebase-utils` repository which might apply as well.

**Comment by katowulf** [comment]
Definitely need to update firebase-util to do multi-path writes as a single, atomic operation. Should simplify that code considerably and improve consistency. That is the ideal place to handle this sort of merge/join logic. Also, with focus shifting to Angular 2, I don't see a big use case for adding this as a feature in AF. But I'm open to discussion and I'd be happy to help resolve any specific use cases with a gist or two.

**Comment by jamestalmage** [comment]
@dreadjr ,
Note that firebase is pretty smart about only syncing changed data anyways. If you have already synced down a whole object, I am not sure it is worth your while to try and dirty check individual nodes and only upload them. It depends on your use case, but don't try to hard to outsmart the system. My advice would be wait to make that optimization until you know you need it.

**Comment by jamestalmage** [comment]
> with focus shifting to Angular 2, ...

It is not even released yet!

**Comment by dreadjr** [comment]
This is what i am experimenting with right now. [jsfiddle](http://jsfiddle.net/dreadjr/svjnskmb/)

@katowulf can you take a look, here is what i am thinking / assuming at this point. My approach may be way off though. I know a lot is left to be desired as well but it is a working prototype.

**Comment by katowulf** [comment]
Looks like it works. There's a lot of manual work here and also a lot of effort being expended to save specific titles instead of just saving the book object (is bandwidth an issue here? Are we doing millions of save events?) Firebase-util could definitely take some of the tedium of joining, merging, and saving out, but also doesn't optimize to the field level.
