### ISSUE TITLE
how to update by using extend

### ISSUE THREAD

**Issue by kruny1001** [firebase/angularfire#665]
app.factory("Message", function($firebaseArray) {
  function Message(snap) {
    // store the user ID so AngularFire can identify the records
    // in this case, we store it in a custom location, so we'll need
    // to override $$getKey
    this.message_id = snap.key();
    this.message = snap.val();
  }
  Message.prototype = {
    update: function(snap) {
      // store a string into this.message (instead of the default $value)
      if( snap.val() !== this.message ) {
        this.message = snap.val();
        return true;
      }
      return false;
    },
    toJSON: function() {
      // tell AngularFire what data to save, in this case a string
      return this.message;
    }
  };

  return Message;
});

how can I update Message object from a controller? what parameter should be placed onto snap for update function? Can you give me a example?

**Comment by katowulf** [comment]
Not at all sure what this means. There is no use of `$extend` or AngularFire in your example, although it does inject the unused `$firebaseArray` as a dependency. Could you clean this up, add formatting, and provide a complete use case of what you're trying to accomplish here?

**Comment by kruny1001** [comment]
The above code is an example from the official AngularFire documentation. What I understand from the code is "Message" Factory create a class and the "MessageFactory" extends firebaseArray object with a "Message" Class. Once I get a $firebaseArray via "MessageList factory". How can I update a Message class object itself directly. 

Once, MessageList factory instantiates with a Firebase reference. It returns an array with Message class objects. The Message class object has update member method from the document. But it keeps giving me a error because of snap parameter's "undefined val() function". 

If I get an array like this way, 

```javascript
...
controller('ctrl', function($scope, MessageList){
var array = new MessageList(ref);
// array[0] is Message class
array[0].update (??) // what parameter do I need to put in?

....
})
```

**Comment by katowulf** [comment]
The MessageList is used just like any other $firebaseArray instance. Reading and setting data is covered [in the guide here](https://www.firebase.com/docs/web/libraries/angular/guide/synchronized-arrays.html). Check out the Full Example near the bottom for a solid overview.
