### ISSUE TITLE
$firebaseObject.$extend wait for promise to resolve before $loaded

### ISSUE THREAD

**Issue by bostondv** [firebase/angularfire#666]
I'm trying to extend firebaseObject, load in additional data, then resolve $loaded only once all the data is loaded. However $loaded does not wait for the promise to resolve within $$updated.

This issue is the same as #629 but for firebaseObject.

plunkr example: http://plnkr.co/edit/sC8F0KX5cTz5Rdx16X9N

firebase@2.2.9
angular@1.4.7
angularfire@1.1.2

```js
$firebaseObject.$extend({
    $$updated(snapshot) {
      let record = $firebaseObject.prototype.$$updated.call(this, snapshot);
      let ref = new Firebase(fbUrl);

      return $q((resolve) => {
        $firebaseObject(ref.child(`profiles/${this.uid}`))
        .$loaded()
        .then((profile) => {
          this.profile = profile;
        })
        .finally(() => {
          resolve(record);
        });
      });
    }
}
```

**Comment by katowulf** [comment]
`$$updated` isn't part of the criterium for determining when `$loaded()` resolves. That's done by making a direct call to `once('value'...)`. There isn't any way to make $loaded() wait for $$updated and if you think this through logically, that probably doesn't make sense ($$updated is called any time data is changed, not once during the load process)

**Comment by bostondv** [comment]
Thanks @katowulf. Is there another way achieve what I'm trying to do?

**Comment by katowulf** [comment]
Probably. What is it you're trying to do? : )

**Comment by bostondv** [comment]
:)

I'm trying to get a firebaseObject of a user at `/users/{id}` and then attach another path to the `profile` key of the user object with their profile at `/profiles/{id}`. Finally I want to have everything loaded before $loaded is triggered.

I've also tried NormalizedCollection but it doesn't seem to work for my use case? Here's how I want to join the data:

```json
{
    "id": "123456",
    "joinDate": "2015-09-25",
    "profile": {
      "name": "Bruce Lee",
      "phone": "4165552121"
    }
}
```

I'd also be happy with this:

```json
{
    "id": "123456",
    "joinDate": "2015-09-25",
    "name": "Bruce Lee",
    "phone": "4165552121"
}
```

Raw data:

```json
{
  "users": {
    "123456": {
      "id": "123456",
      "joinDate": "2015-09-25"
    }
  },
  "profiles": {
    "123456": {
      "name": "Bruce Lee",
      "phone": "4165552121"
    }
  }
}
```

Current code, which doesn't tie in with loaded...

```js
function ProfileFactory(fbUrl, $firebaseObject, $firebaseUtils, $q) {
  'ngInject';

  let Profile = $firebaseObject.$extend({
    $$updated(snapshot) {
      let record = $firebaseObject.prototype.$$updated.call(this, snapshot);
      let ref = new Firebase(fbUrl);
      let defaults = this.$$defaults();

      if (angular.isObject(defaults)) {
        angular.forEach(defaults, (v, k) => {
          if (!this.hasOwnProperty(k)) {
            this[k] = v;
          }
        });
      }

      this.profile = $firebaseObject(ref.child(`profiles/${this.uid}`));

      return record;
    },

    toJSON() {
      let data = angular.extend({}, this);
      delete data.profile;
      data = $firebaseUtils.toJSON(data);
      return data;
    },

    $$defaults() {
      let defaults = {
        profile: {}
      };
      return defaults;
    },

    fullName() {
      return `${this.profile.firstName} ${this.profile.lastName}`;
    }
  });

  return (uid) => {
    let ref = new Firebase(fbUrl);
    return new Profile(ref.child(`users/${uid}`));
  };
}

export default ProfileFactory;
```

**Comment by bostondv** [comment]
I've tried various combinations of normalized collection like this which come close. But I cannot figure out how to map all the properties of `users` to map to the root of the object rather than in `$value` or another key.

```js
new Firebase.util.NormalizedCollection(
      ref.child(`users`),
      ref.child(`profiles`)
    ).select(
      'users.$value',
      { 'key': 'profiles.$value', 'alias': 'profile' }
    ).ref();
```

**Comment by jwngr** [comment]
Is there a specific reason why you don't just combine your `/users` and `/profiles` nodes? I assume they both have the same children and it seems logical for your `/users` node to just contain a `/profile` node for each user.

**Comment by katowulf** [comment]
What @jwngr said may be simplest. To knowledge share, you just need to tweak the fields on your NormalizedCollection:

```
new Firebase.util.NormalizedCollection(
      ref.child(`users`),
      ref.child(`profiles`)
    ).select(
      'users.id', 'users.joinDate',
      'profiles.name', 'profiles.phone'
    ).ref();
```

Assuming `id` is not shared between profile and user paths (not sure why it wouldn't be), then you could  specify a dependency on a field value, instead of a key, by passing an array as the ref:

```
NormalizedCollection(
      [ref.child('users'), 'user'],
      [ref.child('profiles'), "profile", "user.id"]
).select(
      'user.id', 'user.joinDate', 'profile.name', 'profile.phone'
);
```

**Comment by bostondv** [comment]
My thinking is that its a more optimal structure to denormalize and keep the data flatter. Isn't that recommended practice? 

For the current scale of my app I'm sure it doesn't really matter. But anyways having a method to combine the denormalized data like this would be handy.

@katowulf thanks for the tweaks. Is it required to specify each field in select()? Any way to select all? In reality I have a lot more fields in the user and profile paths and would be ideal not to have to maintain the list of fields to select here.

**Comment by katowulf** [comment]
You have to specify all fields; this is used by NormalizedCollection to map fields back to the paths that own them (since Firebase is schema-less, this definition is critical).

**Comment by bostondv** [comment]
Ok sounds good. If there's any way to add a select all sometime you have my vote ;)

**Comment by jwngr** [comment]
Denormalizing / flattening your data is definitely best practice, but I think this is taking it too far to the extreme. The `/users` and `/profiles` node have a 1:1 mapping to them and often when you get one, you'll want to get the other. Putting them in the same place seems logical and will simplify your code.

**Comment by bostondv** [comment]
@jwngr thx, good to know!
