### ISSUE TITLE
Synchronized Arrays

### ISSUE THREAD

**Issue by thealmikey** [firebase/angularfire#667]
In the angular guide Synchronized Arrays section this example no longer works
 ```
<button ng-click="messages.$remove(message.$id)">x</button>
```
when deleting an item from an ng-repeat generated list,it only worked once I removed the $id to look like this
```
 <button ng-click="messages.$remove(message)">x</button> ```

**Comment by jwngr** [comment]
Hey there, you are very correct! [`$remove()`](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-removerecordorindex) can take the array index or the array item itself. It cannot take the key which is what we were trying to do. Sorry if that caused you any issues!

I put together a Plunker showing this issue [here](http://plnkr.co/edit/ZAu5BAYuXrwrUfmqY4aT). If you look at the `removeMessage()` method, you will see the failing line commented out. If you uncomment it and comment out the working line, it throws the following error:

```
Error removing message: Invalid record; could not determine key for -K1GV8GgK71ZPgklTjRR
```

I'll get out docs updated and the fix should go out within a day or so.

**Comment by jwngr** [comment]
This is now fixed in production [here](https://www.firebase.com/docs/web/libraries/angular/guide/synchronized-arrays.html).

**Comment by thealmikey** [comment]
Awesome :+1: Learning to use firebase through the documentation. Great product btw!
