### ISSUE TITLE
Ionic, SSL error when testing in iOS simulator

### ISSUE THREAD

**Issue by aubm** [firebase/angularfire#668]
Hello, I am facing an issue when deploying an Ionic app in the iOS simulator (or in a real iPhone device).
While my app can fetch data from Firebase in a web browser (even in Safari mobile), trying to do the same thing once the app is built will output the following error (in Safari debug console) :

```
Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made.
```

As this is my first experience with Ionic, I can't say for sure this has to do with Firebase but I don't really know where else to look for a solution. Maybe someone here had a similar issue before ...

I created a minimalist Ionic app which reproduce this behavior, it's available here : https://github.com/aubm/ionic-firebase-test

Thanks in advance for helping ...

Cordova version : 5.3.3
Ionic version : 1.7.4
Node version : v0.10.40

**Comment by jamestalmage** [comment]
Your app worked fine for me.

I was running Node 4.1.2, on OSX.

```sh
$ git clone your-repo
$ cd your-repo
$ npm install
$ npm install -g cordova ionic ios-sim
$ ionic platform add ios
$ ionic build ios
$ ionic emulate ios
```

**Comment by aubm** [comment]
I can't tell why, but uninstalling the app before rebuilding it again in the simulator made it work again. Sorry for the trouble ...
