### ISSUE TITLE
Images(stored as base64 string) retrieved from Firebase takes too long to load(around 20-30 seconds). Any idea why this delay is happening?

### ISSUE THREAD

**Issue by abhi7cr** [firebase/angularfire#669]
We tried 2 options so far:
1.  using  ref.once("value") and ref.on("value)
2.  $FirebaseArray. with $loaded event

The loading time is really slow for both the cases but overall the Array seems to takes more time than the 1st approach. We are using Supersonic framework to create our mobile app.

Any thoughts?

**Comment by jamestalmage** [comment]
This is almost certainly a Firebase issue (not angularFire).

How big are these files?

Somebody from FB may correct me, but I would wager that Firebase is not optimized for serving images. You are not going to be able to implement caching, I doubt firebase transfer speeds compare favorably to GCS/S3, and I'm sure Firebase bandwidth costs more. If this is for a low traffic prototype, then by all means - use firebase.

Create a minimal demo with only firebase as a dependency. Just have it load up a single image. That eliminates Supersonic / angularFire as the source.

**Comment by abhi7cr** [comment]
Thanks for the quick response ! Image size would be approx 500-700 KB. And yes there is going to be high traffic for our app. We were also considering moving to Parse/s3.

**Comment by jamestalmage** [comment]
I can't comment on Parse vs Supersonic. I've never used either.

The mechanics of either solution will be similar.

What type of security do you want for the image?

The easy option is using a secret URL. Simply knowing the URL is what grants access. It can be made sufficiently long that it's unlikely anyone would ever guess it, so "cracking" a secret URL is not a security concern. However, once the secret URL is known, there are no further checks (logged in? paid up on account? doesn't matter if you know the URL).  The exception here might be using GCS [cookie base authentication](https://cloud.google.com/storage/docs/authentication#cookieauth), but that means forcing your users to have a google account.

Signed GET requests offer additional control (not necessarily more security), but you introduce additional server side code and overhead.

In either case, you are going to want to use Signed PUT requests to validate uploads. That will require a server. Here is the [GCS documentation](https://cloud.google.com/storage/docs/access-control?hl=en#Signed-URLs) on the subject.

**Comment by abhi7cr** [comment]
We aren't bothered about security that much since its just going to be an
app used for a college project . We just wanted the loading time to reduce.
So your saying we just store the URL in firebase and retrieve the image
through GCS/S3?

**Comment by jwngr** [comment]
James is right in that, in general, Firebase is not a great solution for blobs like images, videos, and files. You are better off storing the blobs in Google Cloud Storage of Amazon S3 and storing metadata like the URLs in Firebase. You can see some more information [here](https://groups.google.com/forum/#!searchin/firebase-talk/images%7Csort:date/firebase-talk/ANfrkwT-_rw/4wpFfvlpzRMJ). Short story is that this is a very common feature request and it is a top priority for us. We have plans for a true blob storage solution so you don't have to hack together something for yourself. Hang tight!

**Comment by jamestalmage** [comment]
> So your saying we just store the URL in firebase and retrieve the image through GCS/S3?

Yep, that is what I am saying.

> We have plans for a true blob storage solution so you don't have to hack together something for yourself. **Hang tight!**

How close is that?

**Comment by katowulf** [comment]
It's under active development, though priorities may--and do--shift. Like most Google products, we don't publish a public road map, offer ballparks or release dates, so we can't be more specific.

**Comment by mcdonamp** [comment]
That time is now! 🚢🔥🎉

Check out [Firebase Storage](https://firebase.google.com/docs/storage/web/start), it'll make this problem so much easier :)

**Comment by mohammad1990** [comment]
is the FirebaseStorage solve the problem or still I need to upload my image to GCS then store the link in the firebase. Special If I have to download and upload many images in my app.

**Comment by mcdonamp** [comment]
We handle the upload to GCS and then you can store that link anywhere (like the Firebase DB). It actually does make things much easier though, I promise :)
