### ISSUE TITLE
How to clean up all watchers

### ISSUE THREAD

**Issue by blackxored** [firebase/angularfire#670]
Since this doesn't appear to maintain any global state (which is good), there's no obvious way, if any, to clear all watchers in a single instruction AFAIK.

My scenario: 
While the user is logged in, I don't want to destroy "item component" watchers (say a list), when the "item component" is `$destroy`ed, i.e. user navigates away. However I do want to clear them on logout. 

Any clues?

**Comment by katowulf** [comment]
Add a decorator on $firebaseArray/Object that stores any instances created in an array. Add a decorator on $firebaseAuth.unauth() that iterates the array and calls $destroy on the instances.
