### ISSUE TITLE
Query support - is it planned?

### ISSUE THREAD

**Issue by artch** [firebase/angularfire#673]
Are there any plans to add Query support to AngularFire? `$firebaseObject` wrapper cannot accept [`Query`](https://www.firebase.com/docs/web/api/query) objects, which are quite useful. 

Personally I think of something like this (using the Tutorial code on Query page):

````javascript
var ref = new Firebase("https://docs-examples.firebaseio.com/samplechat/messages");
var query = $firebaseObject( ref.orderByChild("timestamp").limitToLast(100) );
query.$loaded().then(function() {
  angular.forEach(query, function(value, key) {
    console.log(key, value);
  });
});
```

**Comment by katowulf** [comment]
> $firebaseObject wrapper cannot accept Query objects

Are you receiving an error? Do you have a repro?

**Comment by andreev-artem** [comment]
Actually, no errors on the first sight. Though do you mean that passing Query object instead of Firebase object is expected and fully acceptable behavior?

**Comment by katowulf** [comment]
Passing a query object into a $fireabseObject constructor should work fine.

**Comment by jwngr** [comment]
Yup, queries are fully supported. We have (minimal) test coverage for it [here](https://github.com/firebase/angularfire/blob/1b9ede49883fc330eb889b4c024d3aff0b3ea80d/tests/unit/FirebaseObject.spec.js#L44-L49).

**Comment by artch** [comment]
Thanks for clarification. My quick tests have shown a certain level of incompatibility, but probably it was my own fault as my test suite is pretty complex and not isolated properly.

It might make sense to add a note to `$firebaseObject` description in the API docs. Currently it tells that only Firebase references can be passed into.

**Comment by jwngr** [comment]
I just sent @katowulf a PR to our website with a note about passing in a query to both `$firebaseArray` and `$firebaseObject`. It should go out in a day or two. Thanks for the suggestion.

If you end up running into issues using queries, please put together a minimal repro and send it our way. Good luck!
