### ISSUE TITLE
non-destructive $save() method?

### ISSUE THREAD

**Issue by colindevs** [firebase/angularfire#674]
I have a question regarding the `$save()` method. Is there a way to use it without replacing the object to which changes are made to?

Use case: I have a user and want to add or change a property of their profile. I could locally store the user object and make changes, then `$save()`:
```
$scope.update = function(){
   var user = $firebaseObject(ref.child('users').child(uid));
   user.name = $scope.newUserName;
   user.$save();
}
```

Well, when I do this, it completely erases the user's object and replaces it with one property: `name`.
So, the `$save()` method must be what's messing things up, right?

My question: 
> Is there a way to only update the part of the object that was changed, not completely replace the object with only that part?

This might be done with a `$update()` type of function, **which I actually saw mention of in [this](https://github.com/firebase/angularfire/issues/238#issuecomment-154894541) issue (#238)**

I actually have a very detailed use case regarding an app I'm making, and can provide a detailed, screenshot-heavy narrative if needed.

I hope this clearly describes the problem, and that someone will respond soon!

Also, if you have the time, come talk on twitter [@colindevs](https://twitter.com/colindevs)!

**Comment by katowulf** [comment]
Not supported. You're probably looking for $firebaseArray.

**Comment by jwngr** [comment]
I'm a bit confused by the code you provided. Given what I see, I would *not* expect the entire object to get overwritten with just a name. It should keep everything around and add in a name. Can you please provide a repro (JSFiddle, Plunker) which shows the overwrite behavior you are talking about?

Also, please make sure you are using the latest version of all libraries to rule out any old issues.

**Comment by colindevs** [comment]
Yeah, I wouldn't expect it to do so either... That's my point.
I'll put together an example.

**Comment by colindevs** [comment]
Here is the link to a Plinker I created as an example:
<a href="http://plnkr.co/edit/RgcInFVnQx187QDpe7pi?p=preview" target="_blank">http://plnkr.co/edit/RgcInFVnQx187QDpe7pi?p=preview   -></a>

Please check out the code!

**Comment by jwngr** [comment]
So the issue here is that you are not waiting for the object to initially sync with Firebase before you are updating it and saving it back to Firebase. As such, you overwrite the existing value. [Here](http://plnkr.co/edit/P6Z00NIznO8KLdvkvbCC) is an updated Plunker with the correct behavior.

For more information, see [this StackOverflow post](http://stackoverflow.com/questions/27049342/asynchronous-access-to-an-array-in-firebase/27050749#27050749) (which is about `$firebaseArray`, but still is relevant).

**Comment by colindevs** [comment]
Alright, here is a quick GIF showing the <a href="http://plnkr.co/edit/RgcInFVnQx187QDpe7pi?p=preview" target="_blank">plunker</a> in action:

![save-example](https://cloud.githubusercontent.com/assets/12850952/11047582/4de72978-8701-11e5-9092-ac97c1b0988d.gif)


The resolution might be low, so it might be hard to see.
I'll summarize it later.
Please check out the code <a href="http://plnkr.co/edit/RgcInFVnQx187QDpe7pi?p=preview" target="_blank">here</a> for a further understanding.

**Comment by colindevs** [comment]
So basically, I shouldn't locally store a `$firebaseObject` *and* `$save()` it inside the same function. I should retrieve it earlier, and then just reference the local variable from the function in which changes are made?

For example, I should do...
```
$scope.user = firebaseObject(...)
```
...before doing 
```
$scope.changeUser = function(){
   $scope.user.name = 'New name';
}
```

**Comment by katowulf** [comment]
If the goal is to set the user's name, you don't need a $firebaseObject. You can just do `ref.child('name').set( "new name" );`

If the goal is to update several fields on a record, this will work: `ref.update( {foo: 'foo', bar: 'bar' } );`

$firebaseObject and $firebaseArray or for binding remote data to a local view and to handle all the timing and synchronization on your behalf. If your goal is to just write data to Firebase, just write it and skip the bindings. 

If you want fine-grained control of how data is saved or synchronized, and want bindings too, then check out $extend and override the $save functionality to meet your needs.

To provide any further help beyond this, you'll need to lay out a specific use case, with all the constraints, and explanations of why these don't meet your needs to avoid [XY problems](http://meta.stackexchange.com/questions/66377/what-is-the-xy-problem/66378#66378).

**Comment by colindevs** [comment]
So the vanilla Firebase JS methods are all that are necessary?
And they work well with Angular?
