### ISSUE TITLE
$firebaseArray $priority: sort issue

### ISSUE THREAD

**Issue by douwevdijk** [firebase/angularfire#675]
Hi there,

In the latest release ( since 1.0 ) I found a bug where updates on priority are not reflected to the client ( unless the client reloads ). In previous version(s), this was not an issue. For me, in this case, it is causing a problem where we need the array to be sorted on priority.

**Comment by katowulf** [comment]
Hi there! Please provide a minimal repro that demonstrates.

**Comment by douwevdijk** [comment]
Sure. I have created a fiddle to demonstrate the issue. In this fiddle I have used both Angularfire and the standard Firebase API. If you click on the button it will add ( push ) a new record to the list. I then update this item with a priority, but as you can see I only get an update using the Firebase API, but not by using the $firebaseArray function.

see here:
https://jsfiddle.net/23g96sah/

**Comment by douwevdijk** [comment]
One update from my side ( if you look at the code in the repro ). If I use the following code it does work:

```
var t = dealers.push();
t.setWithPriority({omzet: 50}, 5);
```
The issue occurs when I use setPriority().

**Comment by katowulf** [comment]
As mentioned in the docs, if you use Array.push(), the items will not be properly ordered. Use firebaseArray.$add() instead.

**Comment by katowulf** [comment]
On a further thought here, there are some examples of doing custom sorting. You could use [this strategy with $watch](https://www.firebase.com/docs/web/libraries/angular/api.html#angularfire-firebasearray-watchcb-context) to custom sort the values and still use push(), if that's needed for some reason.
