### ISSUE TITLE
Is this an incorrect use of $loaded ? 

### ISSUE THREAD

**Issue by elliot-a** [firebase/angularfire#676]
Does the $loaded method of a $firebaseObject not actually wait for the object to be fully loaded in? Is there a way I can achieve this? Without the timeout - obviously :)

    gameObject.$loaded().then(function(){ 

      setTimeout(function(){
        console.log(gameObject.gameType); // return "typeName"
      }, 1000);

      console.log(gameObject.gameType); // return undefined

    });

**Comment by jwngr** [comment]
Can you please provide a live repro of this issue (Plunker or JSFiddle)? Looking at your code, I would expect both log statements to return the correct value. Also, make sure you are using the latest versions of Firebase and AngularFire to rule out any bug which has since been fixed.

**Comment by douwevdijk** [comment]
Can you try this:

```
gameObject.$loaded().then(function(**data**){ 
    console.log(**data**);
});

```

**Comment by elliot-a** [comment]
@douwevdijk -  No change unfortunately.

@jwngr - I have isolated the code into a fiddle and it seems to work so it must be something else in my code base that is causing the problem. My versions are up to date so I will look elsewhere. (My working fiddle - http://jsfiddle.net/3WcWu/150/ )

Thanks for you help - I will let you know if when I find the cause it is something that might be useful to you.

**Comment by elliot-a** [comment]
Just in case anyone has the same issue - turns out that my data was being changed outside of that directive at the same time the directive was being added to the DOM. So $loaded was functioning correctly its just that the data wasn't ready yet.

**Comment by katowulf** [comment]
Glad you sorted it Elliot! The repro is mighty in bug squashing.
