### ISSUE TITLE
Question $firebaseArray

### ISSUE THREAD

**Issue by kruny1001** [firebase/angularfire#678]
to add element of array. 

var firebaseArray = $firebaseArray(ref);
firebaseArray.$add({cnt:cnt}); 

but I don't want to load all data at "ref" for just adding one element. what should I do?

**Comment by puf** [comment]
The $firebaseArray class will load all data. So don't use $firebaseArray
and add the element to the ref directly:

    ref.push({ cnt: cnt });

AngularFire is built on top of Firebase's regular JavaScript SDK. So they
interact nicely and you can fall back to the regular JavaScript SDK in
cases where AngularFire doesn't suit your needs, or isn't needed.

**Comment by kruny1001** [comment]
Thanks
