### ISSUE TITLE
Angular2 support

### ISSUE THREAD

**Issue by vargalas** [firebase/angularfire#679]
Guys,

do you have a version supporting the current state of Angular2? A2 should be ready soon and seems to be a really hot thing.

**Comment by katowulf** [comment]
Check out [this video by Sara on Angular2 + Firebase](https://www.youtube.com/watch?v=RD0xYicNcaY&feature=youtu.be).

**Comment by katowulf** [comment]
Here's some direct links to the code in her demo repo:

https://github.com/sararob/angular2base/blob/master/src/app.ts#L22
https://github.com/sararob/angular2base/blob/master/src/firebasepipe.ts

**Comment by vargalas** [comment]
Thank you very much!
Yo're a better friend than Google was!

**Comment by maxxx333** [comment]
hello, is any estimated time for official angular 2 support, may be beta release?

**Comment by katowulf** [comment]
We'd like to have something stable before ng-conf. But timelines vary and priorities shift.

**Comment by patie** [comment]
any news?

**Comment by jwngr** [comment]
https://github.com/angular/angularfire2
