### ISSUE TITLE
Possible to expand `$firebaseArray` with additional queries?

### ISSUE THREAD

**Issue by drautb** [firebase/angularfire#680]
I need to do pagination of sorts in my app. I'd like to display some number of items, and then as the user scrolls down to the bottom of the page, load more. Something similar to [this][1].

I want to do something like this: (in the demo)

```js
var query = messagesRef.orderByChild("timestamp").limitToLast(10);
var list = $firebaseArray(query);
```

But then I want to perform another query, and tack its result onto the end of `list`, something like this:

```js
var query = messagesRef.orderByChild("timestamp").startAt(endOfList).limitToLast(10);
list.concat($firebaseArray(query));
```

The angularfire API docs say:

> Note that, while the array itself should not be modified, it is practical to change specific elements of the array and save them back to the remote database: [example]

So that leads me to believe that I can't do this...is there another way to expand the contents of a `$firebaseArray` with additional queries?

[1]: http://isotope.metafizzy.co/v1/demos/infinite-scroll.html

**Comment by katowulf** [comment]
Not in the scope of AngularFire. But check out the [Paginate](http://firebase.github.io/firebase-util/#/toolbox/Paginate/example/) class in firebase-util.

**Comment by drautb** [comment]
Ok, thanks! I found the Paginate class earlier in my googling, but was avoiding it due to the 'This is Beta, don't use in production' note that was on it. I'll give it a shot.
