### ISSUE TITLE
direct consultations without downloading database

### ISSUE THREAD

**Issue by newmesiss** [firebase/angularfire#683]
good afternoon, I wonder if it is possible to consult firebase without having to download the database. I have a database and arry 5000 item but do not want to download all that information to just search for data, you can create the query and search that data firebase?

**Comment by puf** [comment]
You can both access specific items (`$firebaseObject(ref.child('user').child(userid))`) or query for items (`$firebaseArray(ref.child('.messages').orderByChild('timestamp').limitToLast(50))`). Read more about it here: https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries
