### ISSUE TITLE
Infinite $digest loop on auth with OAuth redirect

### ISSUE THREAD

**Issue by izeau** [firebase/angularfire#686]
Disclaimer: I’m a Firebase newbie and might do things wrong.

I’ve setup this simple Ionic app with 2 states (`settings` bound to `/settings`, `game` bound to `/game`, nothing fancy). I want my users to be able to authenticate using a “Log in with Facebook” button from my `settings` state, but they are allowed to get to the `game` state without doing so; I want them to be able test the waters before signing in.

Here are my states definitions:

```js
$stateProvider.state('game', {
  url: '/game',
  template: '...'
});

$stateProvider.state('settings', {
  url: '/settings',
  template: '...',
  controller: SettingsController,
  controllerAs: 'settings',
  resolve: {
    currentUser: function (Auth) { return Auth.$waitForAuth(); }
  }
});

$urlRouterProvider.otherwise('/game');
```

The `Auth` service is the idiomatic `return $firebaseAuth(new Firebase(FIREBASE_ENDPOINT));`.

Now for the `SettingsController` part:

```js
function SettingsController ($log, Auth) {
  this.login = function () {
    Auth
      .$authWithOAuthRedirect('facebook')

      // This never gets called in the current environment (Chrome), putting it up here for consistency
      .catch(function (err) {
        return err.code === 'TRANSPORT_UNAVAILABLE' ? Auth.$authWithOAuthPopup('facebook') : $log.error(err);
      });
  };
}
```

When I click the “Log in with Facebook” button, triggering the `settings.login()` function from my template, I’m redirected as intended to the Facebook login page (which I don’t see anymore since I’ve already accepted the permission dialog), then back to my app with a `__firebase_request_key=...` parameter in my hash (`http://localhost:8100/#/settings?__firebase_request_key=...`).

*Then all hell breaks loose.*

I don’t know what causes this to happen, but the `$stateChangeStart` event is fired repeatedly (from the abstract root empty-string-named state to the `settings` state), causing the `resolve.currentUser` to be called multiple time as well but also wreacking havoc on my app with this infamous Angular exception:

```plain
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
```

Moreover, the `__firebase_request_key=...` part stays in the URL (I guess it should not?) and no other ui-router related event gets fired — neither `$stateChangeSuccess` nor `$stateChangeCancel` nor `$stateChangeError`.

Alas I’m logged in! — but this exception is getting on my nerves and I can’t find a proper solution no matter how much I try.

---

Here’s a few avenues I’ve explored to no avail:

  * Rename states to prefix them with `app.` (e.g. `app.game`, `app.settings`) and creating an abstract `app` state bound to an empty URL (or simple `/`) and a `<ui-view/>` template.
  * Replace the `$urlRouterProvider.otherwise` part to use `$state.go`.

```js
// As suggested by https://github.com/angular-ui/ui-router/issues/600#issuecomment-47228922
$urlRouterProvider.otherwise(function (injector) {
  injector.get('$state').go('game');
});
```

---

I created this project during the week and am therefore using recent versions of these libraries, using npm and Browserify:

Library             | Version
------------------- | -------
angular             | 1.4.8
angular-animate     | 1.4.8
angular-sanitize    | 1.4.8
angular-ui-router   | 0.2.15
angularfire         | 1.1.3
firebase            | 2.3.2
ionic-sdk           | 1.2.1

Thank you for taking the time to read this wall of text! I hope we can work out a solution.

**Comment by jwngr** [comment]
I'm not sure I have any ideas off the top of my head. A JSFiddle or Plunker would be super useful here and usually making a minimum repro helps find bugs on the developer end. One thing to note is that you should make sure to not navigate the page away when doing the authentication. If your login button is in a `<form>` element then it will navigate the page upon clicking, which will cause the authentication to not work and can cause unexpected errors. So that is one thing to look into. Without a repro though, I'm not sure I can be of much help.

**Comment by jwngr** [comment]
Closing due to lack of a repro. If you have one, please provide it and re-open this issue.
