### ISSUE TITLE
Support angular 1.5

### ISSUE THREAD

**Issue by chaffeqa** [firebase/angularfire#689]
Im guessing you dont need to do anything to get this to work

**Comment by jwngr** [comment]
It looks like Angular 1.5 is still on a release preview. We won't update the Bower and npm dependencies in this repo until they cut an official, stable `1.5.0` release. I imagine AngularFire will work with the current  1.5 release candidate right out of the box, although I have not tested it myself. If you want to, go ahead and try and let us know if you run into any issues.

**Comment by chaffeqa** [comment]
Yep figured, fyi angularfire seems to work fine on `rc.0`!

Just wanted to make sure this was on the radar, forking isn't too fun heh

**Comment by jwngr** [comment]
Completely understand. We just typically don't want to add official support until it's past the release candidate stage. Once `1.5.0` lands, we will upgrade the dependencies here. I'm glad that things seem to be working without changes. Makes our job easier. Thanks for keeping us honest!
