### ISSUE TITLE
$set missing

### ISSUE THREAD

**Issue by lostlivio** [firebase/angularfire#690]
I noticed in version Version 0.6.0 there was a $set that returned a promise but it was removed in 1.0.0.

I am trying to write data to a specific location but the $add function also creates a key value and stores the object under that instead at the root.
- profiles
   - uid
        - keyValue
            - email
            - phone

what I want to store the data is like
- profiles
   - uid
        - email
        - phone

Why was $set removed?

**Comment by katowulf** [comment]
See release notes and linked migration guide. https://github.com/firebase/angularfire/releases/tag/v1.0.0

**Comment by jwngr** [comment]
You can also read through https://github.com/firebase/angularfire/issues/593 for some related discussion.

**Comment by lostlivio** [comment]
Thanks
