### ISSUE TITLE
Multiple orderByChild

### ISSUE THREAD

**Issue by bsssp** [firebase/angularfire#692]
Hey there, 
i have some questions.
which is the best form to execute a query like "select * from table where prop1=1 and prop2=1"? 
I tried this $firebaseArray(ref).orderByChlid("prop1").equalTo(1).orderByChild("prop2").equalTo(1); 
but it throws an error, see: https://www.firebase.com/docs/web/guide/retrieving-data.html .
What it the best practice to do it and why does not work with orderByChild?

Kindly Regards

**Comment by katowulf** [comment]
AngularFire is just a bindings lib on top of the Firebase SDK. Since the SDK doesn't support multiple query fields, AngularFire can't support this either.

See http://stackoverflow.com/questions/34104270/filter-and-sort-on-multiple-values-with-firebase for more, and some ideas.

**Comment by bsssp** [comment]
Many thanks for the reply and for the link it was very useful!

**Comment by katowulf** [comment]
Happy to help. Thanks for building apps with Firebase.
