### ISSUE TITLE
Es6 Support?

### ISSUE THREAD

**Issue by LoganArnett** [firebase/angularfire#693]
Curious to see if it is on the roadmap to support Es6 for referencing the different services like `$firebaseObject` or `$firebaseArray` being used like this at the top of the file

``` javascript
import $firebaseArray from 'angularfire'

angular.module('goesHere', ['firebase'])
// and so on
```

**Comment by katowulf** [comment]
ES6 will be supported in AngularFire2, which @jeffbcross and @davideast are leading up.

**Comment by LoganArnett** [comment]
Awesome thanks @katowulf :+1:

**Comment by timothytavarez** [comment]
Woooo. Didn't even know about an AngularFire2. Pretty excited to see that.

**Comment by pequet** [comment]
game changer indeed. very much looking forward to this.

**Comment by Phoqe** [comment]
No support coming for AngularFire 1.x? :cry:
