### ISSUE TITLE
Support Angular 1.5 for npm and bower

### ISSUE THREAD

**Issue by davideast** [firebase/angularfire#694]
Angular 1.5 is fresh off the press. The [bower](bower) and [npm](npm) installs should support be able to resolve Angular 1.5 as a dependency.

[bower]: https://github.com/firebase/angularfire/blob/master/package.json#L30
[npm]: https://github.com/firebase/angularfire/blob/master/bower.json#L28

**Comment by rwillmer** [comment]
Related to #689

**Comment by jwngr** [comment]
@davideast is going to handle this. I think we should update the Angular deps in the `bower.json` and the `package.json` to `^1.3.0` which will give us `>= 1.3.0` and `< 2.0.0`. If there ever is a `1.6.0`, we will pick it up automatically without having to do a release.
