### ISSUE TITLE
Checking if its a new user.

### ISSUE THREAD

**Issue by amanuel2** [firebase/angularfire#696]
Hey guys. Im trying to check if the user logged in with the twitter popup is new or not. Also trying to get the name of the user. Currently this docs is not working: https://www.firebase.com/docs/web/guide/user-auth.html  . If you go to the storing data section it tells you about newUser. For me that method dosent work properly for me, because when a old user logs in it counts it as a new user... And also getname(authdata) is undefined...  I also want for security to have read  access for twitter AND Google+ ... Currently i only have Twitter  ".read": "auth !== null && auth.provider === 'twitter'"   Please help

**Comment by jwngr** [comment]
Hey there. This isn't the right venue for this type of question. Please ask it over on [StackOverflow](http://stackoverflow.com/) with the #firebase tag or on our [AngularFire Google Group](https://groups.google.com/forum/#!forum/firebase-angular).

**Comment by amanuel2** [comment]
I asked on stackoverflow here: http://stackoverflow.com/questions/35347858/check-for-new-user

But i still dont understand how the docs are not right here: https://www.firebase.com/docs/web/guide/user-auth.html  

Where it tells me to make a variable called isNewUser and then just do if(isNewUser)... But that dosent work as explained on stackoverflow
