### ISSUE TITLE
Offline support for AngularFire/Cordova

### ISSUE THREAD

**Issue by yustein** [firebase/angularfire#697]
Hi everyone,

Does anyone know if/when there will be offline sync capabilities for AngularFire/Cordova?

Kind regards,
Tony

**Comment by jwngr** [comment]
The web SDK already handle temporary offline scenarios, but as mentioned in https://github.com/firebase/angularfire/issues/31 (give that issue a read), full offline support for our JS SDK is not yet here. We only have that for our mobile (iOS and Android) SDKs. We don't have a release date on when it will land for the JS SDK.
