### ISSUE TITLE
Update the docs - $routeChangeError vs $stateChangeError (in ui-router)

### ISSUE THREAD

**Issue by stefek99** [firebase/angularfire#709]
https://www.firebase.com/docs/web/libraries/angular/guide/user-auth.html

>  Both of these methods work well with the resolve() methods of ngRoute and ui-router.

Apparently, when using ```ui-router``` the ```$routeChangeError``` should be ```$stateChangeError```

```
app.run(["$rootScope", "$location", function($rootScope, $location) {
$rootScope.$on("$routeChangeError", function(event, next, previous, error) {
  // We can catch the error thrown when the $requireAuth promise is rejected
  // and redirect the user back to the home page
  if (error === "AUTH_REQUIRED") {
    $location.path("/home");
  }
});
}]);
```

I'm not the routing expert and it took me a while to figure out why the code wasn't executed - it was name of the event that was wrong.

Example plunker: https://plnkr.co/edit/JSRCuerEpr2JKvQtmaQ2?p=preview

**Comment by jwngr** [comment]
The docs are correct in that the sentence you reference (and the paragraph that precedes it) are referring to the `$waitForAuth()` and `$requireAuth` methods, not `$routeChangeError` and `$stateChangeError`. Note that we have full code samples for both ngRoute and ui-router right below that sentence. It correctly uses `$routeChangeError` for ngRoute and `$stateChangeError` for ui-router. You can switch between them by clicking on the buttons at the top of the code sample. We will see if we can make things less confusing though.

**Comment by stefek99** [comment]
Magic!

Didn't notice that:
![image](https://cloud.githubusercontent.com/assets/249703/14891078/173daafe-0d5d-11e6-94c3-5f635ded1040.png)

Many WOW.
