### ISSUE TITLE
Debounce update in three-way-binding

### ISSUE THREAD

**Issue by R-Kurbatovvakoms** [firebase/angularfire#710]
Hi.

We're using Firebase for basic chat implementation and having problem with UI performance during high load. When multiple users are sending their messages watchers update UI with almost every sent message which is quite expensive. We solved the problem by reducing number of shown messages, copying only subset of them to show and using lo-dash debounce function to proceeding messages only once per second but that ruins completely the whole idea of three way binding. 

So Is it possible to set a kind of debounce delay during creation of AngularObject so it aggregated all updates from server during that period?

**Comment by katowulf** [comment]
three-way-binding is a function of $firebaseObject. The docs make it clear that this is intended to sync simple hashes (key value  pairs) and not complex nested structures or collections. Use $firebaseArray for collections and call $save(). If this doesn't answer the question, then provide a minimal repro demonstrating the issue or submit a PR with a failing test case that covers the desired behavior and we'll discuss.
