### ISSUE TITLE
MockFirebase and authWithPassword() does not trigger an error?

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#712]
(copied from another post on behalf of @liveakshay) 

Ok, I have a similar problem with testing $authWithPassword.  The catch block of my $authWithPassword never gets invoked!  Despite using failNext and flush.  Please help. 

Here is my controller and test spec. 

login.js
```
function LoginController(FIREBASE_URL, $scope, $location, $log, $firebaseAuth, $firebaseObject, $firebaseArray) {

	function login() {
		console.log('authenticateUser', vm.email, vm.password);
		return vm.auth.$authWithPassword({
			email: vm.email,
			password: vm.password
		}).then(function(authData) {
			vm.user = global.userObj = $firebaseObject(global.ref.child(vm.getLoggedInUserID()));
			_setupUser(authData);
			var msg = "Logged in successfully, as user ";
			if(vm.user.isAdmin)
				msg = msg + "and administrator ";
			msg = msg + vm.email + "!";
			vm.success(msg);
			return authData;
		}).catch(function(error) {
			vm.err("* Authentication failed! ", error);
			return error;
		});
	}
}
```

Test Spec
```
'use strict';

describe('Controller: LoginCtrl', function () {

	// load the controller's module
	beforeEach(module('joggerApp'));

	var LoginCtrl, $scope, ref, $log;

	// Initialize the controller and a mock scope
	beforeEach(
		inject(function ($controller, $rootScope) {
			MockFirebase.override();
			$scope = $rootScope.$new();
			LoginCtrl = $controller('LoginCtrl', {
				$scope: $scope
			});
			ref = $scope.global.ref;
			// ref.autoFlush(true);
		})
	);

	it('should fail auth with wrong login email/password', function() {
		$scope.vm.email = "IKnowThisEmailDoesntExist@email.com";
		$scope.vm.password = "NO_WAY_THIS_IS_EVER_A_PASSWORD";
		ref.failNext('authWithPassword', new Error('does it matter?'));
		LoginCtrl.login().then(function(){
			expect($scope.global.errorMessage).toMatch('/* Authentication failed!/');
			console.log('YAY!!!');
			expect($scope.global.successMessage).toBeNull();
			console.log('YAY!!!');
			expect($scope.vm.user).toBeNull();
			console.log('YAY!!!');
		});
		ref.flush();
	});
});

```

**Comment by katowulf** [comment]
Please determine if the error still occurs when you remove MockFirebase from the picture? If not, then this would be a bug with the MockFirebase lib. Reduce this to the smallest amount of code that still reproduces the error, in order to isolate the error to the correct lib, and create a new issue so these aren't confused.

**Comment by liveakshay** [comment]
I removed MockFirebase entirely.  Still doesn't trigger my catch block (and yes, I don't have a user with that username/password in my firebase DB).

I guess at this point I am just looking for help writing a Jasmine test spec that tests a controller that uses angularfire's $authWithPassword.  There are no examples out there!?

**Comment by katowulf** [comment]
Generally speaking, your test units don't need to test the third party lib's functionality. If you want a test unit that tests $authWithPassword(), it's [here](https://github.com/firebase/angularfire/blob/master/tests/unit/FirebaseAuth.spec.js). But if you want to test your own code, the answer would be to a) use an e2e test and run a real auth event or b) mock the $authWithPassword() method. You're not testing $authWithPassword() for bugs, so remove it from the picture.

**Comment by liveakshay** [comment]
I am trying to test that the controller correctly handles a rejected promise (given incorrect auth credentials), and sets the appropriate error message in the model, for the view.  I need the $authWithPassword function to fail, and trigger a rejected promise block in my controller. 

Do I have to write an asynchronous jasmine test for this case (without using MockFirebase)?  Perhaps I can use jasmine spy or spyObject, like you have in the angularFire unit test specs?  Thank you for your continued patience and help.

**Comment by katowulf** [comment]
Doing a bit of housecleaning. MockFirebase is no longer used for tests, and the answer to the question posited here is to use e2e tests for auth and to mock Firebase services for unit tests using spies. Ping back if more help is needed.
