### ISSUE TITLE
"Invalid record; could determine key for [object Object]" should be "couldn't"

### ISSUE THREAD

**Issue by tdkehoe** [firebase/angularfire#714]
When I use `$save(recordOrIndex)`, `$remove(recordOrIndex)`, or `$keyAt(recordOrIndex)` and put an object as the argument I get the error message `Invalid record; could determine key for [object Object]`. Shouldn't that say "couldn't", not "could"?

Or maybe "could" is correct? Records don't have metadata, including keys; but objects include keys and other metadata. If so then the error message could be more clear: `Invalid record; key found in the argument so it's a Firebase object, not a Firebase record. Firebase objects have metadata, Firebase records don't."

While we're on this topic, are there are plans to enable objects as the argument for these methods? Records and objects are almost the same, and it'd be easier to write code if I could use objects.

**Comment by katowulf** [comment]
PR's welcome for the spelling error. What do you mean by objects vs records? You can't save, remove, or find something arbitrary; it has to be an actual record in the database which has been synchronized locally.

**Comment by tdkehoe** [comment]
Firebase records are the keys and values of an object, i.e., a JavaScript object. Firebase objects also include metadata, including `$$conf`, `$id`, and `$priority`. You can't use a Firebase object as the argument for `$save(recordOrIndex)`, `$remove(recordOrIndex)`, or `$keyAt(recordOrIndex)`.

**Comment by katowulf** [comment]
Sorry, I don't have any idea what this means. Please provide a minimal repro demonstrating.

**Comment by tdkehoe** [comment]
A _record_ and an _object_ are not the same. You can't use objects as arguments for `recordOrIndex`.

```js
var ref = new Firebase("https://crudiest-firebase.firebaseio.com/");

$scope.movies = $firebaseArray(ref); // get movies array

$scope.movie = $firebaseObject(ref.child($routeParams.id)); // get movie object

$scope.movie.$loaded().then(function() {
  console.log($scope.movie); // d {$$conf: Object, $id: "-KHQMGal4h1HuME3dcLQ", $priority: null, movieActors: "Lilla Labanc, Kinga Czifra, Ádám Csernóczki, Attila Jankóczky", movieAwards: "N/A"…}
  var record = $scope.movies.$getRecord($scope.movie.$id);
  console.log(record); // Object {movieActors: "Lilla Labanc, Kinga Czifra, Ádám Csernóczki, Attila Jankóczky", movieAwards: "N/A", movieCountry: "Hungary", movieDateAdded: 1462895450585, movieDirector: "Gábor Forgács"…}
  console.log(record === $scope.movie) // false
});
```

![Record vs. Object](https://github.com/tdkehoe/Firebase-Tutorial/blob/master/media/crudfb_record_object.png)

The record and the movie object are identical except that the movie object has a `$$conf` property.

The _object_ includes a `$$conf` object.

The _record_ is the keys and values of the object, i.e., the regular ol' JavaScript object without metadata.

**Comment by katowulf** [comment]
Yeah, that's not supported. Sorry. Note that it's also superfluous to synchronize using $firebaseObject when the data is already synchronized by the array.

**Comment by tdkehoe** [comment]
What are these things called:

```js
$scope.movies = $firebaseArray(ref);
```

Array access link? Data synchronization link?

**Comment by tdkehoe** [comment]
Are you saying that it's suboptimal to put more than one of those things into a controller, e.g., 

```js
// Access all movies in array
$scope.movies = $firebaseArray(ref);

// Set up single movie object
$scope.movie = $firebaseObject(ref.child($routeParams.id));

// Set up comments array
$scope.comments = $firebaseArray(ref.child($routeParams.id).child('movieComments'));

// Set up single comment
$scope.comment = $firebaseObject(ref.child($routeParams.id).child('comments').child(commentID));
```

I thought it's best practice to write one of those things for every array or object that the controller uses. If you only link to the top level array you'd have to use dot notation to access the nested objects and arrays, and Firebase methods don't work with dot notation (they only work with child notation).

**Comment by katowulf** [comment]
Best practice is whatever works best for reading the data later. What you have here probably won't scale well if the comments get into the thousands (you won't be able to get a list of movies without loading every comment in the database), and generally speaking, you may want to [flatten](https://www.firebase.com/docs/web/guide/structuring-data.html#section-flatten).

`$scope.movies = $firebaseArray(ref);` already downloads and synchronizes all the other data you've set up additional listeners to sync. Neither is wrong, just redundant and a bit more resource intensive. Regardless of what approach you choose, you can't interchange the records for other synchronized objects/arrays. 

On NoSQL JSON data structures:
https://www.firebase.com/docs/web/guide/structuring-data.html
https://highlyscalable.wordpress.com/2012/03/01/nosql-data-modeling-techniques/
https://groups.google.com/forum/#!topic/firebase-talk/1p4O4Pc2w6k (data structure optimization)
http://stackoverflow.com/questions/30693785/how-to-write-denormalized-data-in-firebase/30699277#30699277
https://www.firebase.com/blog/2013-04-12-denormalizing-is-normal.html
http://stackoverflow.com/questions/32480615/firebase-data-structure-advice-required
