### ISSUE TITLE
Provide newValue and oldValue on the child_changed event to align with typical AngularJS behavior

### ISSUE THREAD

**Issue by douglasg14b** [firebase/angularfire#715]
The default behavior of AngularJS is to provide a `newValue` and `oldValue` on a `$watch` call. This information is usually very handy when the developer needs to take action depending on what values changed, and what they changed from.

**Comment by douglasg14b** [comment]
I implemented something of the sort here: https://github.com/douglasg14b/angularfire/commit/5579a3e7bed2e06ee21ff1ca105eb83a7a19f42f

However, it looks like the promise returned from `$firebaseUtils.doSet` call in `$save` cannot receive a snapshot. Even though the `updated` function does. It was pretty hard debugging through that as the firebase web-client source is obfuscated, would be nice if it wasn't...

**Comment by katowulf** [comment]
Seems like this would do the trick: https://gist.github.com/katowulf/936c596071f098738e0695114323ff08

I don't really want to change the default behavior, considering that it matches the underlying API, nor do I want to encourage people to use $watch() for more than very simple ops like calling .sort() on a custom sorted collection. Almost all cases where $watch or $loaded are used should be replaced by using $extend (chance are this is one of them; you shouldn't need to know the values in $watch; you should just use $extend and modify in the data as needed).
