### ISSUE TITLE
Misbahave when apply Firebase's rule?

### ISSUE THREAD

**Issue by MarcusEdward** [firebase/angularfire#716]
My firebase database look like this:
```
{
  "test": {
    "a": "constant",
    "b": "change this"
  }
}
```
This is my rules to prevent users from altering "test123" object's structure, defined in Dashboard:
```
{
  "rules": {
    ".read": true,
    
    "test": {
      ".write": true,
      ".validate": "newData.hasChildren(['a', 'b'])",
      
      "b": {
        ".validate": "newData.isString()"
      },
      
      "$any": {
        ".validate": false
      }
    }
  }
}
```

<br/>**Using Firebase**: it behave like what I understand from reading security & rules docs:
```
var ref = new Firebase(url);
ref.child("test").set("Change test object to string"); //re-creating fail
ref.child("test/a").set("change a"); //updating 'a' fail
ref.child("test/b").set("change b 1"); //updating 'b' success
ref.child("test/b").set({ "value": "change b 2" }); //updating 'b' fail
ref.child("test").set({ "a": "contant", "b": "change b 3" }); // updating 'b' fail
ref.child("test/c").set("Add c"); //adding fail
```
Result:
![image](https://cloud.githubusercontent.com/assets/15854904/15285395/05905acc-1b81-11e6-8857-f5be67ca1215.png)
Console's errors:
![image](https://cloud.githubusercontent.com/assets/15854904/15285371/e725ae70-1b80-11e6-805f-4b0aebc0423c.png)

<br/>**Using Angular Fire**: It misbehave and in some case, it even delete my firebase database
```
var ref = new Firebase(url);
$firebaseObject(ref.child("test")).$bindTo($scope, "test");
$scope.test = "Change test object to string"; //re-creating, no fail message and delete the entire "test" object on firebase
$scope.test.a = "change a"; //updating 'a' fail, correct
$scope.test.b = "change b 1"; //updating 'b' fail, misbehave
$scope.test.b = {"value": "change b 2"}; //updating 'b' fail, correct
$scope.test = { "a": "contant", "b": "change b 3" }; //updating 'b', no fail message and delete the entire "test" object on firebase 
$scope.test.c = "Add c"; //adding fail, correct
```
Cannot show the proper result screen of this case, I suggest reading my comment for more informantion

<br/> Can anyone explain to me why this happen?
A solution will be appreciated :smiley:

**Comment by katowulf** [comment]
I can't really understand what you're doing here with pseudo code. Presumably you're not really doing $scope.test = "..."; synchronously, right after calling $bindTo() (which is an asynchronous operation) and then changing the value 4-5 times synchronously? 

I also don't understand the goal here. Why are we setting the value to a string and then setting properties on the string as if it were an object? Trying to use $bindTo and primitive values is not going to work like this.

I'm also having trouble believing that the Firebase commands you described above worked. test/b would have also failed, among other tests there. So I really don't understand what you're saying here.

**Comment by MarcusEdward** [comment]
I mention my goal above: "prevent users from altering 'test' object's structure"
To be more specific:
+ You're not allowed to change "test" object to primitive type
+ You're not allowed to change value of "a"
+ You're not allowed to add more attribute to "test"
+ You're allowed to change "b" value, but only string is accepted

<br/>**Using Firebase**: these easy to test so I run them synchronously

<br/>**Using AngularFire**: Every action there I make a button, so it run asynchronously and the result is in the comment right next to every action.

<br/> You said that my Firebase code for test/b is failed. I have tested it independently so yeah, I sure it works. I read docs about Rules and tested carefully.

<br/>The action order in the two way are corresponding. I will explain more:
- 1st action: Test whether we can change the entire "test" object to a string or not
- 2nd action: Test whether we can change "a" value or not
- 3rd action: Test whether we can change "b" value the normal way or not
- 4th action: Test whether we can change "b" value to another type or not (in this case, I want to change "b" to an object)
- 5th action: Test whether we can change "b" value by setting the entire "test" object or not (as you see, "a" value still the same)
- 6th action: Test whether we can add more attribute to "test" object or not
