### ISSUE TITLE
Version 1.3.0 not available on CDN

### ISSUE THREAD

**Issue by betfun** [firebase/angularfire#720]
Hello,

trying to use the CDN version as described in doc: 
`<script src="https://www.gstatic.com/firebasejs/3.0.0/firebase.js"></script>
`
but I have a "Not found" error.

**Comment by jwngr** [comment]
Try going to [that URL](https://www.gstatic.com/firebasejs/3.0.0/firebase.js) in your web browser. It should be correct. In order for this to be actionable, you would need to provide a repro of the issue via a Plunker or JSFiddle.

**Comment by betfun** [comment]
Sorry I meant: 
```
<!-- AngularFire -->
<script src="https://cdn.firebase.com/libs/angularfire/1.3.0/angularfire.min.js"></script>
```

**Comment by jwngr** [comment]
Version `1.3.0` of this library does not exist. [The latest version is `1.2.0`](https://github.com/firebase/angularfire/releases). Try using `"https://cdn.firebase.com/libs/angularfire/1.2.0/angularfire.min.js"`.
