### ISSUE TITLE
CDN not working for version 2.0.0

### ISSUE THREAD

**Issue by kapoorji** [firebase/angularfire#721]
Unable to access latest angularfire version as I need to use firebase 3.0,
https://cdn.firebase.com/libs/angularfire/2.0.0/angularfire.min.js

I did try npm install it, but the library there is v1.2. Is it still planned? As the link in description shows, the latest version is hosted.

**Comment by BenDz** [comment]
Angularfire 2.x is not yet released. A PR is in progress regarding this: [717](https://github.com/firebase/angularfire/pull/717).

**Comment by jwngr** [comment]
Closing in favor of #717 which is already tracking the upgrade to the latest version of the Firebase SDK. We are working through some details in getting this update out. Hoping to get it out tomorrow.
