### ISSUE TITLE
Link to 2.0.0 is broken...

### ISSUE THREAD

**Issue by wbhob** [firebase/angularfire#724]
When I go to https://cdn.firebase.com/libs/angularfire/2.0.0/angularfire.min.js, it simply returns a 404 Not Found message.

**Comment by cakdityo** [comment]
I think because it has not released yet.

**Comment by wbhob** [comment]
Then why are the docs already available, and why didn't they release them together?

**Comment by jwngr** [comment]
Can someone please refer me to the doc that you are talking about? @cakdityo is correct that `2.0.0` has not yet been released and is being tracked in #718.

**Comment by cholathit** [comment]
This is the doc @wbhob was talking about. I get 404 when I tried to follow this doc as well.
https://github.com/firebase/angularfire/blob/2.0/docs/quickstart.md

**Comment by jwngr** [comment]
That is in a non-`master` branch which has not yet been merged which is creating the package that will actually get shipped at 2.0. So yes, it doesn't work yet, but will by the time that code is merged.
