### ISSUE TITLE
404 Error for AngularFire 2.0 CDN Source

### ISSUE THREAD

**Issue by tysonthomas9** [firebase/angularfire#728]
I'm getting a 404 Error while using this source for AngularFire 2.0 https://cdn.firebase.com/libs/angularfire/2.0.0/angularfire.min.js

Also i'm getting an error 'No tag found that was able to satisfy ~2.0.0' when i set AngularFire 2.0.0 in bower.json and run 'bower install'

**Comment by jwngr** [comment]
Dupe of #724.
