### ISSUE TITLE
Firebase Notifications available?

### ISSUE THREAD

**Issue by amanuel2** [firebase/angularfire#729]
I was just asking if i could implement this awesome feature for my project witch uses older version like 2.4.3. 

Project : https://github.com/amanuel2/ng-forum

**Comment by jwngr** [comment]
Firebase Notifications does not have a web API, so upgrading to the latest `3.x.x` SDK won't allow you to use them from your Angular app anymore than the `2.x.x` would.

Also, the upgrade to the `3.x.x` SDK is being tracked in #717 and is coming soon.

**Comment by amanuel2** [comment]
Oh sorry for trouble @jwngr  i thought there was a web thing, for notifications.
