### ISSUE TITLE
$createUser throws error "provider is not enabled"

### ISSUE THREAD

**Issue by hash1492** [firebase/angularfire#730]
Hi, 
I am trying to use Firebase authentication using the "email/password" provider. Here are the steps I followed:
1. I created a new firebase in the console
2. In the "Auth" section and "Sign in method" tab, I enabled "email/password" provider.
3. Here is my code for creating a firebase user

```
var ref = new Firebase("https://myfirebase-7529f.firebaseio.com");

  var authObj = $firebaseAuth(ref);

  $scope.register = function() {
    authObj.$createUser({
      email: $scope.user.email,
      password: $scope.user.password
    })
    .then(function(userData) {
      console.log(userData);
    })
    .catch(function(error) {
      console.error("Error: ", error);
    });
```
When the register method is called, it throws this error in the console:

``` 
Error:  Error: The specified authentication provider is not enabled for this Firebase
```

The same error is thrown when I use the $authWithPassword() method for logging in a create that I manually created using the firebase console.
But as I said above, I have already enabled the "email/password" provider in the firebase console. Am I missing anything.

Thanks

**Comment by CyrusZei** [comment]
The problem is that you have activated the auth in firebase.google.com(firebase 3.0), but your script tag is looking at the firebase legacy(old, not working since 18 of may)

They are working on the angularfire 2.0 that are using the firebase 3.0.
They hope to launch this week if everything works out

**Comment by hash1492** [comment]
@CyrusZei Thanks a lot for the quick reply. 

I created a new firebase app using the legacy console, enabled "email/password" provider there, and used my existing code. And everything works fine now.

Thanks again.
