### ISSUE TITLE
Clean up test suite from 3.x.x upgrade

### ISSUE THREAD

**Issue by jwngr** [firebase/angularfire#734]
As part of merging in #717 to upgrade to the Firebase `3.x.x` SDK, we made a lot of testing changes and the test suite is now pretty unstable and does not pass in Travis. We need to clean things up in general and specifically focus on:
  1. Defining a better [`tick()`](https://github.com/firebase/angularfire/blob/38b0e9a969414fdd9021abc11085ab1c22bf8204/tests/unit/utils.spec.js#L42-L48) method to force the digest loop to update.
  2. Make sure our promise chains are set up properly and that we are waiting for things properly. For example, [this test](https://github.com/firebase/angularfire/blob/38b0e9a969414fdd9021abc11085ab1c22bf8204/tests/unit/utils.spec.js#L364) does not wait for the Firebase `set()` to complete.
  3. Make sure the e2e tests actually pass (e.g. the Todo app has two failing tests).

**Comment by juan-orca** [comment]
sounds good!!

**Comment by CyrusZei** [comment]
did you guys just finished the angularfire 2.0 ? I see that the version is 2.0 now ?

**Comment by jwngr** [comment]
Yes, version 2.0.0 of AngularFire has been released and you can see the change log [here](https://github.com/firebase/angularfire/releases/tag/v2.0.0). This bug is tracking the build failures. We wanted to get the release out instead of waiting for us to tackle all the build failures which seemed more like testing issues than actual code issues.

**Comment by abehaskins** [comment]
See #740 for first batch of improvements

**Comment by jwngr** [comment]
@abehaskins - I think we can close this one now that the tests are fast and run reliably. Please re-open if there was anything else you meant to do.
