### ISSUE TITLE
Cannot install AngularFire#2 using bower

### ISSUE THREAD

**Issue by matiishyn** [firebase/angularfire#737]
Hi, guys.

I'm trying to update AngularFire to the new version - #2.0.0
But I cannot get a minified version of it

1. Trying to use your CDN: https://cdn.firebase.com/libs/angularfire/2.0.0/angularfire.min.js but it gives me 404 (Not Found)
2. Trying to download it with Bower but it says that:
```
Additional error details:
Available versions in https://github.com/firebase/angularFire.git: 1.2.0, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0, 0.9.2, 0.9.1, 0.9.0, 0.8.2, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.0, 0.6.0-
pre1, 0.5.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1.0
```

Could you plz take a look

**Comment by jwngr** [comment]
We are literally in the middle of getting the release out. Hang tight for a little longer.
