### ISSUE TITLE
$firebaseAuth promises never resolved

### ISSUE THREAD

**Issue by stormtony** [firebase/angularfire#746]
When using $signInAnonymously or $signInWithEmailAndPassword (I haven't tested other sign in methods), the documentation states those methods return a promise. But this promise is never resolved nor rejected.

Sign in errors only appear in console as Uncaught Errors.

### Version info

**Angular:** 1.5.0

**Firebase:** 3.0.3

**AngularFire:** 2.0.0

### Test case

https://plnkr.co/edit/LDaSAuiV3Kc2KJk5eT7j?p=preview

### Steps to reproduce

Click on "Login"

### Expected behavior

Console should display 
- Signing in ...
- Sign in success

### Actual behavior

Console only displays
- Signing in ...

**Comment by iRoachie** [comment]
Was this issue resolved?

**Comment by smrubin** [comment]
Can confirm this is happening with $createUserWithEmailAndPassword as well.

**Comment by jwngr** [comment]
Thanks for the reports here. I'm taking a look now.

**Comment by iRoachie** [comment]
I think it's all the methods of the $firebaseAuth object, just tried with $sendPasswordResetEmail

**Comment by jwngr** [comment]
Yup, I think you're right. I updated to the issue title to reflect that.

**Comment by jwngr** [comment]
I've got a fix for this already. I'm just updating our tests so that they actually work :/

**Comment by jwngr** [comment]
These should all be fixed in the [`2.0.1` release](https://github.com/firebase/angularfire/releases/tag/v2.0.1) which just went out.

**Comment by chris08002** [comment]
For me .then works but .catch and .finally don't (Angular Fire 2.0.1 and Firebase 3.0.3):

`
  $scope.doLogin = function(user) {
    console.log("do login", user);
    Auth.$signInWithEmailAndPassword(user.email, user.password).then(function(authData) {
      console.log('Logged in successfully as: ', authData.uid);
      $scope.loggedInUser = authData;
      $scope.closeLogin();
    }).catch(function(error) {
      console.log('Error: ', error);
      $scope.loginData.errorMsg = error;
    }).finally(function(xx) {
      console.log("finally", xx);
    });
  };
`

**Comment by iRoachie** [comment]
Your error is that the function isn't being passed a valid argument for password. Check your user.password to see if it's not null and it's a string. Your catch is working, thats why you're seeing the error.

**Comment by chris08002** [comment]
Well i intentionally use a wrong password as a user might do. I'd like to give an error message to the user but it can not be cached.

Or am I missing something?

**Comment by jwngr** [comment]
@chris08002 - Please open up a new issue as the original issue has been resolved. Also, please provide a Plunkr or JSFiddle which has a minimal reproduction of your issue.

FWIW, I think we throw a synchronous error when you pass invalid arguments. You should add code to check the argument is valid before calling the sign in method.
