### ISSUE TITLE
$getAuth() and the documentation

### ISSUE THREAD

**Issue by tgensol** [firebase/angularfire#758]
The doc says that it returns : 

>uid, provider (string identifying the provider), auth (the authentication token payload), and expires (expiration time in seconds since the Unix epoch)

But 

```
var authData = $scope.authObj.$getAuth();
```
authData.uid is okay, but authData.provider and authData.auth are undefined. 

Maybe I do not understand the doc correctly ?

**Comment by katowulf** [comment]
Please resubmit and follow the template appropriately, including version info, steps to repro, and all the other items requested. Happy to help, but we need you to follow the process.

**Comment by jwngr** [comment]
Re-opened as https://github.com/firebase/angularfire/issues/759.
