### ISSUE TITLE
Rename authData variables to firebaseUser

### ISSUE THREAD

**Issue by davideast** [firebase/angularfire#760]
In the docs we refer to the authentication result as the `authData` variable which worked for the old 2.x.x SDK. The object in the 3.0 SDK is named [`firebase.User`.](https://firebase.google.com/docs/reference/js/firebase.User)

I propose we change all instances to `firebaseUser` in the docs to avoid confusion and to show that it's now a new object with different properties.

I'm more than happy to do this myself 😄

**Comment by jwngr** [comment]
Let's do it!

**Comment by jwngr** [comment]
While you are doing this, it would be great to fix #759 and see if there are similar issues with the docs being out of date.

**Comment by jwngr** [comment]
David, I ended up taking this on as part of #763.

**Comment by jwngr** [comment]
Fixed with #763.
