### ISSUE TITLE
Document $firebaseRefProvider

### ISSUE THREAD

**Issue by davideast** [firebase/angularfire#761]
There are currently no docs on how to use the `$firebaseRefProvider`. We are also treating the the `firebase.database.ref()` as a global variable in the docs. 

I propose we create a section documenting `$firebaseRefProvider` and switch to using it in the docs as well.

I'm more than happy to do this 😄

**Comment by jwngr** [comment]
Sounds good to me. FYI that the docs now live on GitHub [here](https://github.com/firebase/angularfire/tree/master/docs). Assigning this one to you.

**Comment by brentahiti** [comment]
Any update on this?

I'm wondering if it would make sense to be able to get refs across several databases? (personally in this case)

**Comment by rissell** [comment]
@davideast Any update on this?

**Comment by davideast** [comment]
@rissell I plan on starting this after #865 is finished. Dealing with Travis issues right now as all the tests pass locally. Hopefully shouldn't be much longer.

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by jamesdaniels** [comment]
Closing as stale.
