### ISSUE TITLE
App named '[DEFAULT]' already exists.

### ISSUE THREAD

**Issue by CyrusZei** [firebase/angularfire#765]
Hi guys,

I wanted to upload the site so I ran the command 
`grunt`
and I got this error
`App named '[DEFAULT]' already exists.`

I did look around and found that it has something to do with 
`.config(function(){
    var config = {
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authDomain: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  };
  firebase.initializeApp(config);`

I have this config in angular app.js

### Version info

**Angular:** 1.5.6

**Firebase:** 3.03

**AngularFire:** 2.0

**Other (e.g. Node, browser, operating system) (if applicable):**

### Steps to reproduce

I used
1.yo angular generator
2.added the .config in app.js
3.then ran the command "grunt"

**Comment by iRoachie** [comment]
I'm unable to replicate this error. I used the same steps and the app works perfect for me.

**Comment by CyrusZei** [comment]
did you add the .config in the app.js also ?

**Comment by iRoachie** [comment]
Yes I did. Make sure you add firebase to your list of modules. `angular
  .module('generatorApp', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngRoute',
    'ngSanitize',
    'ngTouch',
    'firebase'
  ])`

**Comment by CyrusZei** [comment]
yupp, i also have the firebase in my modules. I need to look this up why it keep telling me that.

**Comment by jwngr** [comment]
The error you are getting (`App named '[DEFAULT]' already exists.`) means you have called `firebase.initializeApp()` multiple times. You should make sure to only ever call this once.

**Comment by CyrusZei** [comment]
yupp, I noticed that I had that on two places and forgot to remove the other one. 

Tomorrow I will be able to demo for my classmates why they should use firebase and how fun it is 😄 

Thanks for the reply @jwngr and @iRoachie
