### ISSUE TITLE
Error on firebase.User()

### ISSUE THREAD

**Issue by javanese84** [firebase/angularfire#766]
Hi there, 

I'm having issues with firebase in combination with anguarfire. When I try to update the loggedIn User (via Interface firebase.User) I'm getting an error that says that 
`Cannot read property 'apiKey' of undefined`

I'm trying to call it like this:
`var user = firebase.User();`

Isn't the User Interface of firebase 3.0 already supported or did you already hear about this?

The versions I am using are:

- firebase: v3.0.3 (3.0.3-rc.1)

- angualarfire: 2.0.1

Thanks in advance

**Comment by iRoachie** [comment]
I think you may be getting the current user by user the wrong method. The method for getting the current user is `var user = firebase.auth().currentUser;`

Check the docs [here](https://firebase.google.com/docs/auth/web/manage-users#get_the_currently_signed-in_user) for FirebaseAuth.

**Comment by javanese84** [comment]
Hi iRoachie,

thanks for your reply. But my problem is, that I want to access the updateProfile method on firebase.User...
Do you have another idea?

**Comment by iRoachie** [comment]
Is this the same method you mean?

```js
var user = firebase.auth().currentUser;

user.updateProfile({
  displayName: "Jane Q. User",
  photoURL: "https://example.com/jane-q-user/profile.jpg"
}).then(function() {
  // Update successful.
}, function(error) {
  // An error happened.
});
```

**Comment by javanese84** [comment]
Yes, I think that's the same. Unfortunately `firebase.auth().currentUser` gives me _null_ and I' definitely logged in. When I do a console.log with `firebase.auth()` there is an object currentUser. But it seems that I cannot acces it through `firebase.auth().currentUser`

**Comment by javanese84** [comment]
OK, now I have found a solution. I'm now listening in the `$onAuthStateChanged` function for changes and there I can access the object as you wrote above.

Thank you very much, iRoachie!!
