### ISSUE TITLE
firebaseauth not defined, something is wrong here

### ISSUE THREAD

**Issue by CyrusZei** [firebase/angularfire#768]
Hi guys,

Just started a new ionic project that i have for school and after ionic scaffold the project I did this

`bower install angularfire --save`
and I see that it save angularfire in the bower.json file and the same goes for 
`bower install firebase --save`

I inject the firebase in the main app
`angular.module('app', ['ionic', 'app.controllers', 'app.routes', 'app.services', 'app.directives','firebase'])`

and then in my controller
`.controller('popularCtrl', ['$scope', '$firebaseObject', '$firebaseArray', '$firebaseAuth', function($scope, firebaseObject, firebaseArray, firebaseAuth) {`

Then when I want to use the firebaseAuth function
`var authObj = $firebaseAuth();`

it says `$firebaseAuth is not defined`

This is my PR [THL](https://github.com/CyrusZei/thl)

I have looked at the doc and they say that I should do it like that.

and in my app.js I also added the sdk

`angular.module('app', ['ionic', 'app.controllers', 'app.routes', 'app.services', 'app.directives','firebase'])
.config(function(){
  var config = {
    apiKey: "xxxxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxxx",
    databaseURL: "xxxxxxxxxxxxxxx",
    storageBucket: "xxxxxxxxxxxxxxx",
 };
 firebase.initializeApp(config);
})`

Can anyone tell my why this is happening, am I reading the doc wrong or ?

### Version info

**Angular:** 1.5.6

**Firebase:** 3.03

**AngularFire:** 2.

**Other (e.g. Node, browser, operating system) (if applicable):**

**Comment by iRoachie** [comment]
Did you add the script tags from the bower components for the libraries?

**Comment by CyrusZei** [comment]
yes, since I noticed that the bower installs didn't work I added the script tag to the cdn


  <script src="https://www.gstatic.com/firebasejs/3.0.3/firebase.js"></script>

  
  <script src="https://cdn.firebase.com/libs/angularfire/2.0.1/angularfire.min.js"></script>

in the index.html file ,but still no luck

**Comment by iRoachie** [comment]
Did you add those tags before the tag for the app.js?

If still not working, do you have the project on a repo, that we could look and see?

**Comment by CyrusZei** [comment]
yupp, added the script tags before my app.js script tag.

Yes here is a link to my Public repo
https://github.com/CyrusZei/thl

**Comment by iRoachie** [comment]
All you had to do was add the script tags. I have it here working. I'll submit a pr to your repo

**Comment by CyrusZei** [comment]
I just merged it and it worked. well from now on I will only go for the bower script tag links. Thank you so much for you help!

**Comment by katowulf** [comment]
Thanks @CyrusZei 🚀🚀🚀

@iRoachie nice when they turn out to be easy fixes. Have a great day.
