### ISSUE TITLE
Firebase 3 - How to generate Unique ID by push() 

### ISSUE THREAD

**Issue by agumack** [firebase/angularfire#769]
**Angular: 1.5.3**

**Firebase: 3.0**

**AngularFire: 2.0.1**

This is my old method:

```
var ref = new Firebase(AppConstant.FIREBASE_APP_URL);
var appRef = ref.child("apps");
var newAppKey = appRef.push().key();
```

New method?
```
var ref = firebase.database().ref();
var appRef = ref.child("apps");
var newAppKey = **????**
```

**Comment by katowulf** [comment]
There's no AngularFire code here. Not really sure how this relates to the bindings lib.

For an example of the API usage of push(), see [here](https://firebase.google.com/docs/database/web/save-data#update_specific_fields).

**Comment by jwngr** [comment]
`key` is now a read-only property, not a function. So, you would do this:

`var newAppKey = appRef.push().key;`

See [here](https://firebase.google.com/support/guides/firebase-web#no-argument_getters_are_now_read-only_properties_numbered) for the full list of changed methods.
