### ISSUE TITLE
Supporting "Firebase Clould Messaging"

### ISSUE THREAD

**Issue by RezaRahmati** [firebase/angularfire#770]
I am trying to use FCM (Firebase Cloud Messaging) but I couldn't find anything related in angularfire, I am missing something? if I am not, is there any road map for implementing it?

**Comment by davideast** [comment]
@RezaRahmati 

The magic of FCM is that no real API for AngularFire is needed.

The code is in registering the ServiceWorker to receive notifications, which can be done outside of the scope of Angular.

To send a notification, it's just a POST request to FCM.
[
**Check out this tutorial for more info.**](https://developers.google.com/web/fundamentals/getting-started/push-notifications/?hl=en)

**Comment by RezaRahmati** [comment]
@davideast Sorry I get a little confused, the link that you have provided is about GCM (Google cloud messaging), I was asking about FCM (firebase cloud messaging)

**Comment by iRoachie** [comment]
@RezaRahmati It's the same thing. GCM is now FCM. Just rebranded.

**Comment by davideast** [comment]
@RezaRahmati 

What @iRoachie said. GCM is now FCM.

I'm closing this issue but feel free to comment if you still have any questions.

**Comment by vishnu038** [comment]
not able to register a service worker in angular app. where  do i place  firebase-messaging-sw  file in angular app. i have placed it in root level getting errors. how do i load this firebase-messaging-sw js file  I mean how I get GET downloaded  it in Browser. here is the stack over flow link
http://stackoverflow.com/questions/42435028/where-to-put-firebase-messaging-sw-file-in-angular-app/42441183#42441183

**Comment by patrick-sheehan** [comment]
@vishnu038 
Firebase looks for the firebase-messaging-sw.js in the document root for me. 
I think you can change this in the firebase.json file
