### ISSUE TITLE
Bind to other then $scope

### ISSUE THREAD

**Issue by forcewill** [firebase/angularfire#776]
### Version info

**Angular: 1.5.6** 

**Firebase:3.04**

**AngularFire:2.0.1**

The documentation talks about 

       var ref = storageRef.child('/users/' + self.steamId + '/inventories');

        var preferencesRef = storageRef.child('/users/' + self.steamId + '/preferences');
        var syncObject = $firebaseObject(preferencesRef);
        syncObject.$bindTo($scope, "preferences");

Is it possible to bind to the controller itself ?

I tend to use the controllerAs and as such my controllers follow the pattern

controllerAs: 'ctrl'
... in controller function 
self = this;

i would like to bind directly to the controller such as

      var ref = storageRef.child('/users/' + self.steamId + '/inventories');

        var preferencesRef = storageRef.child('/users/' + self.steamId + '/preferences');
        var syncObject = $firebaseObject(preferencesRef);
        syncObject.$bindTo(self, "preferences");

Is this possible i haven't had any success trying out of the box since the bindTo method depends on $scope.$on

**Comment by iRoachie** [comment]
Yea you correctly mentioned it uses $scope.$on event. Which really just calls the obj.$save method. With this in mind we can create our own $scope.$watch and trigger the event.

```js
var vm = this;
var obj = $firebaseObject(firebase.database().ref('test'));
obj.$loaded().then(function() {
 vm.test = obj;
});
  
//watch for changes and call $save on firebaseObject
$scope.$watch(function () {
  return vm.test.$value;
},function(value) {
  me.$save(vm.test);
}, true);
```

**Comment by jwngr** [comment]
Awesome work @iRoachie! Thanks for answering.

Also see https://github.com/firebase/angularfire/issues/441 for someone else asking about this.

**Comment by pziegler** [comment]
Hi, thanks for input but would it be possible to add how to do this for firebaseArray?
I dont use controllerAs but instead directly just use this for everything.
so I thought it might look something like this:
````
var vm = this; //is there no way to skip this part and just use this. ?
var array = $firebaseArray(firebase.database().ref('test'));
array.$loaded().then(function() {
 vm.test = array; //I would like to use this.test=array instead
});
//Right now here I do this.vm = vm..not so nice

//watch for changes and call $save on firebaseArray
$scope.$watch(function () {
  return vm.test;
},function(value) {
  me.$save(vm.test);//this one is confusing, what is me??
}, true);

**Comment by iRoachie** [comment]
The reason we use `var vm = this` is to always have a way to access the main object. Javascript is function scoped, this means that the reference of this is scoped to the current function.

Consider this example
```js
this.test = 'haha';

function boom() {
    this.test = 'nah';
    console.log(this.test);
}

boom(); // outputs 'nah'
console.log(this.test);  // outputs 'haha'
```

This is because the this is scoped to the current function block. So by using `var vm = this` we always have a true reference to the main object.

```js
var vm = this;

vm.test = 'haha';

function boom() {
    vm.test = 'nah';
    console.log(vm.test);
}

boom(); //outputs 'nah'
console.log('outer: ', vm.test); // outputs 'nah'
```

To use 'this' in angular 1, you have to be using controllerAs in either two places.

#### In a state configuration on the router
```js
.state('about', {
    url: '/about',
    templateUrl: 'about.html',
    controller: 'SomeController',
    controllerAs: 'some'
})
```

#### In your template
```html
<div ng-controller='SomeController as some'>
    <p>{{some.$value}} </p>
</div>
```

These are the only two ways you can use 'this' in angular.

**Comment by iRoachie** [comment]
Ohh, you're using ES6 with components. The original question was on binding to a controller so I assumed the same. Well that's another story all together. The me in the `me.$save` is the firebaseArray.

**Comment by pziegler** [comment]
thanks for the reply :) ok, then I think I understand it better
