### ISSUE TITLE
$firebaseAuth().$signInWithCustomToken does not return promise

### ISSUE THREAD

**Issue by tskweres** [firebase/angularfire#782]
I'm implementing passwordless SMS authentication for a hybrid Ionic app. 

After I verify the SMS code I receive a token from the server, then I have this in my controller:

```
$scope.authObj = $firebaseAuth();
      $scope.authObj.$signInWithCustomToken(response.token).then(function(firebaseUser) {
        console.log("Signed in as:", firebaseUser.uid);
        $scope.hideLoading();
      }).catch(function(error) {
        console.error("Authentication failed:", error);
      });
```

I'm using:

```
    <!-- Firebase -->
    <script src="https://www.gstatic.com/firebasejs/3.0.4/firebase.js"></script>

    <!-- AngularFire -->
    <script src="https://cdn.firebase.com/libs/angularfire/2.0.0/angularfire.min.js"></script>
```

The user is created in Firebase, I can see it in my admin console. But I receive no promise, no returned object, then .then() never fires. Any ideas?

**Comment by iRoachie** [comment]
There was a hot fix applied in the next version 2.0.1 of angularfire that fixed returned promises from auth methods.

Similar issue was reported here #782. Just upgrade to the latest release. https://github.com/firebase/angularfire/releases/tag/v2.0.1

**Comment by tskweres** [comment]
works perfectly

**Comment by nikmartin** [comment]
Have the CDN versions been hotfixed? I'm using https://cdn.firebase.com/libs/angularfire/2.0.1/angularfire.min.js and am still not getting any promises returned from $signInWithEmailAndPassword

**Comment by jwngr** [comment]
> Have the CDN versions been hotfixed?

No, CDN versions are not touched once they are deployed. If we need to make a change, we publish a new version.

> [I] am still not getting any promises returned from `$signInWithEmailAndPassword()`.

This is because you are not passing valid inputs into the method, as explained [here](https://github.com/firebase/angularfire/issues/820#issuecomment-235005918). Let's keep the discussion in one place (the other issue) to avoid duplicated work for our team.
