### ISSUE TITLE
$onAuthStateChanged() method signature is incorrect

### ISSUE THREAD

**Issue by jwngr** [firebase/angularfire#783]
### Version info

**Angular:** 1.5.x

**Firebase:** 3.x.x

**AngularFire:** 2.x.x
### Expected behavior

`$onAuthStateChanged()` takes the same three arguments [`onAuthStateChanged()`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged) takes in the regular Firebase SDK:
1. A callback function triggered whenever the auth state changes.
2. A callback function triggered whenever an auth error occurs.
3. A callback function triggered whenever the observer is removed.
### Actual behavior

`$onAuthStateChanged()` takes [two arguments](https://github.com/firebase/angularfire/blob/6adf9cf2f9920ebb7149eb71fcfc54fab70a97ac/src/FirebaseAuth.js#L163):
1. A callback triggered whenever the auth state changes.
2. A `context` object (which is the Firebase `2.x.x` SDK behavior).

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by jamesdaniels** [comment]
Closing as stale.
