### ISSUE TITLE
Document behavior of $ref()--will return a Query

### ISSUE THREAD

**Issue by katowulf** [firebase/angularfire#784]
Per #780, when calling $ref() it returns the original ref used to create the $firebaseArray/$firebaseObject instance. In some cases, this will be the query and not the reference. Would be good to document this distinction as it requires special considerations for [some cases](https://github.com/firebase/angularfire/blob/504383dd3734ba8509dfac72268ce862e9e5a273/src/FirebaseArray.js#L240).

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by jamesdaniels** [comment]
Closing as stale.
