### ISSUE TITLE
$getAuth in $onStateChangeStart dosnt work in the first call

### ISSUE THREAD

**Issue by sirgalleto** [firebase/angularfire#786]
### Version info

**Angular:** ionic 1.2.4

**Firebase:** 3.0.4

**AngularFire:** 2.0.1

**Other (e.g. Node, browser, operating system) (if applicable):**

### Expected behavior

Generaly for manage auth logic permisses I use a ui-router `$onStateChangeStart` event like a middleware when I create redirections if the user have the permissions, like ACL.  

### Actual behavior

When I use `$getAuth()` method in the ui-router `$onStatechangeStart` even on the first call the result is null and I cant create a redirection to another router if the user is logged.

**Comment by katowulf** [comment]
Try using `resolve` with `$waitForAuth()` instead of `$onStateChangeStart`. See recommended practices for [routers with AngularFire](https://github.com/firebase/angularfire/blob/master/docs/guide/user-auth.md#authenticating-with-routers).

**Comment by CyrusZei** [comment]
use resolve in your staate

`resolve: {
            "currentAuth": ["Auth", function(Auth) {
                return Auth.$waitForSignIn();           // it waits for the session and get the UID
            }]
        }`


and then in your controller add the inject the "currentAuth" in your controller to check for the UID and if the UID is null redirect to login state maybe ?
