### ISSUE TITLE
Uncaught TypeError: firebase.goOffline is not a function

### ISSUE THREAD

**Issue by appplumbr** [firebase/angularfire#787]
I'm getting the error when using **firebase.goOffline()** below 

**Error:** 
Uncaught TypeError: firebase.goOffline is not a function

**Ionic lib version**
Ionic, v1.3.1

**Angular JS version**
AngularJS v1.5.3

**Library version includes:**
firebase 3.0.3-rc.1.js
angularfire.min 2.0.1.js

Any help or hint is appreciated, thanks

**Comment by davideast** [comment]
Hey @appplumbr.

You're looking for `firebase.database().goOffline()`. Let me know if that works!

**Comment by appplumbr** [comment]
Thanks @davideast for the update, I did not find this in any of SDK migration docs, please can you also  help me with this one too > Firebase.ServerValue.TIMESTAMP > error is firebase is undefined, should i use > firebase.database().ServerValue.TIMESTAMP ?

**Comment by jwngr** [comment]
Close, it should be [`firebase.database.ServerValue.TIMESTAMP`](https://firebase.google.com/docs/reference/js/firebase.database#.ServerValue).
