### ISSUE TITLE
$save is not updating data and $add works perfectly and adds data to database node

### ISSUE THREAD

**Issue by appplumbr** [firebase/angularfire#788]
Versions used:
**AngularFire 2.0.1**
**Firebase 3.0.3-rc.1**

**$add** is working 
```
var newSync = $firebaseArray(firebase.database().ref("users").child("roles"));
							
newSync.$add({
  key: "value"
});
```

**$save** is not working

```
var newSync = $firebaseArray(firebase.database().ref("users").child("roles"));
							
newSync.$save({
  key: "value"
});
```

$push /$set is not supported

**Comment by jwngr** [comment]
Please use a stable version of Firebase instead of a release candidate (`3.0.5` released yesterday is the latest as of this message). Also, please open a new issue with the issue template filled out completely, including actual versus expected results and a minimal repro in JSFiddle or Plunkr.

**Comment by appplumbr** [comment]
@jwngr Even 3.0.5 seems to be a RC 

https://www.gstatic.com/firebasejs/3.0.5/firebase.js
@license Firebase v3.0.5
Build: 3.0.5-rc.2

Even upgrading doesn't resolve my issue, any help? $save is not working

**Comment by jwngr** [comment]
As noted above, please open up a new issue and follow the issue template, which includes providing a repro and the expected vs. actual results.
