### ISSUE TITLE
Error with $signInWithPopup method on Ionic 1 and Angular 1: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https.

### ISSUE THREAD

**Issue by alexissusset** [firebase/angularfire#794]
After upgrading to Firebase 3 and Angularfire 2.0.1 on an Ionic 1 / Angular 1 application, I am getting the following error when trying to bring an auth popup from firebase (worked with the older methods):
This operation is not supported in the environment this application is running on. "location.protocol" must be http or https.

The method I use is the $signInWithPopup method

Sample code:
```javascript
var provider = new firebase.auth.GoogleAuthProvider();
Auth.$signInWithPopup(provider).then(function(authData) {
    // User successfully logged in
}).catch(function(error) {
    // Login error
});

```

**Comment by jwngr** [comment]
Please follow the error template next time you create an issue.

The popup / redirect sign in methods in Firebase `3.x.x` currently do not support Cordova / Ionic. [See here](https://groups.google.com/forum/#!msg/firebase-talk/mC_MlLNCWnI/cL0OnL4hAwAJ) for more details.

**Comment by spivotron** [comment]
@jwngr Do you know when Cordova / Ionic will support popup / redirect sign in methods in Firebase v3?

**Comment by jwngr** [comment]
Nothing other than is already in that thread. [This is still our answer](https://groups.google.com/d/msg/firebase-talk/mC_MlLNCWnI/uyN7Q-yeBgAJ).

**Comment by epicfaace** [comment]
@jwngr Looks like there isn't a working solution for google signin yet though...

**Comment by jwngr** [comment]
We recently did [some work to get `signInWithPopup()` working in Chrome extensions](https://firebase.google.com/support/release-notes/js#3.7.1), but I don't think that covers the Cordova / Ionic use case. We are working through these issues though. Keep an eye on the [release notes](https://firebase.google.com/support/release-notes/js) for future improvements.
