### ISSUE TITLE
Give option for max debounce in $bindTo

### ISSUE THREAD

**Issue by ericyliu** [firebase/angularfire#800]
Right now, $bindTo automatically `send`s after 500 milliseconds. It would be nice if this was an option when binding. Our application has the user editing an input field and we do not want the change to happen until the user is done typing.

**Comment by katowulf** [comment]
You can skip $bindTo, use Angular's built-in [change](https://docs.angularjs.org/api/ng/directive/ngChange) functions, and trigger your own calls to $save() at any interval or time you prefer. Angular also has built in support for [debounce](https://docs.angularjs.org/api/ng/directive/ngModelOptions) as well, if that's preferred.
