### ISSUE TITLE
Triple Binding with Firebase 3

### ISSUE THREAD

**Issue by ericyliu** [firebase/angularfire#805]
### Version info

**Angular:** 1.5.7

**Firebase:** 3.0.4

**AngularFire:** 2.0.1

**Other (e.g. Node, browser, operating system) (if applicable):**

### Issue

When triple binding with angularfire and firebase 3, when a part of a `$firebaseObject` is changed, the entire `$firebaseObject` is reloaded

### Steps to reproduce

Triple bind a object and set the `ng-model` of a value in the object to an input

### Expected behavior

In firebase 2, it seemed that only the diff was reloaded, as inputs that were triple binded did not lose focus when the value changed

### Actual behavior

Entire object is reloaded

**Comment by jwngr** [comment]
Without a minimal repro in JSFiddle or Plunkr, this is not actionable from our end. Please provide a minimal repro and we will re-open this.
