### ISSUE TITLE
Support ThenableReferences for $add

### ISSUE THREAD

**Issue by davideast** [firebase/angularfire#809]
In the Firebase JS SDK a `DatabaseReference#push` call returns a [`ThenableReference`](https://firebase.google.com/docs/reference/js/firebase.database.ThenableReference) which is a cross of a `Promise` and a `DatabaseReference`.

``` js
const thenableRef = firebase.database().ref().push("item");
console.log(thenableRef.key);
ref.then(_ => console.log('succeeded'));
```

This is useful because not only do you receive they client-side generated `key`, but you also have a way of determining when the operation succeeded.
### AngularFire `$firebaseArray#$add`

In AngularFire `$firebaseArray#$add` is akin to `DatabaseReference#push`. However, we only return a [promise created by `$q`](https://github.com/firebase/angularfire/blob/6ac5a0f7e9d6b05a07ef0fcf7869d5ee896d97b4/src/FirebaseArray.js#L126), which doesn't contain the `key` property.

[**JSBin Demo**](http://jsbin.com/guyodirayi/1/edit?js,console)

``` js

    .controller('MyCtrl', function($scope, $firebaseArray, $firebaseRef) {
      $scope.items = $firebaseArray($firebaseRef.items);
      const ref = $scope.items.$add({ name: 'itemSix' });
      console.log(ref);
      console.log(ref.key); // undefined
    });
```

**I propose we support returning of a `ThenableReference` type object rather than just a promise created from `$q`.**

**Comment by jwngr** [comment]
The only reason the Firebase SDK returns both things is because historically we used a callback and then we added Promises later. I think Promises are the way to go to be honest and am not in favor of this particular proposal. It makes the API more complex and can lead people to thinking `$add()` is synchronous, which it is not. What's the use case that brought this up? That is, what will this enable that the current API does not?

**Comment by davideast** [comment]
Having the key is important when you need to share that key as a relation in the Realtime Database or when integrating with Firebase Storage.

```js
    .controller('MyCtrl', function($scope, $firebaseArray, $firebaseRef, $firebaseStorage) {
      $scope.items = $firebaseArray($firebaseRef.items);
      const promiseWithKey = $scope.items.$add({ name: 'itemSix' });
      
      // create a record based off the key
      const userItemRef = $firebaseRef.userItems.child(promiseWithKey.key);
      $scope.userItems = $firebaseArray(userItemRef);

      // Create a storage ref based off the key
      const storageRef = firebase.storage().ref().child("items").child(promiseWithKey.key);
      const storage = $firebaseStorage(storageRef);
      const task = storage.$put(file);
    });
```

Without this key it makes really difficult to keep track of Realtime Database records that require sharing the generated push-id.

**Comment by jwngr** [comment]
I agree having the key is critical, but the promise is already fulfilled with a ref from which you can get the key:

```
.controller('MyCtrl', function($scope, $firebaseArray, $firebaseRef, $firebaseStorage) {
  $scope.items = $firebaseArray($firebaseRef.items);
  $scope.items.$add({ name: 'itemSix' }).then(function(newRef) {
    // create a record based off the key
    const userItemRef = $firebaseRef.userItems.child(newRef.key);
    $scope.userItems = $firebaseArray(userItemRef);

    // Create a storage ref based off the key
    const storageRef = firebase.storage().ref().child("items").child(newRef.key);
    const storage = $firebaseStorage(storageRef);
    const task = storage.$put(file);
  }).catch(function(error) {
    console.log("Error adding item:", error);
  });
});
```

**Comment by davideast** [comment]
I don't think you should have to resolve an async action to get a key created synchronously. One of the finer points of AngularFire is that it reduces complex async code.

**Comment by jwngr** [comment]
You have a good point. I do think it makes it a bit harder to document if there are two ways to get the key, but if this is purely additive, I will throw my support behind it.

**Comment by davideast** [comment]
Excellent! I do agree it can be confusing, but it can really be helpful when it comes to structuring data.

**Comment by katowulf** [comment]
We could have both by simply adding the key to the thermals return value

On Jul 21, 2016 5:20 AM, "David East" <notifications@github.com> wrote:

I don't think you should have to resolve an async action to get a key
created synchronously. One of the finer points of AngularFire is that it
reduces complex async code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/angularfire/issues/809#issuecomment-234237091>,
or mute the thread

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
