### ISSUE TITLE
Error: authObj.authWithPassword is not a function

### ISSUE THREAD

**Issue by Gajendrasinh** [firebase/angularfire#813]
Hi i am using firebase 3.0.3 ana Angularfir 2.0.1 

i was get this error Error: authObj.authWithPassword is not a function when i m try to login using email and password 

myApp.controller('LoginCtrl', ['$scope' ,'$state', '$firebaseAuth', '$firebaseArray',   function($scope, $state, $firebaseAuth,  $firebaseArray) {

       // var rootRef = firebase.database().ref();

        var authObj = $firebaseAuth();

        $scope.login = function () {
            
            authObj.authWithPassword({
              email    : $scope.loginEmail,
              password : $scope.loginPassword
            }, function(error, authData) {
              if (error) {
                console.log("Login Failed!", error);
              } else {
                console.log("Authenticated successfully with payload:", authData);
                $state.go('home');
              }
            });

        }

        firebaseAuthLogin = function(provider){
            console.log(provider);
            authObj.$authWithOAuthPopup(provider).then(function (authData) {
                console.log("Authenticated successfully with provider " + provider +" with payload:", authData);
            }).catch(function (error) {
                console.error("Authentication failed:", error);
            });
            
        }

        $scope.googleLogin = function () {
           firebaseAuthLogin('google');
        }

}]);

**Comment by jwngr** [comment]
The method is no longer called `authWithPassword()` (it actually was `$authWithPassword()` in the AngularFire `1.x.x` SDK, with a `$`). In the AngularFire `2.x.x` SDK, the method is called [`$signInWithEmailAndPassword()`](https://github.com/firebase/angularfire/blob/master/docs/reference.md#signinwithemailandpasswordemail-password). [Here](https://github.com/firebase/angularfire/blob/master/docs/reference.md#firebaseauth) is the entire API reference for `$firebaseAuth`.
