### ISSUE TITLE
Authentication session persistence

### ISSUE THREAD

**Issue by crossRT** [firebase/angularfire#822]
Angular: 1.4.10
Firebase: 3.1.0
Angularfire: 2.0.2

According to [documentation](https://github.com/firebase/angularfire/blob/master/docs/reference.md#signinwithemailandpasswordemail-password), we can set the authentication session persistence by adding an optional object to the function. But I found that the parameters are not accepted in the source code.

Every time I refresh my angular app, it requires the user to log in again. I thought the authentication session persistence should handle by firebase SDK and angularfire natively?
Please correct me if I'm in the wrong direction to keep authentication session persistence in firebase project.

**Comment by katowulf** [comment]
Hi Rui, Please follow the issue template and resubmit. Be sure to include a repro or failing test case as indicated.
