### ISSUE TITLE
$requireSignIn() with conditional on not anoynmous

### ISSUE THREAD

**Issue by armensg** [firebase/angularfire#825]
$requireSignIn()  seems like a really useful function for resolving states but it seems to fall short in that even if the user is authed as anonymous (which i do for all users by default), i need to implement my own extra logic to resolve promises in the route to check if the user is anonymous or not. Would be really nice feature if we that was build into the function:

`function $requireSIgnIn(bool allowAnonymous)`

thoughts?
Thanks

**Comment by jwngr** [comment]
I don't see why we would want to special case anonymous here. I also think this is fairly simple to do using the existing API by just defining a method called `requireAnonymous()`:

```
function requireAnonymous(Auth, $q) {
  return Auth.$getAuth().then(function(firebaseUser) {
    if (firebaseUser.isAnonymous) {
      return $q.reject("Logged in user is anonymous");
    }
  });
}
```
