### ISSUE TITLE
$firebaseArray $add/$remove doesn't update local copy immediately (angularfire 1.2.0 and earlier)

### ISSUE THREAD

**Issue by jaymanned** [firebase/angularfire#831]
As mentioned in issue [829](https://github.com/firebase/angularfire/issues/829), $firebaseArray.$add and $remove do not update the local array immediately. In case of removing, the deleted item remains in the local $firebaseArray object until its is synced with the db. I've found the bug on angularfire 1.2.0 and earlier.

**Comment by jwngr** [comment]
Re-opening the other issue.
