### ISSUE TITLE
$signInWithPopup 'auth/popup-closed-by-user' error callback takes too many time

### ISSUE THREAD

**Issue by gabrielAnglada** [firebase/angularfire#834]
When user closes oauth popup (google in this case), the error 'auth/popup-closed-by-user' takes too many time to fire.

Thanks!

**Comment by jwngr** [comment]
Closing as invalid since this does not follow the issue template.

**Comment by jwngr** [comment]
Moved to https://github.com/firebase/angularfire/issues/849.
