### ISSUE TITLE
Is necessary authenticate user on $createUserWithEmailAndPassword?

### ISSUE THREAD

**Issue by iKarl** [firebase/angularfire#838]
**Angular:** 1.5.8
**Firebase:** 3.2.1
**AngularFire:** 2.0.1

In that old version of AngularFire: 1.2.0 and Fiberase: <= 2.3.x in the docs say:

> **$createUser(credentials)**
> 
> Creates a new user account using an email / password combination. This function returns a promise that is resolved with an object containing user data about the created user. Currently, the object only contains the created user’s uid.
> 
> and 
> 
> **Note that this function only creates the user. If you wish to log in as the newly created user, call $authWithPassword() after the promise for this method has been fulfilled.**
> 

This is very usefull, because we can tell if we want to log the user or not.

I am developing a system where a privileged user add another user with "$createUserWithEmailAndPassword" it will automatically overwrite the active session for the new user added and automatically logs off the current user.

Another form as I can do this?

**Comment by jwngr** [comment]
This has been discussed on our Google Group [here](https://groups.google.com/forum/#!msg/firebase-talk/zYatdVy1QfU/pDFb9Tk2AAAJ). That thread includes a lot of good information and also explains a workaround that you can use to get the behavior that you want.
