### ISSUE TITLE
$save() on $firebaseObject with undefined properties gives no indication of an error

### ISSUE THREAD

**Issue by wallden** [firebase/angularfire#840]
### Version info

**Angular:** 1.4.3

**Firebase:** 3.2.1

**AngularFire:** 2.0.1

### Test case

Using `$save()` on a `$firebaseObject` containing `undefined` properties does not throw an error and never resolves the promise.

### Steps to reproduce

```
var obj = $firebaseObject({
  writeWillWork: "This works",
  writeWillNotWork: undefined
});
```

Try saving a `$firebaseObject` with `$save()`.

### Expected behavior

Error to be thrown or promise to be resolved with an error like in the Firebase CLI when you try to save an object with undefined properties.

### Actual behavior
Promise never resolves and nothing happens. No indication of an error.

**Comment by katowulf** [comment]
Hi @wallden, the steps to reproduce here are insufficient. Please include code verifying that the error is not surfaced in either the success or error callbacks of the promise, along with some sample data to recreate.

**Comment by jwngr** [comment]
Closing as no repro. [I created a Plunker](https://plnkr.co/edit/BoWmne) which shows that the promise is successfully rejected if you have a key which has a value of `undefined` when calling `$save()`.

Note that in your repro steps, you do:

```
var obj = $firebaseObject({
  writeWillWork: "This works",
  writeWillNotWork: undefined
});
```

which is invalid syntax. You should pass `$firebaseObject` a Firebase ref, not data to be written. Check out my Plunkr or [the AngularFire quickstart](https://github.com/firebase/angularfire/blob/master/docs/quickstart.md#4-inject-the-angularfire-services) to see how this is supposed to actually work.
