### ISSUE TITLE
displayName and photoURL are empty using firebase.auth().currentUser

### ISSUE THREAD

**Issue by jdnichollsc** [firebase/angularfire#843]
### Version info

**Angular:** 1.5

**Firebase:** 3

**Other (e.g. Node, browser, operating system) (if applicable):** Cordova 4

### Test case

Currently I'm debugging using **GapDebug**, you can see the issue http://screencast.com/t/EG54B0vljY
Check my code example: https://gist.github.com/jdnichollsc/17bae6581d405321937fe433410172c9

### Steps to reproduce

- Get a token from Google with the **profile** scope, for example using [$cordovaOauth](https://github.com/nraboy/ng-cordova-oauth) plugin
- Authenticate the user using the method **firebase.auth().signInWithCredential**

### Expected behavior

Get the user info, like the name and the image from Google.

### Actual behavior

displayName and photoURL are empty.

Thanks for all, Nicholls

**Comment by katowulf** [comment]
@jdnichollsc I don't see any usage of the AngularFire libs in your code sample. It looks like you're working directly with the Firebase SDK.

**Comment by katowulf** [comment]
Having said that, I wonder if you can reproduce this behavior without Ionic involved in the process? That seems like a great place to begin binary sorting the possibilities.

**Comment by jwngr** [comment]
@alfongj - Any insight here you can add? Is this the expected behavior of the underlying Firebase SDK?

I agree with Kato that this has nothing to do with AngularFire, so this is not the right place for this. If you wouldn't mind moving this to the [Firebase Google Group](https://groups.google.com/forum/#!forum/firebase-talk), that would be appreciated.

**Comment by alfongj** [comment]
From what I am reading [here](https://gist.github.com/jdnichollsc/17bae6581d405321937fe433410172c9) this may be an issue with $cordovaOAuth not passing scopes correctly.

@jdnichollsc Do you see this behavior occur independently of the Google account and Firebase project used?

**Comment by jdnichollsc** [comment]
thanks Guys, this issue is related with $cordovaOAuth. Sorry for this and have a good day! :dancers:
