### ISSUE TITLE
angularfire 2 UNMET PEER DEPENDENCY 

### ISSUE THREAD

**Issue by gencoder25** [firebase/angularfire#844]
I am getting that error when trying to run "npm install angularfire2 firebase --save"

please, help ...
![capture1](https://cloud.githubusercontent.com/assets/19807799/17728571/0904bb2e-648a-11e6-9ebf-a7c39016c9ba.PNG)

**Comment by jwngr** [comment]
You should report this in the [AngularFire2 repo](https://github.com/angular/angularfire2). This repo is for the AngularFire library compatible with Angular 1.

**Comment by gencoder25** [comment]
thanks for advise
