### ISSUE TITLE
Issue resolving if the user is logged in?

### ISSUE THREAD

**Issue by gopchi** [firebase/angularfire#877]
Hi, 
I am new to Angular, but started a project and wanted to make just a simple app with 2 routes. 
A "/" route with a Facebook login button and then on successful login to redirect to "/app"route. I followed and even copied the code from the Angularfire documentation on Authentication with routers but Angular is giving me the following error "Unknown provider: currentAuthProvider <-"

Here is my app.js source code:

`var app = angular.module('offerel', ['ngRoute', 'firebase', 'angularUtils.directives.dirPagination']);

  var config = {
      apiKey: "--not--shown--on-purpose",
      authDomain: "--not--shown--on-purpose",
      databaseURL: "--not--shown--on-purpose",
      storageBucket: "--not--shown--on-purpose",
      messagingSenderId: "--not--shown--on-purpose"
  };

  firebase.initializeApp(config);
// for ngRoute
app.run(["$rootScope", "$location", function($rootScope, $location) {
  $rootScope.$on("$routeChangeError", function(event, next, previous, error) {
    // We can catch the error thrown when the $requireSignIn promise is rejected
    // and redirect the user back to the home page
    if (error === "AUTH_REQUIRED") {
      $location.path("/");
    }
  });
}]);

app.config(["$routeProvider", function($routeProvider) {
  $routeProvider.when("/", {
    // the rest is the same for ui-router and ngRoute...
    controller: "homeCtrl",
    templateUrl: "views/home.html",
    resolve: {
      // controller will not be loaded until $waitForSignIn resolves
      // Auth refers to our $firebaseAuth wrapper in the factory below
      "currentAuth": ["Auth", function(Auth) {
        // $waitForSignIn returns a promise so the resolve waits for it to complete
        return Auth.$waitForSignIn();
      }]
    }
  }).when("/app", {
    // the rest is the same for ui-router and ngRoute...
    controller: "appCtrl",
    templateUrl: "views/app.html",
    resolve: {
      // controller will not be loaded until $requireSignIn resolves
      // Auth refers to our $firebaseAuth wrapper in the factory below
      "currentAuth": ["Auth", function(Auth) {
        // $requireSignIn returns a promise so the resolve waits for it to complete
        // If the promise is rejected, it will throw a $stateChangeError (see above)
        return Auth.$requireSignIn();
      }]
    }
  });
}]);

app.controller("homeCtrl", ["currentAuth", function(currentAuth) {
  // currentAuth (provided by resolve) will contain the
  // authenticated user or null if not signed in
}]);

app.controller("appCtrl", ["currentAuth", function(currentAuth) {
  // currentAuth (provided by resolve) will contain the
  // authenticated user or null if not signed in
}]);

app.factory("Auth", ["$firebaseAuth", function($firebaseAuth) {
    return $firebaseAuth();
  }
]);`

I would be happy if anyone help me with this issue. 

Thanks!

**Comment by jwngr** [comment]
Closing as invalid since it does not follow the issue template. Please open a new issue with the issue template filled out, including versioning information and a JSFiddle or Plunkr with a repro.
