### ISSUE TITLE
Adding scope to signInWithPopup

### ISSUE THREAD

**Issue by Nicolazinho** [firebase/angularfire#894]
Hi Firebase team,

Any idea how I can add scope to receive special permissions (eg. _user_location_) with `$signInWithPopup`? It seems that the service is not accepting any other parameters.

I am looking to use the [Javascript FacebookAuthProvider addScope](https://firebase.google.com/docs/reference/js/firebase.auth.FacebookAuthProvider#addScope) for Angularfire.

Thanks

**Comment by sjashwin** [comment]
Create a new FacebookAuthProvider with the scope added and pass the provider to the $signInWithPopup() as a parameter. The documentation says you can pass providers also as parameter.

**Comment by jwngr** [comment]
I added an example of how to do this using AngularFire with https://github.com/firebase/angularfire/pull/896. It should get merged in shortly.

For your Facebook example, your code will look something like this:

```js
var provider = new firebase.auth.FacebookAuthProvider();
provider.addScope("user_location");

$scope.authObj.$signInWithPopup(provider).then(function(result) {
  console.log("Signed in as:", result.user.uid);
}).catch(function(error) {
  console.error("Authentication failed:", error);
});
```

**Comment by isaadabbasi** [comment]
@jwngr Whenever i add a provider for example (provider.addScope('id,name,posts') OR provider.addScope('posts') )
facebook gives an error like "Sorry, something went wrong. we're working on getting this fixed as soon as we can"
