### ISSUE TITLE
Add loading indicator in signInWithPopup popup's background.

### ISSUE THREAD

**Issue by ofabricio** [firebase/angularfire#895]
It would be nice a loading indicator in the `signInWithPopup` popup's background (while loading the content), because the blank background sometimes gives the impression it is freezed.

**Comment by jwngr** [comment]
AngularFire doesn't concern itself with the UI of your app. You can accomplish this kind of thing yourself by doing something like this:

**JavaScript**
```js
$scope.loading = true;
$scope.authObj.$signInWithPopup("google").then(function(result) {
  $scope.loading = false;
  console.log("Signed in as:", result.user.uid);
}).catch(function(error) {
  $scope.loading = false;
  console.error("Authentication failed:", error);
});
```

**HTML**
```html
<div ng-if="loading">
   <!-- Show loading indicator -->
</div>

<div ng-if="!loading">
     <!-- Show loaded content -->
</div>
```

**Comment by ofabricio** [comment]
How, as it opens up a popup (new window) that has nothing to do with my app?

**Comment by jwngr** [comment]
Sorry, I misinterpreted what you were referring to. I've forwarded this feedback on to the auth team. Thanks for the feedback.
