### ISSUE TITLE
NaNirebaseStorageProvider issue

### ISSUE THREAD

**Issue by fallais** [firebase/angularfire#900]
Hello,

I'm getting this issue when trying to use $firebaseStorage : `Unknown provider: NaNirebaseStorageProvider <- $firebaseStorage <- ProfilesCtrl`

**Comment by jwngr** [comment]
The new Firebase Storage service has been merged into `master` but has not yet been shipped. David is working on the docs for it and then we will cut a new release so you can play around with it.
