### ISSUE TITLE
Adding $updateProfile methods

### ISSUE THREAD

**Issue by douglaszaltron** [firebase/angularfire#906]
Adding the ability to update a profile to a new displayName or photoURL.

User Management

$updateProfile(context)

Sample:

$scope.authObj.$updateProfile({displayName : "displayName"}).then(function() {
  console.log("Updated profile change successfully!");
}).catch(function(error) {
  console.error("Error: ", error);
});

@davideast @jwngr

**Comment by jwngr** [comment]
Duplicate of #764.

**Comment by joshreeder** [comment]
@jwngr A little confused as to why this is a duplicate. It doesn't seem to be referenced in the duplicate card and doesn't seem to be available and seems like a good idea. What am I missing?
