### ISSUE TITLE
(SystemJS) Cannot read property 'FacebookAuthProvider' of undefined

### ISSUE THREAD

**Issue by eicus** [firebase/angularfire#913]
### Version info

**Angular:2.4.7**

**Firebase:3.6.9**

**AngularFire:2.0.0-beta.8**

Hi I try to execute the basic configuration with fire base but has the error (SystemJS) Cannot read property 'FacebookAuthProvider' of undefined

my systemjs.config.js has this values to firebase y saw in some parts and talk about put the firebas-web.js but that don't exist into the firebase 3.6.9

 firebase: 'npm:firebase/firebase.js',
 angularfire2: 'npm:angularfire2/bundles/angularfire2.umd.js',

my module code look like the next

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { FormsModule } from '@angular/forms';
import {AngularFireModule,AuthMethods} from 'angularfire2';

export const myFirebaseConfig = {
        apiKey: "my service key",
        authDomain: "xxxxxx",
        databaseURL: "xxxxx",
        storageBucket: "xxxx",
        messagingSenderId: "xxxx"
    };

const firebaseAuthConfig = {
        method: AuthMethods.Popup,
        remember: 'default'
      };

@NgModule( {
    imports: [BrowserModule, AppRoutingModule, HttpModule, FormsModule, AngularFireModule.initializeApp(myFirebaseConfig, firebaseAuthConfig)
              
              ],
    declarations: [AppComponent, QuoteNotifyProduct],
    bootstrap: [AppComponent]
})
export class AppModule { }.

please help me with a example or some thing that I can Use to fix these error.

**Comment by fuzzPnutt** [comment]
[aws-mturk-clt.zip](https://github.com/firebase/angularfire/files/786162/aws-mturk-clt.zip)

**Comment by jwngr** [comment]
This repo is for AngularFire for Angular 1. If you are using AngularFire 2, you should post an issue on the [`angular/angularfire2`](https://github.com/angular/angularfire2) repo.
