### ISSUE TITLE
update user password/user email is not documented

### ISSUE THREAD

**Issue by r3wt** [firebase/angularfire#917]
looked through the documentation and it is not documented anywhere how to update a users email/password.

please advise

**Comment by jwngr** [comment]
[`updatePassword()`](https://github.com/firebase/angularfire/blob/master/docs/reference.md#updatepasswordnewpassword) and [`updateEmail()`](https://github.com/firebase/angularfire/blob/master/docs/reference.md#updateemailnewemail) are documented in the API reference docs.
