### ISSUE TITLE
Transactions refresh listing in Safari/iOS

### ISSUE THREAD

**Issue by ix-xerri** [firebase/angularfire#919]
### Version info

**Angular:**
2.3.1 (tried on 2.4.8)
**Firebase:**
3.3.0
**AngularFire:**
2.0.0-beta.8
**Other (e.g. Node, browser, operating system) (if applicable):**
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
### Test case

Whenever you try to implement a transaction the list gets refreshed inside Safari / iOS (in ionic 2 - tested on device). I notice it because part of my list is an image url. Anything that changes in the transaction, the image get reloaded.

This is the function that is called when you click a button. The action is for a simple like button. If you click the like button twice, it unlikes and image. Simple Instagram scenario here. Work normal in Chrome. Note that there are no transaction in Angularfire.

    const workoutLikes = firebase.database().ref('/workouts').child(this.workout.$key + "/likes/" + email);

    // Like and unlike depending on the state
    workoutLikes.transaction(function(likes) {
        // If no like
        if(likes === null) {
          return 1;
        }

        likes++;

        return likes;
    });`

**Comment by jwngr** [comment]
It looks like you are using [AngularFire2](https://github.com/angular/angularfire2), which is a different library than this repo. This repo is for use in Angular `1.x.x`. Please open an issue in the [AngularFire2](https://github.com/angular/angularfire2) repo.
