### ISSUE TITLE
$firebaseStorage inject Provider Error

### ISSUE THREAD

**Issue by itsShailz** [firebase/angularfire#920]
I am currently having the issue where I'm using $firebaseStorage as an injection dependency in my ionic project, however it returns the following error message:

Error: [$injector:unpr] Unknown provider: $firebaseStorageProvider <- $firebaseStorage <- UploadCtrl

Would you be able to assist me in this matter please?

**Comment by jwngr** [comment]
Please open up a new issue which follows the issue template. Thanks!
