### ISSUE TITLE
Can't set redirectUrl for localhost testing

### ISSUE THREAD

**Issue by megamindbrian** [firebase/angularfire#933]
I am no longer being forwarded back to localhost when running my app in development mode.  I use to be able to log in with Google and get the token back on the app.  Now it just redirects back to the authDomain instead of the domain that it came from.

**Comment by davideast** [comment]
Hi @megamindbrian ! We have a required issue template. I'm going to close this issue, but free to open a new one that follows the template. Also if you could provide a plnkr that demonstrates the problem that would help out tremendously!

**Comment by ghost** [comment]
_
