### ISSUE TITLE
'403 Forbidden' for facebook photoURL in Ionic

### ISSUE THREAD

**Issue by remisture** [firebase/angularfire#935]
Hi,

I can suddenly no longer load the profile images from the Facebook Auth provider in my Ionic app. I just get '403 Forbidden'. I have the 'cordova-whitelist-plugin' and have set < access origin="*"/> in my config.xml, and have not done any code changes. This worked before. 

Can it be anything related to this library?

I'm able to get around the problem by fetching the image manually, so it doesn't seem to be a whitelist/content-security-policy issue.

```
$firebaseAuth().$onAuthStateChanged(function (user) {
   if (user) {
      user.providerData.forEach(function (profile) {
         if (profile.providerId === "facebook.com") {
            user.updateProfile({
               photoURL : "https://graph.facebook.com/" + profile.uid + "/picture?height=200"
            });
         }
     });
   }
});
```

Thanks

**Comment by davideast** [comment]
Hi @remisture! We have a required issue template. I'm going to close this for now, but feel free to open with an issue that follows the template.
