### ISSUE TITLE
refresh_token for Google oauth2

### ISSUE THREAD

**Issue by davittomasso** [firebase/angularfire#936]
We use angularfire google authentication in our angular app. We chose Google because our application makes Google API calls from backend. We authorize these api calls with the access_token included in authorization payload that is returned from firebase. However, we are having trouble figuring out how to refresh the access_token after it expires. Even if we set access_type to offline it doesn't help. Seems we receive totally another refresh token and we can't use it to refresh access_token.

Finally it isn't currently possible to get a Google OAuth **VALID** refresh token via Firebase.

**Comment by davideast** [comment]
Hi @davittomasso ! We have a required issue template. I'm going to close this issue, but free to open a new one that follows the template.
