### ISSUE TITLE
$firebaseObject.$loaded not firing EVER .catch nor reject function

### ISSUE THREAD

**Issue by klifa90** [firebase/angularfire#937]
Example code

```
 var objRef = ref.child( clientId );
  return $firebaseObject( objRef ).$loaded( function( resp ) {
      return resp;
    }, function (exp)
    {
      return exp;
    });
```

The reject function will never be called.
If I have wifi/network connection then i will get the .then/resolve function called properly, but if i just turn off wifi and call this method again, it will hang forever...

Am i doing something wrong here? Is it possible to define a 10s timeout for this (without doing nasty stuff)?

P.D. i have updated today to the latest version available

Thanks

**Comment by kaufi07** [comment]
+1
I have a similar problem. When accessing the angular app directly in the browser (via local server or production server) everything is working fine. But when our Prerender service (PhantomJS) tries to launch the angular app the firebase data cannot be accessed and $loaded functions are never firing. 
Also I tried to increase the timeout but that did not help.

**Comment by davideast** [comment]
Hi @klifa90! We have a required issue template. I'm going to close this issue, but free to open a new one that follows the template. Also if you could provide a plnkr that demonstrates the problem that would help out tremendously!
