### ISSUE TITLE
$firebasearray.$save is not saving the data to firebase

### ISSUE THREAD

**Issue by MrSumant** [firebase/angularfire#938]
I have an application where I am trying to watch for changes in a controller variable and saving it to firebase if any change happens i.e. 3-way binding.

service.js

    ` var ref = firebase.database().ref('checklists').orderByChild('checklistName').equalTo('Sample Firebase Sumant');
                var obj = $firebaseObject(ref);

                obj.$loaded().then(function () {
                    var key = Object.keys(obj);
                    var treeRef = firebase.database().ref('checklists/' + key[4] + '/tree');
                    fullTreeCache = $firebaseArray(treeRef);
                    fullTreeCache.$loaded().then(function () {
                        compressedTree = clipChildren(fullTreeCache);
                        console.log(compressedTree);
                        promise.resolve(raw ? fullTreeCache : compressedTree);
                    });`
controller.js
`vm.firebaseData =checklistTreeService.getFullTree();
        $scope.$watch(function () {
             return vm.firebaseData;
           },function() {
         vm.firebaseData.$save($scope,vm.firebaseData);
         }, true);`
   
$save statement is executing when I change a piece of data without any console errors but it's not getting saved to the firebase realtime database. Please help me out if there is something wrong with my approach.

**Comment by davideast** [comment]
Hi @MrSumant! We have a required issue template. I'm going to close this issue, but free to open a new one that follows the template. Also if you could provide a plnkr that demonstrates the problem that would help out tremendously!
