### ISSUE TITLE
ios pwa firebase redirect auth mode doesnt work

### ISSUE THREAD

**Issue by ezequielzacca** [firebase/angularfire#942]
**Angular:** 4.1.1

**Firebase:** 3.9.0

**AngularFire:** 4.0.0.-rc1

### Steps to reproduce

Use angularfire2 with google as provider, create manifest.json and add the page to the home screen, then try to login using google

### Expected behavior

should go to the screen to select wich google account u want to use (if you have several) if you have one should return to the page with the login data

### Actual behavior

you get disallowed_useragent when initiating google OAuth flow

-----------------------------------------

When you try to use google authentication using angularfire2, you cannot if you have a pwa on ios, this is really a huge problem for PWA and actually i think is critical, probably related to 
[this stackoverflow](https://stackoverflow.com/questions/43745462/google-oauth-no-longer-supported-for-progressive-applications)

**Comment by davideast** [comment]
@ezequielzacca Do you have a github repo that demonstrates this problem?

**Comment by rakeshdausa** [comment]
I am also facing same issue. Does any one get the solution of this problem?

**Comment by ezequielzacca** [comment]
this is sad, seems like apple doesnt want PWA's to grow, with this and the poor and sad implementation of serviceworkers in safari :(

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by jamesdaniels** [comment]
Closing as stale.
