### ISSUE TITLE
Documentation for $getAuth is ambiguous

### ISSUE THREAD

**Issue by curiouslybrown** [firebase/angularfire#944]
When the documentation for $getAuth() says that it's synchronous, I took that to mean that it will block the browser until it has the auth information. This is important when the page first loads and the user already is logged in. getAuth() won't wait until that initial auth check has been completed

**Comment by alexsales** [comment]
$getAuth() is just a wrapper for the Firebase Auth service's `.currentUser` property and checks that the user hasn't timed-out or logged out from the client-side (so there shouldn't be any waiting or server requests with this simple client-side check).

To check if a user is logged in initially:
```
var user = $firebaseAuth().$getAuth();

if (user) {
 // signed in as user.uid
} else {
 // signed out
}
```

And to have your application pay attention to subsequent log-ins/log-outs/time-outs after the initial auth check, you'll want to add a listener using `$onAuthStateChanged()`:
```
$firebaseAuth().$onAuthStateChanged(function(user) {
  if (user) {
    // signed in as user.uid
  } else {
    // signed out
  }
});
```
