### ISSUE TITLE
ui-router example not correct when using ui-router v1.0.x

### ISSUE THREAD

**Issue by githubmonkey** [firebase/angularfire#945]
https://github.com/firebase/angularfire/blob/master/docs/guide/user-auth.md#ui-router-example

I believe the recommendation for router auth is not longer correct for ui-router version 1.0.x. 

The issue is that $rootScope.$on("$stateChangeError", ...) is not longer fired as documented here: https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-change-events

**Comment by davideast** [comment]
Hi @githubmonkey! We have a required issue template. I'm going to close this issue, but feel free to open a new one that follows the template. 

In your new issue if you could also provide a plnkr demonstrating the problem that would help out tremendously!
