### ISSUE TITLE
Is it possible to save a complete path?

### ISSUE THREAD

**Issue by newmesiss** [firebase/angularfire#946]
I am a query, I have been searching for information for a long time, it is possible to save a complete path like vm.datas.$save() considering that within dates I have an array?

![image](https://user-images.githubusercontent.com/5264883/28686473-562ecae4-72d9-11e7-9277-552b701824da.png)

**Comment by davideast** [comment]
Hi @newmesiss! We have a required issue template. This question seems more suited for Stackoverflow as this repo is dedicated to troubleshooting library issues.
