### ISSUE TITLE
how to use signInWithPhoneNumber ?

### ISSUE THREAD

**Issue by krazylearner** [firebase/angularfire#952]
is this sdk exposes "signInWithPhoneNumber" method

**Comment by davideast** [comment]
Hi @krazylearner! We have a required issue template which is helpful to know what versions you are using. 

Phone number auth is not currently supported and there are no plans of adding support. Please refer to the docs and use the regular Firebase SDK for phone number auth. It's not an anti-pattern to use the regular SDK for custom needs or unsupported features.
