### ISSUE TITLE
Firebase Real Time Database (Insertion to table)

### ISSUE THREAD

**Issue by Snehitha09** [firebase/angularfire#953]
[data (1).zip](https://github.com/firebase/angularfire/files/1263269/data.1.zip)
Hello,
 Had a clarification, if you could please guide me,
i have a table with 2 root nodes
1)Parent
2)Child
So when i do a post information to parent a key is added along with the values i pass,
Now in the child root i would want to reference the corresponding parent and then generate a specific key to the child and then the values that i have passed, so this is how i would want, will attach an example

### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Node, browser, operating system) (if applicable):**

**Comment by davideast** [comment]
Hi @Snehitha09! Please use Stackoverflow for these kinds of posts as this repo is dedicated to troubleshooting library issues. Thanks!
