### ISSUE TITLE
Wrong doc: AngularFire by Bower is accessed by 'firebase' and not 'angularfire'

### ISSUE THREAD

**Issue by jackie-d** [firebase/angularfire#954]
As in the description, I found wrong information in the docs.

The module name in not specified or inaccurate.

Point 2 of [](https://github.com/firebase/angularfire/blob/master/docs/quickstart.md)

And it is not specified in [](https://github.com/firebase/angularfire#getting-started-with-firebase)

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
