### ISSUE TITLE
Firebase storage support rest API 

### ISSUE THREAD

**Issue by almgwary** [firebase/angularfire#955]
=D 

I don't know where should i put this issue, there is no repo for Firebase API . 
Firebase should support rest API  for storage . i am using angular, i don't need to update dependency each version . i just need to use rest API without depending on library , becouse after upgrade to Angular 4, I have to upgrade Angularfire too to make `ng build --prod --aot` . which is time consuming .

**Comment by puf** [comment]
For Firebase products that don't have a public issue tracker, please [file a feature request through our support team](https://firebase.google.com/support/contact/bugs-features/).
