### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by niyoma** [firebase/angularfire#957]
I have used angularfire in my cordova app
It is working fine on browser.
but when i am testing app on device it is giving me 404 error for 

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular.min.js"></script>

<script src="https://www.gstatic.com/firebasejs/3.6.6/firebase.js"></script>

<script src="https://cdn.firebase.com/libs/angularfire/2.3.0/angularfire.min.js"></script>
these scripts

Please help me with it.
Is angular fire is  supported in cordova? 
do i need to add some dependencies?

**Comment by Joebob12** [comment]
Just wanted to bump this as i'm getting the same issue here with Ionic. Do you have  `<access origin="*" />` in your config.xml? I thought that was the issue but still getting 404 only when I'm emulating in android.

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
