### ISSUE TITLE
Multiple firebase projects

### ISSUE THREAD

**Issue by tbone849** [firebase/angularfire#958]
I would like to be able to configure angularfire to handle multiple firebase projects. Configuring multiple projects is possible via the [firebase docs](https://firebase.google.com/docs/configure/#use_multiple_projects_in_your_application), but from what I can find, angularfire can only handle one project (default) at a time. Below is the code to initialize a second project. However I can't find if angularfire can distinguish between the two.

```
var secondaryAppConfig = {
    apiKey: "<API_KEY>",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
    storageBucket: "<BUCKET>.appspot.com",
};

// Initialize another app with a different config
var secondary = firebase.initializeApp(secondaryAppConfig, "secondary");

// Retrieve the database.
var secondaryDatabase = secondary.database();
```

**Comment by puf** [comment]
Also posted on: https://stackoverflow.com/q/46821178

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
