### ISSUE TITLE
Updating AngularJS View when Scope has changed using $watch

### ISSUE THREAD

**Issue by gregdevs** [firebase/angularfire#959]
Hi, I am using AngularJS 1.6 along with AngularFire 2.3. 
I'm a bit stuck ATM...

I have some data stored in Firebase and when a child value changes, I would like the scope to change along with the View.
For some reason when I make a change in the Firebase DB, and I log the scope.. it is reflecting the new data, however the changes aren't making it into the angular view.
```
var furryPostsRef = firebase.database().ref('stories/' + storyId + "/correspondents").orderByChild('published').equalTo(true);
var fbObj = $firebaseObject(furryPostsRef);
fbObj.$watch(function(){
//do stuff
$scope.stuff = fbObj;
console.log($scope.stuff)
//everytime a change happens on the Firebase server, This is logging correct
});
```
Not exactly sure where I;m going wrong here.
Thanks

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
