### ISSUE TITLE
How to implement the load more in firebase in AngularJs?

### ISSUE THREAD

**Issue by kapilSoni101** [firebase/angularfire#960]
Hello sir,
I have create a ecommerce website in AngualrJs and backend is firebase.i have to get the product list from the firebase and i am using - limitToFirst() query for get the initially record's and i want to load more functionlity so sir tell me how to implement te load more in our website?
`$scope.getProductData = function() {
          //GET THE DATA FROM THE FIREABSE  
          firebase.database().ref("sellerProduct").limitToFirst(2).once('value').then(function(snapshot) {
             var value = snapshot.val();
               $scope.productArray = objToArray(value);
  });
}
$scope.getProductData();`

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
