### ISSUE TITLE
Error: Metadata version mismatch for module node_modules/angularfire2/index.d.ts, found version 4,

### ISSUE THREAD

**Issue by kpvsrkp** [firebase/angularfire#971]
### Version info

**Angular:**

angular-cli: 1.0.0-beta.28.3
node: 6.11.0
os: win32 x64
angular/common: 4.4.4
angular/compiler: 4.4.4
angular/compiler-cli: 4.4.4
angular/core: 4.4.4
angular/forms: 4.4.4
angular/http: 4.4.4
angular/platform-browser: 4.4.4
angular/platform-browser-dynamic: 4.4.4

**Firebase:**
firebase --version  => 3.18.4
package.json  => "firebase": "^5.0.4"

**AngularFire:**
package.json  =>  ^5.0.0-rc.8.1-next

**Other (e.g. Node, browser, operating system) (if applicable):**

**Browser** 
Chrome

**Node**
6.11.0

**Ionic**
3.20.0

### Test case

Doing a prod build using 
npm run ionic:build --prod

### Expected behavior

Should get build successfully.

### Actual behavior

[00:01:05]  Error: Metadata version mismatch for module /node_modules/angularfire2/auth/index.d.ts, found   version 4, expected 3

I got many solutions from [github](https://github.com/angular/angularfire2/issues/1397) and [stackoverflow](https://stackoverflow.com/questions/47441625/angular-4-angularfire2-metadata-version-mismatch).  It works but I am loosing the storage module from angularfire2 if I downgrade it to advised versions in the solutions.  I need storage module as well with resolution for this error. Please advise.

**Comment by fdambrosio** [comment]
I have the same problem

**Comment by gsdiama** [comment]
Hi,

Same problem here. Does anyone have a solution?

Thanks in advance.

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
