### ISSUE TITLE
JS console error displaying my API Key on failed login - Chrome only

### ISSUE THREAD

**Issue by nasquam** [firebase/angularfire#972]
### Version info

**Angular: 

https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js
https://code.angularjs.org/1.6.9/angular-route.min.js

**Firebase:**

https://www.gstatic.com/firebasejs/3.6.6/firebase.js

**AngularFire:**

https://cdn.firebase.com/libs/angularfire/2.3.0/angularfire.min.js

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

From this code base:
https://github.com/nasquam/angular-firebase/tree/69f6576ab5cad0ee1aeb641820d26dd5994c4fc5
Image of the error:
https://angular-firebase-92878.firebaseapp.com/assets/img/post_error.PNG

### Steps to reproduce

Attempt a login with a bad username and password in the google Chrome browser

### Expected behavior

Not to have my API key exposed in the JS console.... 

### Actual behavior
![post_error](https://user-images.githubusercontent.com/2468328/41364591-1ff64028-6f05-11e8-9d61-e24a20ae1b1f.PNG)

There's a warning message printing in the JS console that has my API key in it.

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
