### ISSUE TITLE
Your library does not support callbacks for set(), push(), while Firebase does

### ISSUE THREAD

**Issue by trobbins1981** [firebase/angularfire#973]
We have a large codebase with the older firebase in it (2.x), which supported callbacks for set() and push() operations.  Now, we are converting to Firebase 5.2.1, which still supports the callbacks for compatibility purposes.  However, your library does not support callbacks.  This means that if i want to use mock-firebase, I must convert my whole codebase over to use promises.   

**Angular:**
1.5.9

**Firebase:**
5.2.0

**AngularFire:**
2.3.0

**Other (e.g. Node, browser, operating system) (if applicable):**

Node 8.9.4

### Expected behavior

I expect that your library would be a drop-in replacement for firebase, meaning it would support callbacks

### Actual behavior

my callbacks never get called

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
