### ISSUE TITLE
ng build --prod || Can't resolve './public_api' in '/node_modules/angularfire2/database'

### ISSUE THREAD

**Issue by ohabash** [firebase/angularfire#976]
**Angular:** 
^6.1.7

**Firebase:** 
^5.0.0-rc.10

**AngularFire:** 
^5.0.4

### Steps to reproduce

Im getting the following error after `ng build --prod`

### Actual behavior

>ERROR in ./node_modules/angularfire2/database/index.js
Module not found: Error: Can't resolve './public_api' in '/Users/Sites/fornida-ng6/node_modules/angularfire2/database'

>ERROR in ./node_modules/angularfire2/firestore/index.js
Module not found: Error: Can't resolve './public_api' in '/Users/Sites/fornida-ng6/node_modules/angularfire2/firestore'

### package.json

	{
	  "name": "fornida-ng6",
	  "version": "0.0.0",
	  "scripts": {
	    "ng": "ng",
	    "build": "ng build",
	    "test": "ng test",
	    "lint": "ng lint",
	    "e2e": "ng e2e",
	    "prestart": "ng build --prod && ngc",
	    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
	    "serve:ssr": "node dist/server",
	    "build:client-and-server-bundles": "ng build --prod && ng run fornida-ng6:server",
	    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
	  },
	  "private": true,
	  "dependencies": {
	    "@angular/animations": "^6.1.7",
	    "@angular/common": "^6.1.7",
	    "@angular/compiler": "^6.1.7",
	    "@angular/core": "^6.1.7",
	    "@angular/forms": "^6.1.7",
	    "@angular/http": "^6.1.7",
	    "@angular/platform-browser": "^6.1.7",
	    "@angular/platform-browser-dynamic": "^6.1.7",
	    "@angular/platform-server": "^6.1.7",
	    "@angular/router": "^6.1.7",
	    "@angular/service-worker": "^6.1.7",
	    "@ng-toolkit/universal": "^1.1.41-beta.110",
	    "@nguniversal/express-engine": "^6.1.0",
	    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
	    "angularfire2": "^5.0.0-rc.10",
	    "core-js": "^2.5.4",
	    "desandro-classie": "^1.0.1",
	    "express": "^4.16.3",
	    "firebase": "^5.0.4",
	    "font-awesome": "^4.7.0",
	    "jquery": "^3.3.1",
	    "jsoneditor": "^5.24.6",
	    "jwt-decode": "^2.2.0",
	    "jwt-simple": "^0.5.1",
	    "ng-snotify": "^4.3.1",
	    "ngx-slick": "^0.1.3",
	    "node-bigcommerce": "^3.0.0",
	    "rellax": "^1.7.0",
	    "request": "^2.88.0",
	    "rxjs": "^6.2.1",
	    "rxjs-compat": "^6.2.1",
	    "sticky-js": "^1.2.0",
	    "ts-loader": "^5.1.1",
	    "zone.js": "^0.8.26"
	  },
	  "devDependencies": {
	    "@angular-devkit/build-angular": "~0.6.8",
	    "@angular/compiler-cli": "^6.1.7",
	    "@angular/language-service": "^6.1.7",
	    "@nativescript/schematics": "^0.3.1",
	    "@types/jasmine": "~2.8.6",
	    "@types/jasminewd2": "~2.0.3",
	    "@types/jquery": "^3.3.6",
	    "@types/node": "^8.10.29",
	    "codelyzer": "~4.2.1",
	    "jasmine-core": "~2.99.1",
	    "jasmine-spec-reporter": "~4.2.1",
	    "karma": "~1.7.1",
	    "karma-chrome-launcher": "~2.2.0",
	    "karma-coverage-istanbul-reporter": "^2.0.4",
	    "karma-jasmine": "~1.1.1",
	    "karma-jasmine-html-reporter": "^0.2.2",
	    "protractor": "~5.3.0",
	    "ts-node": "~5.0.1",
	    "tslint": "~5.9.1",
	    "typescript": "~2.7.2",
	    "webpack-cli": "^3.1.0"
	  }
	}

**Comment by ohabash** [comment]
Here is what i did 

1. `npm uninstall angularfire2 firebase`
2. `npm install @angular/fire firebase --save`
3. changed import paths from `/angularfire2` to `/@angular/fire` in `app.module.ts`
4. updated import paths in any component using angularfire

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg
