### ISSUE TITLE
firestorage $putString callbacks not binding

### ISSUE THREAD

**Issue by bondseid** [firebase/angularfire#977]
**Angular: 1.7.4 **

**Firebase:3.9.0**

**AngularFire:2.3.0**

### Test case

let photoStorage = $firebaseStorage(ref);
let uploadTask = photoStorage.$putString("data:string", "data_url");
uploadTask.then();

firebase.js:585 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at Object.T.then (firebase.js:585)

This error is thrown for all callbacks. $complete, .catch etc...

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by Yngdev31** [comment]
Have you find a solution for this ? I have the same problem ...

**Comment by jamesdaniels** [comment]
Sorry for the radio silence, as you might've gathered we're not investing in AngularFire at the moment, advising folk migrate to Angular and `@angular/fire` instead.
