### ISSUE TITLE
Firestore support

### ISSUE THREAD

**Issue by sundsx** [firebase/angularfire#979]
Please support Firestore! I spent a lot of time for angularjs and honestly don't like me angular 2. I have app up and running and need o update to Firestore new cloud realtime database. Please Help developer...

Thank you

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by jamesdaniels** [comment]
Thanks for the feedback, however at this point we're considering the library to be finished and are advising folk migrate to Angular and `@angular/fire`.
