### ISSUE TITLE
Dependency Update

### ISSUE THREAD

**Issue by Miguel-Alberto** [firebase/angularfire#980]
A handful of dependencies have known vulnerabilities in the required versions. A little housekeeping to resolve theses would be much appreciated. 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/36014895/53954744-16ee2c80-40a5-11e9-90c4-cdc320398a51.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/36014895/53954754-1ce40d80-40a5-11e9-9024-d78dc157e59e.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/36014895/53954765-23728500-40a5-11e9-9dcf-82f32ca0dbb0.png">

**Comment by Bktechmasala** [comment]
forgot password reset link , see the video link completely solved 
https://youtu.be/daGZO6YAkRg

**Comment by Miguel-Alberto** [comment]
@davideast resolved, or?
